goog.provide('exports');


goog.require('authentication');
goog.require('closurequery');
goog.require('controllers');
goog.require('datastore');
goog.require('debug');
goog.require('require');
goog.require('services');
goog.require('stream');
goog.require('ui');
window['authentication'] = authentication;
window['authentication']['cookieAge'] = authentication.cookieAge;
window['authentication']['token'] = authentication.token;
window['authentication']['userid'] = authentication.userid;
window['authentication']['username'] = authentication.username;
window['authentication']['init'] = authentication.init;
window['authentication']['getUsername'] = authentication.getUsername;
window['authentication']['hash'] = authentication.hash;
window['authentication']['login'] = authentication.login;
window['authentication']['logout'] = authentication.logout;
window['authentication']['createUser'] = authentication.createUser;
window['authentication']['changePassword'] = authentication.changePassword;
window['closurequery'] = closurequery;
window['controllers'] = controllers;
window['datastore'] = datastore;
window['datastore']['data'] = datastore.data;
window['datastore']['root'] = datastore.root;
window['datastore']['group'] = datastore.group;
window['datastore']['lastPlayed'] = datastore.lastPlayed;
window['datastore']['track'] = datastore.track;
window['datastore']['user'] = datastore.user;
window['debug'] = debug;
window['debug']['log'] = debug.log;
window['debug']['logFoo'] = debug.logFoo;
window['debug']['logVal'] = debug.logVal;
window['debug']['lucky'] = debug.lucky;
window['require'] = require;
window['services'] = services;
window['services']['metadata'] = services.metadata;
window['services']['search'] = services.search;
window['services']['stream'] = services.stream;
window['stream'] = stream;
window['stream']['isPlaying'] = stream.isPlaying;
window['stream']['newTime'] = stream.newTime;
window['stream']['newTimeProcessed'] = stream.newTimeProcessed;
window['stream']['player'] = stream.player;
window['stream']['syncTimeouts'] = stream.syncTimeouts;
window['stream']['init'] = stream.init;
window['stream']['isFinished'] = stream.isFinished;
window['stream']['length'] = stream.length;
window['stream']['loadTrack'] = stream.loadTrack;
window['stream']['mute'] = stream.mute;
window['stream']['onFinished'] = stream.onFinished;
window['stream']['play'] = stream.play;
window['stream']['processTime'] = stream.processTime;
window['stream']['sync'] = stream.sync;
window['stream']['time'] = stream.time;
window['stream']['updateNowPlaying'] = stream.updateNowPlaying;
window['stream']['volume'] = stream.volume;
window['ui'] = ui;
window['ui']['pageLoadingClass'] = ui.pageLoadingClass;
window['ui']['playButtonClass'] = ui.playButtonClass;
window['ui']['slider'] = ui.slider;
window['ui']['init'] = ui.init;
window['ui']['update'] = ui.update;
window['datastore']['data']['group'] = datastore.data.group;
window['datastore']['data']['lastPlayed'] = datastore.data.lastPlayed;
window['datastore']['data']['lastPlayed']['processed'] = datastore.data.lastPlayed.processed;
window['datastore']['data']['track'] = datastore.data.track;
window['datastore']['data']['user'] = datastore.data.user;
window['datastore']['data']['user']['current'] = datastore.data.user.current;
