goog.provide('exports');
goog.require('require');
goog.require('authentication');
/** @expose */\nauthentication = authentication;
goog.require('closurequery');
/** @expose */\nclosurequery = closurequery;
goog.require('controllers');
/** @expose */\ncontrollers = controllers;
goog.require('datastore');
/** @expose */\ndatastore = datastore;
goog.require('debug');
/** @expose */\ndebug = debug;
goog.require('require');
/** @expose */\nrequire = require;
goog.require('services');
/** @expose */\nservices = services;
goog.require('stream');
/** @expose */\nstream = stream;
goog.require('ui');
/** @expose */\nui = ui;
