function g(a){throw a;}var j=void 0,l=!0,m=null,q=!1;function aa(a){return function(b){this[a]=b}}function ba(a){return function(){return this[a]}}var t,u=this;function ca(a,b){var c=a.split("."),d=u;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&v(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function da(){}
function ea(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function v(a){return a!==j}function fa(a){return"array"==ea(a)}function ga(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length}function x(a){return"string"==typeof a}function ha(a){return"function"==ea(a)}function ia(a){var b=typeof a;return"object"==b&&a!=m||"function"==b}function ja(a){return a[ka]||(a[ka]=++la)}var ka="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),la=0;
function ma(a,b,c){return a.call.apply(a.bind,arguments)}function na(a,b,c){a||g(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function y(a,b,c){y=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ma:na;return y.apply(m,arguments)}var B=Date.now||function(){return+new Date};
function C(a,b){function c(){}c.prototype=b.prototype;a.i=b.prototype;a.prototype=new c;a.prototype.constructor=a};var F=new function(){var a=this;a.o=function(){function b(){}function c(a){(a=a.data==YT.PlayerState.PLAYING?window.Id:a.data==YT.PlayerState.ENDED?window.xf:m)&&a();D.update()}function d(){var b=new oa(function(){return window.je});b.Hd=function(){a.Gd()};b.start()}window.Th=function(){a.p=new YT.Player(pa("#stream")[0],{height:"390",width:"640",Oh:"1",Ih:{onReady:d,onStateChange:c,onError:b}})};E.j().kb.m.setOnDisconnect(q);E.j().kb.Kb.setOnDisconnect(0);a.Nc=[]};a.ef=function(){return a.time()>=
a.length()};a.length=function(){return a.p.getDuration()};a.td=function(b,c,d){a.p.stopVideo();a.time(0,l);window.Id=function(){window.Id=m;window.setTimeout(function(){F.volume(0);a.time(0,l);a.play(l,l);E.h(a.ua).length.set(a.length());c&&c()},2E3)};E.h(b).once("value",function(c){var f=c.val();c=c.name();D.z.Vb(f.length);E.h(b).w.set(Date.now());E.h(b).xc.set(H.$a);E.w().push(c);a.p.loadVideoById(f.Fa);a.ua=b;d!=l&&(E.h(b).Dc.set(++f.Dc),a.Yb());c=E.data.j.current.Z.Va;for(var h in c)f=c[h],f.Ad=
f.id==a.ua?"now-playing":""})};a.mute=function(b){b!=q?a.p.mute():a.p.unMute()};a.Gd=function(b){window.xf=function(){a.play(q);window.clearInterval(D.z.Jd);b&&b()}};a.play=function(b,c){a.m=b==q?q:l;a.m?a.volume(100):a.volume(0);window.clearInterval(D.z.Jd);a.m&&(D.z.Jd=window.setInterval(function(){!D.z.Td&&a.m&&a.time()},500));a.m?a.p.playVideo():a.p.pauseVideo();D.update();a.time();c!=l&&a.Yb()};a.Fc=function(a){a=a||0;return(60>a?"0:":"")+(10>a?"0":"")+([].add((new Date(0,0,0,0,0,a)).toLocaleTimeString().match(/[^0:].*/))[0]||
0)};a.Sd=function(b){b=b||H.$a;var c=E.j(b);E.j(E.data.j.current.Zc).kb.Kb.off();E.j().Zc.set(b);c.kb.Kb.on("value",function(b){b=b.val();var e=(Date.now()-b)/1E3;c.pa.once("value",function(b){var c=b.val(),d=c.time+(c.m?e:0);c.h!=a.ua?a.td(c.h,function(){a.Nc[0]=window.setTimeout(function(){c.h==a.ua&&a.p.pauseVideo();a.Nc[1]=window.setTimeout(function(){c.h==a.ua&&(a.play(c.m,l),a.time(d,l))},3E3)},3E3)},l):(c.m?a.p.playVideo():a.p.pauseVideo(),a.time(d,l));D.update()})})};a.time=function(b,c){if((b=
0===b?1:b)&&5>Math.abs(b-a.time()))return b;b&&(a.R=b,c!=l?a.Yb():a.p.seekTo(b,l));if((b>=a.length()||a.p.getCurrentTime()>=a.length())&&a.m)a.m=q,a.R=0,D.update();a.R=a.p.getCurrentTime()||a.R;a.tf=a.Fc(a.R);a.R&&E.j().kb.time.set(a.R);qa(D.z,a.R);D.update();return a.R};a.Yb=function(){E.j().pa.set({m:a.m,Kb:Date.now(),time:a.R,h:a.ua});D.update()};a.volume=function(b){window.isNaN(b)||a.p.setVolume(b);return a.p.getVolume()}};function I(){0!=ra&&(this.Eh=Error().stack,sa[ja(this)]=this)}var ra=0,sa={};I.prototype.gc=q;I.prototype.u=function(){if(!this.gc&&(this.gc=l,this.d(),0!=ra)){var a=ja(this);delete sa[a]}};I.prototype.d=function(){this.le&&ta.apply(m,this.le);if(this.Fd)for(;this.Fd.length;)this.Fd.shift()()};function ta(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];ga(d)?ta.apply(m,d):d&&"function"==typeof d.u&&d.u()}};function J(a,b){this.type=a;this.currentTarget=this.target=b}t=J.prototype;t.d=function(){};t.u=function(){};t.Wa=q;t.defaultPrevented=q;t.Tb=l;t.preventDefault=function(){this.defaultPrevented=l;this.Tb=q};function ua(a){a.preventDefault()};function va(){}var wa=0;t=va.prototype;t.key=0;t.Ba=q;t.ub=q;t.o=function(a,b,c,d,e,f){ha(a)?this.od=l:a&&a.handleEvent&&ha(a.handleEvent)?this.od=q:g(Error("Invalid listener argument"));this.Qa=a;this.Kd=b;this.src=c;this.type=d;this.capture=!!e;this.Eb=f;this.ub=q;this.key=++wa;this.Ba=q};t.handleEvent=function(a){return this.od?this.Qa.call(this.Eb||this.src,a):this.Qa.handleEvent.call(this.Qa,a)};function xa(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function ya(a){if(!za.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Aa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ba,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ca,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Da,"&quot;"));return a}var Aa=/&/g,Ba=/</g,Ca=/>/g,Da=/\"/g,za=/[&<>\"]/;Math.random();var Ea,Fa,Ga,Ha,Ia,Ja,Ka;function La(){return u.navigator?u.navigator.userAgent:m}function Ma(){return u.navigator}Ha=Ga=Fa=Ea=q;var Na;if(Na=La()){var Oa=Ma();Ea=0==Na.indexOf("Opera");Fa=!Ea&&-1!=Na.indexOf("MSIE");(Ga=!Ea&&-1!=Na.indexOf("WebKit"))&&Na.indexOf("Mobile");Ha=!Ea&&!Ga&&"Gecko"==Oa.product}var Pa=Ea,K=Fa,L=Ha,M=Ga,Qa,Ra=Ma();Qa=Ra&&Ra.platform||"";Ia=-1!=Qa.indexOf("Mac");Ja=-1!=Qa.indexOf("Win");Ka=-1!=Qa.indexOf("Linux");Ma()&&(Ma().appVersion||"").indexOf("X11");
function Sa(){var a=u.document;return a?a.documentMode:j}var Ta;a:{var Ua="",Va;if(Pa&&u.opera)var Wa=u.opera.version,Ua="function"==typeof Wa?Wa():Wa;else if(L?Va=/rv\:([^\);]+)(\)|;)/:K?Va=/MSIE\s+([^\);]+)(\)|;)/:M&&(Va=/WebKit\/(\S+)/),Va)var Xa=Va.exec(La()),Ua=Xa?Xa[1]:"";if(K){var Ya=Sa();if(Ya>parseFloat(Ua)){Ta=String(Ya);break a}}Ta=Ua}var Za={};
function N(a){var b;if(!(b=Za[a])){b=0;for(var c=xa(String(Ta)).split("."),d=xa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"",n=RegExp("(\\d*)(\\D*)","g"),p=RegExp("(\\d*)(\\D*)","g");do{var r=n.exec(h)||["","",""],s=p.exec(k)||["","",""];if(0==r[0].length&&0==s[0].length)break;b=((0==r[1].length?0:parseInt(r[1],10))<(0==s[1].length?0:parseInt(s[1],10))?-1:(0==r[1].length?0:parseInt(r[1],10))>(0==s[1].length?0:parseInt(s[1],10))?1:0)||((0==r[2].length)<
(0==s[2].length)?-1:(0==r[2].length)>(0==s[2].length)?1:0)||(r[2]<s[2]?-1:r[2]>s[2]?1:0)}while(0==b)}b=Za[a]=0<=b}return b}function $a(a){return K&&ab>=a}var bb=u.document,ab=!bb||!K?j:Sa()||("CSS1Compat"==bb.compatMode?parseInt(Ta,10):5);function cb(a,b){for(var c in a)b.call(j,a[c],c,a)}function db(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function eb(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function fb(a,b){for(var c=ga(b),d=c?b:arguments,c=c?0:1;c<d.length&&!(a=a[d[c]],!v(a));c++);return a}function gb(){var a=hb,b;for(b in a)return q;return l}var ib="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
function jb(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<ib.length;f++)c=ib[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var kb=!K||$a(9),lb=!K||$a(9),mb=K&&!N("9");!M||N("528");L&&N("1.9b")||K&&N("8")||Pa&&N("9.5")||M&&N("528");L&&!N("8")||K&&N("9");function nb(a){Error.captureStackTrace?Error.captureStackTrace(this,nb):this.stack=Error().stack||"";a&&(this.message=String(a))}C(nb,Error);nb.prototype.name="CustomError";var O=Array.prototype,ob=O.indexOf?function(a,b,c){return O.indexOf.call(a,b,c)}:function(a,b,c){c=c==m?0:0>c?Math.max(0,a.length+c):c;if(x(a))return!x(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},P=O.forEach?function(a,b,c){O.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=x(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},pb=O.filter?function(a,b,c){return O.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=x(a)?a.split(""):
a,k=0;k<d;k++)if(k in h){var n=h[k];b.call(c,n,k,a)&&(e[f++]=n)}return e},qb=O.map?function(a,b,c){return O.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=x(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e},rb=O.some?function(a,b,c){return O.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=x(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return l;return q};function sb(a,b){var c=ob(a,b),d;(d=0<=c)&&O.splice.call(a,c,1);return d}
function tb(a){return O.concat.apply(O,arguments)}function ub(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function vb(a,b,c){return 2>=arguments.length?O.slice.call(a,b):O.slice.call(a,b,c)}function wb(a,b){return a>b?1:a<b?-1:0};function xb(a){xb[" "](a);return a}xb[" "]=da;function yb(a,b){a&&this.o(a,b)}C(yb,J);var zb=[1,4,2];t=yb.prototype;t.target=m;t.relatedTarget=m;t.offsetX=0;t.offsetY=0;t.clientX=0;t.clientY=0;t.screenX=0;t.screenY=0;t.button=0;t.keyCode=0;t.charCode=0;t.ctrlKey=q;t.altKey=q;t.shiftKey=q;t.metaKey=q;t.Af=q;t.N=m;
t.o=function(a,b){var c=this.type=a.type;J.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(L){var e;a:{try{xb(d.nodeName);e=l;break a}catch(f){}e=q}e||(d=m)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=M||a.offsetX!==j?a.offsetX:a.layerX;this.offsetY=M||a.offsetY!==j?a.offsetY:a.layerY;this.clientX=a.clientX!==j?a.clientX:a.pageX;this.clientY=a.clientY!==j?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Af=Ia?a.metaKey:a.ctrlKey;this.state=a.state;this.N=a;a.defaultPrevented&&this.preventDefault();delete this.Wa};
t.preventDefault=function(){yb.i.preventDefault.call(this);var a=this.N;if(a.preventDefault)a.preventDefault();else if(a.returnValue=q,mb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};t.ye=ba("N");t.d=function(){};var Ab={},R={},Bb={},Cb={};
function S(a,b,c,d,e){if(fa(b)){for(var f=0;f<b.length;f++)S(a,b[f],c,d,e);return m}a:{b||g(Error("Invalid event type"));d=!!d;var h=R;b in h||(h[b]={b:0,L:0});h=h[b];d in h||(h[d]={b:0,L:0},h.b++);var h=h[d],f=ja(a),k;h.L++;if(h[f]){k=h[f];for(var n=0;n<k.length;n++)if(h=k[n],h.Qa==c&&h.Eb==e){if(h.Ba)break;k[n].ub=q;a=k[n].key;break a}}else k=h[f]=[],h.b++;var p=Db,r=lb?function(a){return p.call(r.src,r.key,a)}:function(a){a=p.call(r.src,r.key,a);if(!a)return a},n=r;n.src=a;h=new va;h.o(c,n,a,b,
d,e);h.ub=q;c=h.key;n.key=c;k.push(h);Ab[c]=h;Bb[f]||(Bb[f]=[]);Bb[f].push(h);a.addEventListener?(a==u||!a.Uc)&&a.addEventListener(b,n,d):a.attachEvent(b in Cb?Cb[b]:Cb[b]="on"+b,n);a=c}return a}function Eb(a,b,c,d,e){if(fa(b))for(var f=0;f<b.length;f++)Eb(a,b[f],c,d,e);else if(d=!!d,a=Fb(a,b,d))for(f=0;f<a.length;f++)if(a[f].Qa==c&&a[f].capture==d&&a[f].Eb==e){T(a[f].key);break}}
function T(a){if(!Ab[a])return q;var b=Ab[a];if(b.Ba)return q;var c=b.src,d=b.type,e=b.Kd,f=b.capture;c.removeEventListener?(c==u||!c.Uc)&&c.removeEventListener(d,e,f):c.detachEvent&&c.detachEvent(d in Cb?Cb[d]:Cb[d]="on"+d,e);c=ja(c);Bb[c]&&(e=Bb[c],sb(e,b),0==e.length&&delete Bb[c]);b.Ba=l;if(b=R[d][f][c])b.zd=l,Gb(d,f,c,b);delete Ab[a];return l}
function Gb(a,b,c,d){if(!d.Mb&&d.zd){for(var e=0,f=0;e<d.length;e++)d[e].Ba?d[e].Kd.src=m:(e!=f&&(d[f]=d[e]),f++);d.length=f;d.zd=q;0==f&&(delete R[a][b][c],R[a][b].b--,0==R[a][b].b&&(delete R[a][b],R[a].b--),0==R[a].b&&delete R[a])}}function Fb(a,b,c){var d=R;return b in d&&(d=d[b],c in d&&(d=d[c],a=ja(a),d[a]))?d[a]:m}
function Hb(a,b,c,d,e){var f=1;b=ja(b);if(a[b]){a.L--;a=a[b];a.Mb?a.Mb++:a.Mb=1;try{for(var h=a.length,k=0;k<h;k++){var n=a[k];n&&!n.Ba&&(f&=Ib(n,e)!==q)}}finally{a.Mb--,Gb(c,d,b,a)}}return Boolean(f)}function Ib(a,b){a.ub&&T(a.key);return a.handleEvent(b)}
function Db(a,b){if(!Ab[a])return l;var c=Ab[a],d=c.type,e=R;if(!(d in e))return l;var e=e[d],f,h;if(!lb){var k;if(!(k=b))a:{k=["window","event"];for(var n=u;f=k.shift();)if(n[f]!=m)n=n[f];else{k=m;break a}k=n}f=k;k=l in e;n=q in e;if(k){if(0>f.keyCode||f.returnValue!=j)return l;a:{var p=q;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(r){p=l}if(p||f.returnValue==j)f.returnValue=l}}p=new yb;p.o(f,this);f=l;try{if(k){for(var s=[],z=p.currentTarget;z;z=z.parentNode)s.push(z);h=e[l];h.L=h.b;for(var G=
s.length-1;!p.Wa&&0<=G&&h.L;G--)p.currentTarget=s[G],f&=Hb(h,s[G],d,l,p);if(n){h=e[q];h.L=h.b;for(G=0;!p.Wa&&G<s.length&&h.L;G++)p.currentTarget=s[G],f&=Hb(h,s[G],d,q,p)}}else f=Ib(c,p)}finally{s&&(s.length=0)}return f}d=new yb(b,this);return f=Ib(c,d)}var Jb=0;function U(){I.call(this)}C(U,I);t=U.prototype;t.Uc=l;t.Qb=m;t.Jc=aa("Qb");t.addEventListener=function(a,b,c,d){S(this,a,b,c,d)};t.removeEventListener=function(a,b,c,d){Eb(this,a,b,c,d)};
t.dispatchEvent=function(a){var b=a.type||a,c=R;if(b in c){if(x(a))a=new J(a,this);else if(a instanceof J)a.target=a.target||this;else{var d=a;a=new J(b,this);jb(a,d)}var d=1,e,c=c[b],b=l in c,f;if(b){e=[];for(f=this;f;f=f.Qb)e.push(f);f=c[l];f.L=f.b;for(var h=e.length-1;!a.Wa&&0<=h&&f.L;h--)a.currentTarget=e[h],d&=Hb(f,e[h],a.type,l,a)&&a.Tb!=q}if(q in c)if(f=c[q],f.L=f.b,b)for(h=0;!a.Wa&&h<e.length&&f.L;h++)a.currentTarget=e[h],d&=Hb(f,e[h],a.type,q,a)&&a.Tb!=q;else for(e=this;!a.Wa&&e&&f.L;e=e.Qb)a.currentTarget=
e,d&=Hb(f,e,a.type,q,a)&&a.Tb!=q;a=Boolean(d)}else a=l;return a};t.d=function(){U.i.d.call(this);var a,b=0,c=a==m;a=!!a;if(this==m)cb(Bb,function(d){for(var e=d.length-1;0<=e;e--){var f=d[e];if(c||a==f.capture)T(f.key),b++}});else{var d=ja(this);if(Bb[d])for(var d=Bb[d],e=d.length-1;0<=e;e--){var f=d[e];if(c||a==f.capture)T(f.key),b++}}this.Qb=m};function Kb(a,b){I.call(this);this.C=a||1;this.pb=b||Lb;this.cc=y(this.Kf,this);this.yc=B()}C(Kb,U);Kb.prototype.enabled=q;var Lb=u.window;t=Kb.prototype;t.ea=m;t.setInterval=function(a){this.C=a;this.ea&&this.enabled?(this.stop(),this.start()):this.ea&&this.stop()};t.Kf=function(){if(this.enabled){var a=B()-this.yc;0<a&&a<0.8*this.C?this.ea=this.pb.setTimeout(this.cc,this.C-a):(this.dispatchEvent(Mb),this.enabled&&(this.ea=this.pb.setTimeout(this.cc,this.C),this.yc=B()))}};
t.start=function(){this.enabled=l;this.ea||(this.ea=this.pb.setTimeout(this.cc,this.C),this.yc=B())};t.stop=function(){this.enabled=q;this.ea&&(this.pb.clearTimeout(this.ea),this.ea=m)};t.d=function(){Kb.i.d.call(this);this.stop();delete this.pb};var Mb="tick";function Nb(a,b,c){I.call(this);this.Ra=a;this.C=b||0;this.la=c;this.de=y(this.me,this)}C(Nb,I);t=Nb.prototype;t.P=0;t.d=function(){Nb.i.d.call(this);this.stop();delete this.Ra;delete this.la};t.start=function(a){this.stop();var b=this.de;a=v(a)?a:this.C;ha(b)||(b&&"function"==typeof b.handleEvent?b=y(b.handleEvent,b):g(Error("Invalid listener argument")));this.P=2147483647<a?-1:Lb.setTimeout(b,a||0)};t.stop=function(){this.Fb()&&Lb.clearTimeout(this.P);this.P=0};t.Fb=function(){return 0!=this.P};
t.me=function(){this.P=0;this.Ra&&this.Ra.call(this.la)};function oa(a,b){I.call(this);this.Ra=a;this.la=b;this.Ia=new Nb(y(this.wf,this),0,this)}C(oa,I);t=oa.prototype;t.C=0;t.Gc=0;t.nd=q;t.d=function(){this.Ia.u();delete this.Ra;delete this.la;oa.i.d.call(this)};t.start=function(a,b){this.stop();this.nd=q;var c=b||0;this.C=Math.max(a||0,0);this.Gc=0>c?-1:B()+c;this.Ia.start(0>c?this.C:Math.min(this.C,c))};t.stop=function(){this.Ia.stop()};t.Fb=function(){return this.Ia.Fb()};t.Hd=function(){};
t.wf=function(){if(this.Ra.call(this.la))this.nd=l,this.Hd();else if(0>this.Gc)this.Ia.start(this.C);else{var a=this.Gc-B();0>=a||this.Ia.start(Math.min(this.C,a))}};var Ob;Ob=function(){return l};var Pb;function Qb(a){a=a.className;return x(a)&&a.match(/\S+/g)||[]}function Rb(a,b){for(var c=Qb(a),d=vb(arguments,1),e=c.length+d.length,f=c,h=0;h<d.length;h++)0<=ob(f,d[h])||f.push(d[h]);a.className=c.join(" ");return c.length==e}function Sb(a,b){var c=Qb(a),d=vb(arguments,1),c=pb(c,function(a){return!(0<=ob(d,a))});a.className=c.join(" ")};function Tb(a,b){this.width=a;this.height=b}t=Tb.prototype;t.clone=function(){return new Tb(this.width,this.height)};t.toString=function(){return"("+this.width+" x "+this.height+")"};t.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};t.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};t.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var Ub=!K||$a(9),Vb=!L&&!K||K&&$a(9)||L&&N("1.9.1"),Wb=K&&!N("9"),Xb=K||Pa||M;function Yb(a,b,c){return Math.min(Math.max(a,b),c)};function V(a,b){this.x=v(a)?a:0;this.y=v(b)?b:0}V.prototype.clone=function(){return new V(this.x,this.y)};V.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function W(a){return a?new Zb(X(a)):Pb||(Pb=new Zb)}function $b(a){return x(a)?document.getElementById(a):a}function ac(a,b,c){return bc(document,a,b,c)}function cc(a,b){var c=b||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):c.getElementsByClassName?c.getElementsByClassName(a):bc(document,"*",a,b)}function dc(a,b){var c=b||document,d=m;return(d=c.querySelectorAll&&c.querySelector?c.querySelector("."+a):cc(a,b)[0])||m}
function bc(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&0<=ob(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a}
function ec(a,b){cb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in fc?a.setAttribute(fc[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var fc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function gc(a){return hc(a||window)}
function hc(a){a=a.document;a=ic(a)?a.documentElement:a.body;return new Tb(a.clientWidth,a.clientHeight)}function jc(a){var b=a.document,c=0;if(b){a=hc(a).height;var c=b.body,d=b.documentElement;if(ic(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{var b=d.scrollHeight,e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}}return c}
function kc(a){var b=lc(a);a=a.parentWindow||a.defaultView;return new V(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)}function lc(a){return!M&&ic(a)?a.documentElement:a.body}function mc(a){return a?a.parentWindow||a.defaultView:window}
function nc(a,b){var c=b[0],d=b[1];if(!Ub&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',ya(d.name),'"');if(d.type){c.push(' type="',ya(d.type),'"');var e={};jb(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(x(d)?c.className=d:fa(d)?Rb.apply(m,[c].concat(d)):ec(c,d));2<b.length&&oc(a,c,b,2);return c}function oc(a,b,c,d){function e(c){c&&b.appendChild(x(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];ga(f)&&!pc(f)?P(qc(f)?ub(f):f,e):e(f)}}
function rc(a){return document.createElement(a)}function sc(a,b,c,d){for(var e=["<tr>"],f=0;f<c;f++)e.push(d?"<td>&nbsp;</td>":"<td></td>");e.push("</tr>");e=e.join("");c=["<table>"];for(f=0;f<b;f++)c.push(e);c.push("</table>");a=a.createElement("DIV");a.innerHTML=c.join("");return a.removeChild(a.firstChild)}
function tc(a,b){var c=a.createElement("div");K?(c.innerHTML="<br>"+b,c.removeChild(c.firstChild)):c.innerHTML=b;if(1==c.childNodes.length)return c.removeChild(c.firstChild);for(var d=a.createDocumentFragment();c.firstChild;)d.appendChild(c.firstChild);return d}function uc(){return ic(document)}function ic(a){return"CSS1Compat"==a.compatMode}
function vc(a){if(1!=a.nodeType)return q;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return q}return l}function wc(a,b){a.appendChild(b)}function xc(a,b){oc(X(a),a,arguments,1)}
function yc(a){for(var b;b=a.firstChild;)a.removeChild(b)}function zc(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)}function Ac(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)}function Bc(a,b,c){a.insertBefore(b,a.childNodes[c]||m)}function Cc(a){return a&&a.parentNode?a.parentNode.removeChild(a):m}function Dc(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)}
function Ec(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(q);for(;b=a.firstChild;)c.insertBefore(b,a);return Cc(a)}}function Fc(a){return Vb&&a.children!=j?a.children:pb(a.childNodes,function(a){return 1==a.nodeType})}function Gc(a){return a.firstElementChild!=j?a.firstElementChild:Hc(a.firstChild,l)}function Ic(a){return a.lastElementChild!=j?a.lastElementChild:Hc(a.lastChild,q)}
function Jc(a){return a.nextElementSibling!=j?a.nextElementSibling:Hc(a.nextSibling,l)}function Kc(a){return a.previousElementSibling!=j?a.previousElementSibling:Hc(a.previousSibling,q)}function Hc(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function Lc(a){if(!a)return m;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:m}
function Mc(a){if(!a)return m;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a}function pc(a){return ia(a)&&0<a.nodeType}function Nc(a){return ia(a)&&1==a.nodeType}function Oc(a){return ia(a)&&a.window==a}function Pc(a){if(Xb)return a.parentElement;a=a.parentNode;return Nc(a)?a:m}
function Qc(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function Rc(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(K&&!$a(9)){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?Sc(a,b):!c&&Qc(e,b)?-1*Tc(a,b):!d&&Qc(f,a)?Tc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=X(a);c=d.createRange();
c.selectNode(a);c.collapse(l);d=d.createRange();d.selectNode(b);d.collapse(l);return c.compareBoundaryPoints(u.Range.START_TO_END,d)}function Tc(a,b){var c=a.parentNode;if(c==b)return-1;for(var d=b;d.parentNode!=c;)d=d.parentNode;return Sc(d,a)}function Sc(a,b){for(var c=b;c=c.previousSibling;)if(c==a)return-1;return 1}
function Uc(a){var b,c=arguments.length;if(c){if(1==c)return arguments[0]}else return m;var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],h=arguments[b];h;)f.unshift(h),h=h.parentNode;d.push(f);e=Math.min(e,f.length)}f=m;for(b=0;b<e;b++){for(var h=d[0][b],k=1;k<c;k++)if(h!=d[k][b])return f;f=h}return f}function X(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function Vc(a){return a.contentDocument||a.contentWindow.document}
function Wc(a){return a.contentWindow||Vc(a).parentWindow||Vc(a).defaultView}function Xc(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else yc(a),a.appendChild(X(a).createTextNode(b))}function Yc(a){if("outerHTML"in a)return a.outerHTML;var b=X(a).createElement("div");b.appendChild(a.cloneNode(l));return b.innerHTML}function Zc(a,b){var c=[];return $c(a,b,c,l)?c[0]:j}
function ad(a,b){var c=[];$c(a,b,c,q);return c}function $c(a,b,c,d){if(a!=m)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||$c(a,b,c,d))return l;a=a.nextSibling}return q}var bd={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},cd={IMG:" ",BR:"\n"};function dd(a){var b=a.getAttributeNode("tabindex");return b&&b.specified?(a=a.tabIndex,"number"==typeof a&&0<=a&&32768>a):q}function ed(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))}
function fd(a){if(Wb&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];gd(a,b,l);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Wb||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function gd(a,b,c){if(!(a.nodeName in bd))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in cd)b.push(cd[a.nodeName]);else for(a=a.firstChild;a;)gd(a,b,c),a=a.nextSibling}function hd(a){return fd(a).length}function id(a,b){for(var c=b||X(a).body,d=[];a&&a!=c;){for(var e=a;e=e.previousSibling;)d.unshift(fd(e));a=a.parentNode}return d.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length}
function jd(a,b,c){a=[a];for(var d=0,e=m;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in bd))if(3==e.nodeType)var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," "),d=d+f.length;else if(e.nodeName in cd)d+=cd[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);ia(c)&&(c.Wh=e?e.nodeValue.length+b-d-1:0,c.Rh=e);return e}
function qc(a){if(a&&"number"==typeof a.length){if(ia(a))return"function"==typeof a.item||"string"==typeof a.item;if(ha(a))return"function"==typeof a.item}return q}function kd(a,b,c){if(!b&&!c)return m;var d=b?b.toUpperCase():m;return ld(a,function(a){var b;if(b=!d||a.nodeName==d)if(!(b=!c))a=Qb(a),b=0<=ob(a,c);return b},l)}function md(a,b){return kd(a,m,b)}function ld(a,b,c,d){c||(a=a.parentNode);c=d==m;for(var e=0;a&&(c||e<=d);){if(b(a))return a;a=a.parentNode;e++}return m}
function nd(a){try{return a&&a.activeElement}catch(b){}return m}function Zb(a){this.f=a||u.document||document}t=Zb.prototype;t.Db=W;t.kc=ba("f");t.c=function(a){return x(a)?this.f.getElementById(a):a};t.Ce=function(a,b,c){return bc(this.f,a,b,c)};t.mc=function(a,b){return cc(a,b||this.f)};t.lc=function(a,b){return dc(a,b||this.f)};t.Gf=ec;t.Se=function(a){return gc(a||this.pc())};t.Ae=function(){return jc(this.pc())};t.Ha=function(a,b,c){return nc(this.f,arguments)};t.createElement=function(a){return this.f.createElement(a)};
t.createTextNode=function(a){return this.f.createTextNode(a)};t.ie=function(a,b,c){return sc(this.f,a,b,!!c)};t.Ye=function(a){return tc(this.f,a)};t.ze=function(){return this.sc()?"CSS1Compat":"BackCompat"};t.sc=function(){return ic(this.f)};t.pc=function(){return this.f.parentWindow||this.f.defaultView};t.Be=function(){return lc(this.f)};t.Ma=function(){return kc(this.f)};t.ue=function(a){return nd(a||this.f)};t.appendChild=wc;t.append=xc;t.canHaveChildren=vc;t.Ld=yc;t.cf=zc;t.bf=Ac;t.af=Bc;
t.removeNode=Cc;t.Df=Dc;t.te=Ec;t.ad=Fc;t.De=Gc;t.Ge=Ic;t.He=Jc;t.Pe=Kc;t.Ie=Lc;t.Qe=Mc;t.gf=pc;t.isElement=Nc;t.lf=Oc;t.Oe=Pc;t.contains=Qc;t.ge=Rc;t.pe=Uc;t.Ne=X;t.Ee=Vc;t.Fe=Wc;t.Hf=Xc;t.Me=Yc;t.qe=Zc;t.re=ad;t.ff=dd;t.Ff=ed;t.Re=fd;t.Ke=hd;t.Le=id;t.Je=jd;t.hf=qc;t.xe=kd;t.we=md;t.ve=ld;/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

The "New" BSD License:

Copyright (c) 2005-2009, The Dojo Foundation
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
function od(a,b){var c=b||[];a&&c.push(a);return c}var pd=M&&"BackCompat"==document.compatMode,qd=document.firstChild.children?"children":"childNodes",rd=q;
function sd(a){function b(){0<=p&&(w.id=c(p,A).replace(/\\/g,""),p=-1);if(0<=r){var a=r==A?m:c(r,A);0>">~+".indexOf(a)?w.A=a:w.Pb=a;r=-1}0<=n&&(w.ba.push(c(n+1,A).replace(/\\/g,"")),n=-1)}function c(b,c){return xa(a.slice(b,c))}a=0<=">~+".indexOf(a.slice(-1))?a+" * ":a+" ";for(var d=[],e=-1,f=-1,h=-1,k=-1,n=-1,p=-1,r=-1,s="",z="",G,A=0,ag=a.length,w=m,Q=m;s=z,z=a.charAt(A),A<ag;A++)if("\\"!=s)if(w||(G=A,w={qa:m,Aa:[],sb:[],ba:[],A:m,Pb:m,id:m,oc:function(){return rd?this.yf:this.A}},r=A),0<=e)if("]"==
z){Q.attr?Q.zc=c(h||e+1,A):Q.attr=c(e+1,A);if((e=Q.zc)&&('"'==e.charAt(0)||"'"==e.charAt(0)))Q.zc=e.slice(1,-1);w.sb.push(Q);Q=m;e=h=-1}else"="==z&&(h=0<="|~^$*".indexOf(s)?s:"",Q.type=h+z,Q.attr=c(e+1,A-h.length),h=A+1);else 0<=f?")"==z&&(0<=k&&(Q.value=c(f+1,A)),k=f=-1):"#"==z?(b(),p=A+1):"."==z?(b(),n=A):":"==z?(b(),k=A):"["==z?(b(),e=A,Q={}):"("==z?(0<=k&&(Q={name:c(k+1,A),value:m},w.Aa.push(Q)),f=A):" "==z&&s!=z&&(b(),0<=k&&w.Aa.push({name:c(k+1,A)}),w.ud=w.Aa.length||w.sb.length||w.ba.length,
w.Uh=w.qa=c(G,A),w.yf=w.A=w.Pb?m:w.A||"*",w.A&&(w.A=w.A.toUpperCase()),d.length&&d[d.length-1].Pb&&(w.ld=d.pop(),w.qa=w.ld.qa+" "+w.qa),d.push(w),w=m);return d}function td(a,b){return!a?b:!b?a:function(){return a.apply(window,arguments)&&b.apply(window,arguments)}}function ud(a){return 1==a.nodeType}function vd(a,b){return!a?"":"class"==b?a.className||"":"for"==b?a.htmlFor||"":"style"==b?a.style.cssText||"":(rd?a.getAttribute(b):a.getAttribute(b,2))||""}
var wd={"*=":function(a,b){return function(c){return 0<=vd(c,a).indexOf(b)}},"^=":function(a,b){return function(c){return 0==vd(c,a).indexOf(b)}},"$=":function(a,b){return function(c){c=" "+vd(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return 0<=(" "+vd(b,a)+" ").indexOf(c)}},"|=":function(a,b){b=" "+b;return function(c){c=" "+vd(c,a);return c==b||0==c.indexOf(b+"-")}},"=":function(a,b){return function(c){return vd(c,a)==b}}},xd="undefined"==
typeof document.firstChild.nextElementSibling,yd=!xd?"nextElementSibling":"nextSibling",zd=!xd?"previousElementSibling":"previousSibling",Ad=xd?ud:Ob;function Bd(a){for(;a=a[zd];)if(Ad(a))return q;return l}function Cd(a){for(;a=a[yd];)if(Ad(a))return q;return l}function Dd(a){var b=a.parentNode,c=0,d=b[qd],e=a._i||-1,f=b._l||-1;if(!d)return-1;d=d.length;if(f==d&&0<=e&&0<=f)return e;b._l=d;e=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[yd])Ad(b)&&(b._i=++c,a===b&&(e=c));return e}
function Ed(a){return!(Dd(a)%2)}function Fd(a){return Dd(a)%2}
var Hd={checked:function(){return function(a){return a.checked||a.attributes.checked}},"first-child":function(){return Bd},"last-child":function(){return Cd},"only-child":function(){return function(a){return!Bd(a)||!Cd(a)?q:l}},empty:function(){return function(a){var b=a.childNodes;for(a=a.childNodes.length-1;0<=a;a--){var c=b[a].nodeType;if(1===c||3==c)return q}return l}},contains:function(a,b){var c=b.charAt(0);if('"'==c||"'"==c)b=b.slice(1,-1);return function(a){return 0<=a.innerHTML.indexOf(b)}},
not:function(a,b){var c=sd(b)[0],d={Ja:1};"*"!=c.A&&(d.A=1);c.ba.length||(d.ba=1);var e=Gd(c,d);return function(a){return!e(a)}},"nth-child":function(a,b){if("odd"==b)return Fd;if("even"==b)return Ed;if(-1!=b.indexOf("n")){var c=b.split("n",2),d=c[0]?"-"==c[0]?-1:parseInt(c[0],10):1,e=c[1]?parseInt(c[1],10):0,f=0,h=-1;0<d?0>e?e=e%d&&d+e%d:0<e&&(e>=d&&(f=e-e%d),e%=d):0>d&&(d*=-1,0<e&&(h=e,e%=d));if(0<d)return function(a){a=Dd(a);return a>=f&&(0>h||a<=h)&&a%d==e};b=e}var k=parseInt(b,10);return function(a){return Dd(a)==
k}}},Jd=K?function(a){var b=a.toLowerCase();"class"==b&&(a="className");return function(c){return rd?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}};
function Gd(a,b){if(!a)return Ob;b=b||{};var c=m;b.Ja||(c=td(c,ud));b.A||"*"!=a.A&&(c=td(c,function(b){return b&&b.tagName==a.oc()}));b.ba||P(a.ba,function(a,b){var f=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=td(c,function(a){return f.test(a.className)});c.count=b});b.Aa||P(a.Aa,function(a){var b=a.name;Hd[b]&&(c=td(c,Hd[b](b,a.value)))});b.sb||P(a.sb,function(a){var b,f=a.attr;a.type&&wd[a.type]?b=wd[a.type](f,a.zc):f.length&&(b=Jd(f));b&&(c=td(c,b))});b.id||a.id&&(c=td(c,function(b){return!!b&&b.id==
a.id}));c||"default"in b||(c=Ob);return c}var Kd={};
function Ld(a){var b=Kd[a.qa];if(b)return b;var c=a.ld,c=c?c.Pb:"",d=Gd(a,{Ja:1}),e="*"==a.A,f=document.getElementsByClassName;if(c)if(f={Ja:1},e&&(f.A=1),d=Gd(a,f),"+"==c)var h=d,b=function(a,b,c){for(;a=a[yd];)if(!xd||ud(a)){(!c||Md(a,c))&&h(a)&&b.push(a);break}return b};else if("~"==c)var k=d,b=function(a,b,c){for(a=a[yd];a;){if(Ad(a)){if(c&&!Md(a,c))break;k(a)&&b.push(a)}a=a[yd]}return b};else{if(">"==c)var n=d,n=n||Ob,b=function(a,b,c){for(var d=0,e=a[qd];a=e[d++];)Ad(a)&&((!c||Md(a,c))&&n(a,
d))&&b.push(a);return b}}else if(a.id)d=!a.ud&&e?Ob:Gd(a,{Ja:1,id:1}),b=function(b,c){var e=W(b).c(a.id),f;if(f=e&&d(e))if(!(f=9==b.nodeType)){for(f=e.parentNode;f&&f!=b;)f=f.parentNode;f=!!f}if(f)return od(e,c)};else if(f&&/\{\s*\[native code\]\s*\}/.test(String(f))&&a.ba.length&&!pd)var d=Gd(a,{Ja:1,ba:1,id:1}),p=a.ba.join(" "),b=function(a,b){for(var c=od(0,b),e,f=0,h=a.getElementsByClassName(p);e=h[f++];)d(e,a)&&c.push(e);return c};else!e&&!a.ud?b=function(b,c){for(var d=od(0,c),e,f=0,h=b.getElementsByTagName(a.oc());e=
h[f++];)d.push(e);return d}:(d=Gd(a,{Ja:1,A:1,id:1}),b=function(b,c){for(var e=od(0,c),f,h=0,k=b.getElementsByTagName(a.oc());f=k[h++];)d(f,b)&&e.push(f);return e});return Kd[a.qa]=b}var Nd={},Od={};function Pd(a){var b=sd(xa(a));if(1==b.length){var c=Ld(b[0]);return function(a){if(a=c(a,[]))a.Nb=l;return a}}return function(a){a=od(a);for(var c,f,h=b.length,k,n,p=0;p<h;p++){n=[];c=b[p];f=a.length-1;0<f&&(k={},n.Nb=l);f=Ld(c);for(var r=0;c=a[r];r++)f(c,n,k);if(!n.length)break;a=n}return n}}
var Qd=!!document.querySelectorAll&&(!M||N("526"));
function Rd(a,b){if(Qd){var c=Od[a];if(c&&!b)return c}if(c=Nd[a])return c;var c=a.charAt(0),d=-1==a.indexOf(" ");0<=a.indexOf("#")&&d&&(b=l);if(Qd&&!b&&-1==">~+".indexOf(c)&&(!K||-1==a.indexOf(":"))&&!(pd&&0<=a.indexOf("."))&&-1==a.indexOf(":contains")&&-1==a.indexOf("|=")){var e=0<=">~+".indexOf(a.charAt(a.length-1))?a+" *":a;return Od[a]=function(b){try{9==b.nodeType||d||g("");var c=b.querySelectorAll(e);K?c.fe=l:c.Nb=l;return c}catch(f){return Rd(a,l)(b)}}}var f=a.split(/\s*,\s*/);return Nd[a]=
2>f.length?Pd(a):function(a){for(var b=0,c=[],d;d=f[b++];)c=c.concat(Pd(d)(a));return c}}var Sd=0,Td=K?function(a){return rd?a.getAttribute("_uid")||a.setAttribute("_uid",++Sd)||Sd:a.uniqueID}:function(a){return a._uid||(a._uid=++Sd)};function Md(a,b){if(!b)return 1;var c=Td(a);return!b[c]?b[c]=1:0}
function Ud(a){if(a&&a.Nb)return a;var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(2>a.length)return b;Sd++;if(K&&rd){var c=Sd+"";a[0].setAttribute("_zipIdx",c);for(var d=1,e;e=a[d];d++)a[d].getAttribute("_zipIdx")!=c&&b.push(e),e.setAttribute("_zipIdx",c)}else if(K&&a.fe)try{for(d=1;e=a[d];d++)ud(e)&&b.push(e)}catch(f){}else{a[0]&&(a[0]._zipIdx=Sd);for(d=1;e=a[d];d++)a[d]._zipIdx!=Sd&&b.push(e),e._zipIdx=Sd}return b}
function Vd(a,b){if(!a)return[];if(a.constructor==Array)return a;if(!x(a))return[a];if(x(b)&&(b=$b(b),!b))return[];b=b||document;var c=b.ownerDocument||b.documentElement;rd=b.contentType&&"application/xml"==b.contentType||Pa&&(b.doctype||"[object XMLDocument]"==c.toString())||!!c&&(K?c.xml:b.xmlVersion||c.xmlVersion);return(c=Rd(a)(b))&&c.Nb?c:Ud(c)}Vd.Aa=Hd;ca("goog.dom.query",Vd);ca("goog.dom.query.pseudos",Vd.Aa);function Wd(){};function Xd(){this.sa=[];this.total=this.Oa=0;for(var a=[],b=0;64>b;b++)a[b]=0;this.Bc=a;this.Bc[0]=128;this.hash=[];this.Cd=0;this.reset()}C(Xd,Wd);
function Yd(a,b){for(var c=[],d=0,e=0;e<b.length;)c[d++]=b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3],e=4*d;for(d=16;64>d;d++)c[d]=c[d-16]+((c[d-15]>>>7|c[d-15]<<25)^(c[d-15]>>>18|c[d-15]<<14)^c[d-15]>>>3)+c[d-7]+((c[d-2]>>>17|c[d-2]<<15)^(c[d-2]>>>19|c[d-2]<<13)^c[d-2]>>>10)&4294967295;for(var e=a.hash[0],f=a.hash[1],h=a.hash[2],k=a.hash[3],n=a.hash[4],p=a.hash[5],r=a.hash[6],s=a.hash[7],d=0;64>d;d++)var z=((e>>>2|e<<30)^(e>>>13|e<<19)^(e>>>22|e<<10))+(e&f^e&h^f&h)&4294967295,G=s+((n>>>6|n<<26)^(n>>>11|
n<<21)^(n>>>25|n<<7))+(n&p^~n&r)+a.Xd[d]+c[d]&4294967295,s=r,r=p,p=n,n=k+G&4294967295,k=h,h=f,f=e,e=G+z&4294967295;a.hash[0]=a.hash[0]+e&4294967295;a.hash[1]=a.hash[1]+f&4294967295;a.hash[2]=a.hash[2]+h&4294967295;a.hash[3]=a.hash[3]+k&4294967295;a.hash[4]=a.hash[4]+n&4294967295;a.hash[5]=a.hash[5]+p&4294967295;a.hash[6]=a.hash[6]+r&4294967295;a.hash[7]=a.hash[7]+s&4294967295}
Xd.prototype.update=function(a,b){v(b)||(b=a.length);var c=0,d=this.Oa;if(x(a))for(;c<b;)this.sa[d++]=a.charCodeAt(c++),64==d&&(Yd(this,this.sa),d=0);else for(;c<b;)this.sa[d++]=a[c++],64==d&&(Yd(this,this.sa),d=0);this.Oa=d;this.total+=b};
Xd.prototype.ab=function(){var a=[],b=8*this.total;56>this.Oa?this.update(this.Bc,56-this.Oa):this.update(this.Bc,64-(this.Oa-56));for(var c=63;56<=c;c--)this.sa[c]=b&255,b/=256;Yd(this,this.sa);for(c=b=0;c<this.Cd;c++)for(var d=24;0<=d;d-=8)a[b++]=this.hash[c]>>d&255;return a};
Xd.prototype.Xd=[1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,
3600352804,4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298];function Zd(){Xd.call(this)}C(Zd,Xd);Zd.prototype.reset=function(){this.sa=[];this.total=this.Oa=0;this.hash=[1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225];this.Cd=8};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function $d(a,b){this.Ub=[];this.Ed=a;this.Vc=b||m}t=$d.prototype;t.ya=q;t.fb=q;t.bc=q;t.be=q;t.Kc=q;t.dc=0;t.cancel=function(a){if(this.ya)this.lb instanceof $d&&this.lb.cancel();else{if(this.$){var b=this.$;delete this.$;a?b.cancel(a):(b.dc--,0>=b.dc&&b.cancel())}this.Ed?this.Ed.call(this.Vc,this):this.Kc=l;this.ya||this.La(new ae(this))}};t.Tc=function(a,b){this.bc=q;be(this,a,b)};function be(a,b,c){a.ya=l;a.lb=c;a.fb=!b;ce(a)}function de(a){a.ya&&(a.Kc||g(new ee(a)),a.Kc=q)}
t.V=function(a){de(this);be(this,l,a)};t.La=function(a){de(this);be(this,q,a)};function fe(a,b,c,d){a.Ub.push([b,c,d]);a.ya&&ce(a)}function ge(a){return rb(a.Ub,function(a){return ha(a[1])})}
function ce(a){a.Oc&&(a.ya&&ge(a))&&(u.clearTimeout(a.Oc),delete a.Oc);a.$&&(a.$.dc--,delete a.$);for(var b=a.lb,c=q,d=q;a.Ub.length&&!a.bc;){var e=a.Ub.shift(),f=e[0],h=e[1],e=e[2];if(f=a.fb?h:f)try{var k=f.call(e||a.Vc,b);v(k)&&(a.fb=a.fb&&(k==b||k instanceof Error),a.lb=b=k);b instanceof $d&&(d=l,a.bc=l)}catch(n){b=n,a.fb=l,ge(a)||(c=l)}}a.lb=b;d&&(fe(b,y(a.Tc,a,l),y(a.Tc,a,q)),b.be=l);c&&(a.Oc=u.setTimeout(function(){g(b)},0))}function ee(a){nb.call(this);this.ke=a}C(ee,nb);
ee.prototype.message="Deferred has already fired";ee.prototype.name="AlreadyCalledError";function ae(a){nb.call(this);this.ke=a}C(ae,nb);ae.prototype.message="Deferred was cancelled";ae.prototype.name="CancelledError";function he(a,b,c,d,e,f){$d.call(this,e,f);this.rd=a;this.fc=[];this.Yc=!!b;this.se=!!c;this.he=!!d;for(b=0;b<a.length;b++)fe(a[b],y(this.ed,this,b,l),y(this.ed,this,b,q));0==a.length&&!this.Yc&&this.V(this.fc)}C(he,$d);he.prototype.Bd=0;he.prototype.ed=function(a,b,c){this.Bd++;this.fc[a]=[b,c];this.ya||(this.Yc&&b?this.V([a,c]):this.se&&!b?this.La(c):this.Bd==this.rd.length&&this.V(this.fc));this.he&&!b&&(c=m);return c};he.prototype.La=function(a){he.i.La.call(this,a);P(this.rd,function(a){a.cancel()})};function ie(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}ie.prototype.clone=function(){return new ie(this.top,this.right,this.bottom,this.left)};ie.prototype.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};ie.prototype.contains=function(a){return!this||!a?q:a instanceof ie?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom};function ke(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}ke.prototype.clone=function(){return new ke(this.left,this.top,this.width,this.height)};ke.prototype.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};
ke.prototype.contains=function(a){return a instanceof ke?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};function le(a,b){var c=X(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,m))?c[b]||c.getPropertyValue(b)||"":""}function me(a,b){return le(a,b)||(a.currentStyle?a.currentStyle[b]:m)||a.style&&a.style[b]}function ne(a){var b=a.getBoundingClientRect();K&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function oe(a){if(K&&!$a(8))return a.offsetParent;var b=X(a),c=me(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=me(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return m}
function pe(a){var b=new V;if(1==a.nodeType){if(a.getBoundingClientRect){var c=ne(a);b.x=c.left;b.y=c.top}else{c=W(a).Ma();var d,e=X(a),f=me(a,"position"),h=L&&e.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==f&&(d=e.getBoxObjectFor(a))&&(0>d.screenX||0>d.screenY),k=new V(0,0),n;d=e?X(e):document;n=K&&!$a(9)&&!W(d).sc()?d.body:d.documentElement;if(a!=n)if(a.getBoundingClientRect)d=ne(a),e=W(e).Ma(),k.x=d.left+e.x,k.y=d.top+e.y;else if(e.getBoxObjectFor&&!h)d=e.getBoxObjectFor(a),e=e.getBoxObjectFor(n),
k.x=d.screenX-e.screenX,k.y=d.screenY-e.screenY;else{d=a;do{k.x+=d.offsetLeft;k.y+=d.offsetTop;d!=a&&(k.x+=d.clientLeft||0,k.y+=d.clientTop||0);if(M&&"fixed"==me(d,"position")){k.x+=e.body.scrollLeft;k.y+=e.body.scrollTop;break}d=d.offsetParent}while(d&&d!=a);if(Pa||M&&"absolute"==f)k.y-=e.body.offsetTop;for(d=a;(d=oe(d))&&d!=e.body&&d!=n;)if(k.x-=d.scrollLeft,!Pa||"TR"!=d.tagName)k.y-=d.scrollTop}b.x=k.x-c.x;b.y=k.y-c.y}if(L&&!N(12)){var p;K?p="-ms-transform":M?p="-webkit-transform":Pa?p="-o-transform":
L&&(p="-moz-transform");var r;p&&(r=me(a,p));r||(r=me(a,"transform"));r?(a=r.match(qe),a=!a?new V(0,0):new V(parseFloat(a[1]),parseFloat(a[2]))):a=new V(0,0);b=new V(b.x+a.x,b.y+a.y)}}else p=ha(a.ye),r=a,a.targetTouches?r=a.targetTouches[0]:p&&a.N.targetTouches&&(r=a.N.targetTouches[0]),b.x=r.clientX,b.y=r.clientY;return b}function re(a){return"rtl"==me(a,"direction")}var se={thin:2,medium:4,thick:6};
function te(a,b){if("none"==(a.currentStyle?a.currentStyle[b+"Style"]:m))return 0;var c=a.currentStyle?a.currentStyle[b+"Width"]:m,d;if(c in se)d=se[c];else if(/^\d+px?$/.test(c))d=parseInt(c,10);else{d=a.style.left;var e=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=c;c=a.style.pixelLeft;a.style.left=d;a.runtimeStyle.left=e;d=c}return d}
function ue(a){if(K){var b=te(a,"borderLeft"),c=te(a,"borderRight"),d=te(a,"borderTop");a=te(a,"borderBottom");return new ie(d,c,a,b)}b=le(a,"borderLeftWidth");c=le(a,"borderRightWidth");d=le(a,"borderTopWidth");a=le(a,"borderBottomWidth");return new ie(parseFloat(d),parseFloat(c),parseFloat(a),parseFloat(b))}var qe=/matrix\([0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, ([0-9\.\-]+)p?x?, ([0-9\.\-]+)p?x?\)/;function ve(a){I.call(this);this.la=a;this.l=[]}C(ve,I);var we=[];function Y(a,b,c,d,e){fa(c)||(we[0]=c,c=we);for(var f=0;f<c.length;f++){var h=S(b,c[f],d||a,e||q,a.la||a);a.l.push(h)}return a}function xe(a,b,c,d,e,f){if(fa(c))for(var h=0;h<c.length;h++)xe(a,b,c[h],d,e,f);else{a:{d=d||a;f=f||a.la||a;e=!!e;if(b=Fb(b,c,e))for(c=0;c<b.length;c++)if(!b[c].Ba&&b[c].Qa==d&&b[c].capture==e&&b[c].Eb==f){b=b[c];break a}b=m}b&&(b=b.key,T(b),sb(a.l,b))}return a}function ye(a){P(a.l,T);a.l.length=0}
ve.prototype.d=function(){ve.i.d.call(this);ye(this)};ve.prototype.handleEvent=function(){g(Error("EventHandler.handleEvent not implemented"))};function ze(){}ze.bd=function(){return ze.md?ze.md:ze.md=new ze};ze.prototype.uf=0;ze.bd();function Ae(a){I.call(this);this.ga=a||W();this.aa=Be}C(Ae,U);Ae.prototype.Ze=ze.bd();var Be=m;t=Ae.prototype;t.P=m;t.ma=q;t.g=m;t.aa=m;t.rf=m;t.$=m;t.fa=m;t.vb=m;t.Vd=q;t.c=ba("g");t.mc=function(a){return this.g?this.ga.mc(a,this.g):[]};t.lc=function(a){return this.g?this.ga.lc(a,this.g):m};t.ka=function(){return this.Na||(this.Na=new ve(this))};t.Jc=function(a){this.$&&this.$!=a&&g(Error("Method not supported"));Ae.i.Jc.call(this,a)};t.Db=ba("ga");t.Ha=function(){this.g=this.ga.createElement("div")};
function Ce(a,b){a.ma&&g(Error("Component already rendered"));if(b&&a.Sc(b)){a.Vd=l;if(!a.ga||a.ga.kc()!=X(b))a.ga=W(b);a.zb(b);a.Ka()}else g(Error("Invalid element to decorate"))}t.Sc=function(){return l};t.zb=aa("g");t.Ka=function(){this.ma=l;De(this,function(a){!a.ma&&a.c()&&a.Ka()})};t.eb=function(){De(this,function(a){a.ma&&a.eb()});this.Na&&ye(this.Na);this.ma=q};
t.d=function(){Ae.i.d.call(this);this.ma&&this.eb();this.Na&&(this.Na.u(),delete this.Na);De(this,function(a){a.u()});!this.Vd&&this.g&&Cc(this.g);this.$=this.rf=this.g=this.vb=this.fa=m};t.Pa=function(){this.aa==m&&(this.aa=re(this.ma?this.g:this.ga.kc().body));return this.aa};function De(a,b){a.fa&&P(a.fa,b,j)}
t.removeChild=function(a,b){if(a){var c=x(a)?a:a.P||(a.P=":"+(a.Ze.uf++).toString(36)),d;this.vb&&c?(d=this.vb,d=(c in d?d[c]:j)||m):d=m;a=d;c&&a&&(d=this.vb,c in d&&delete d[c],sb(this.fa,a),b&&(a.eb(),a.g&&Cc(a.g)),c=a,c==m&&g(Error("Unable to set parent component")),c.$=m,Ae.i.Jc.call(c,m))}a||g(Error("Child is not in parent component"));return a};t.Ld=function(a){for(var b=[];this.fa&&0!=this.fa.length;)b.push(this.removeChild(this.fa?this.fa[0]||m:m,a));return b};function Ee(a){Ae.call(this,a);this.wb=-1;this.mb=q;this.Wc=Fe;this.If=[]}C(Ee,Ae);t=Ee.prototype;t.Nd=0;t.Sc=function(a){return"TABLE"==a.tagName};t.Ka=function(){Ee.i.Ka.call(this);var a=this.c().tHead.rows[this.Nd];Y(this.ka(),a,"click",this.Jf)};t.Jf=function(a){a=kd(a.target,"TH").cellIndex;var b=a==this.wb?!this.mb:q;this.dispatchEvent("beforesort")&&this.sort(a,b)&&this.dispatchEvent("sort")};
t.sort=function(a,b){var c=this.If[a]||this.Wc;if(c===Ge)return q;var d=this.c(),e=d.tBodies[0],f=e.rows,h=d.tHead.rows[this.Nd].cells;0<=this.wb&&Sb(h[this.wb],this.mb?"goog-tablesorter-sorted-reverse":"goog-tablesorter-sorted");this.mb=!!b;for(var h=h[a],k=[],n=0,p=f.length;n<p;n++){var r=f[n],s=fd(r.cells[a]);k.push([s,r])}for(var z=this.mb?-1:1,f=0;f<k.length;f++)k[f]={index:f,value:k[f]};var G=function(a,b){return c(a[0],b[0])*z}||wb;O.sort.call(k,function(a,b){return G(a.value,b.value)||a.index-
b.index}||wb);for(f=0;f<k.length;f++)k[f]=k[f].value;d.removeChild(e);for(n=0;n<p;n++)e.appendChild(k[n][1]);d.insertBefore(e,d.tBodies[0]||m);this.wb=a;Rb(h,this.mb?"goog-tablesorter-sorted-reverse":"goog-tablesorter-sorted");return l};var Ge;Ge=function(){g(Error("no sort"))};function Fe(a,b){return parseFloat(a)-parseFloat(b)};function He(a,b,c,d,e){if(!K&&(!M||!N("525")))return l;if(Ia&&e)return Ie(a);if(e&&!d||!c&&(17==b||18==b||Ia&&91==b))return q;if(M&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return q}if(K&&d&&b==a)return q;switch(a){case 13:return!(K&&$a(9));case 27:return!M}return Ie(a)}
function Ie(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||M&&0==a)return l;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return l;default:return q}}function Je(a){switch(a){case 61:return 187;case 59:return 186;case 224:return 91;case 0:return 224;default:return a}};function Ke(a,b){I.call(this);a&&(this.Jb&&this.detach(),this.g=a,this.Ib=S(this.g,"keypress",this,b),this.uc=S(this.g,"keydown",this.rc,b,this),this.Jb=S(this.g,"keyup",this.Te,b,this))}C(Ke,U);t=Ke.prototype;t.g=m;t.Ib=m;t.uc=m;t.Jb=m;t.D=-1;t.oa=-1;t.ac=q;
var Le={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},Me={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},Ne=K||M&&N("525"),Oe=Ia&&L;t=Ke.prototype;
t.rc=function(a){if(M&&(17==this.D&&!a.ctrlKey||18==this.D&&!a.altKey||Ia&&91==this.D&&!a.metaKey))this.oa=this.D=-1;-1==this.D&&(a.ctrlKey&&17!=a.keyCode?this.D=17:a.altKey&&18!=a.keyCode?this.D=18:a.metaKey&&91!=a.keyCode&&(this.D=91));Ne&&!He(a.keyCode,this.D,a.shiftKey,a.ctrlKey,a.altKey)?this.handleEvent(a):(this.oa=L?Je(a.keyCode):a.keyCode,Oe&&(this.ac=a.altKey))};t.Te=function(a){this.oa=this.D=-1;this.ac=a.altKey};
t.handleEvent=function(a){var b=a.N,c,d,e=b.altKey;K&&"keypress"==a.type?(c=this.oa,d=13!=c&&27!=c?b.keyCode:0):M&&"keypress"==a.type?(c=this.oa,d=0<=b.charCode&&63232>b.charCode&&Ie(c)?b.charCode:0):Pa?(c=this.oa,d=Ie(c)?b.keyCode:0):(c=b.keyCode||this.oa,d=b.charCode||0,Oe&&(e=this.ac),Ia&&(63==d&&224==c)&&(c=191));var f=c,h=b.keyIdentifier;c?63232<=c&&c in Le?f=Le[c]:25==c&&a.shiftKey&&(f=9):h&&h in Me&&(f=Me[h]);a=f==this.D;this.D=f;b=new Pe(f,d,a,b);b.altKey=e;this.dispatchEvent(b)};t.c=ba("g");
t.detach=function(){this.Ib&&(T(this.Ib),T(this.uc),T(this.Jb),this.Jb=this.uc=this.Ib=m);this.g=m;this.oa=this.D=-1};t.d=function(){Ke.i.d.call(this);this.detach()};function Pe(a,b,c,d){d&&this.o(d,j);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}C(Pe,yb);function Qe(a){var b=a.offsetLeft,c=a.offsetParent;!c&&"fixed"==me(a,"position")&&(c=X(a).documentElement);if(!c)return b;if(L)var d=ue(c),b=b+d.left;else $a(8)&&(d=ue(c),b-=d.left);return re(c)?c.clientWidth-(b+a.offsetWidth):b};function Re(a,b,c){I.call(this);this.target=a;this.handle=b||a;this.qd=c||new ke(NaN,NaN,NaN,NaN);this.f=X(a);this.W=new ve(this);S(this.handle,["touchstart","mousedown"],this.Od,q,this)}C(Re,U);var Se=K||L&&N("1.9.3");t=Re.prototype;t.clientX=0;t.clientY=0;t.screenX=0;t.screenY=0;t.Pd=0;t.Qd=0;t.va=0;t.wa=0;t.ic=l;t.xa=q;t.jd=0;t.sf=0;t.$e=q;t.Da=q;t.ha=aa("Da");t.ka=ba("W");
t.d=function(){Re.i.d.call(this);Eb(this.handle,["touchstart","mousedown"],this.Od,q,this);ye(this.W);Se&&this.f.releaseCapture();this.W=this.handle=this.target=m};function Te(a){v(a.aa)||(a.aa=re(a.target));return a.aa}
t.Od=function(a){var b="mousedown"==a.type;if(this.ic&&!this.xa&&(!b||(kb?0==a.N.button:"click"==a.type||a.N.button&zb[0])&&(!M||!Ia||!a.ctrlKey))){Ue(a);if(0==this.jd)if(this.dispatchEvent(new Ve("start",this,a.clientX,a.clientY,a)))this.xa=l,a.preventDefault();else return;else a.preventDefault();var b=this.f,c=b.documentElement,d=!Se;Y(this.W,b,["touchmove","mousemove"],this.We,d);Y(this.W,b,["touchend","mouseup"],this.Ab,d);Se?(c.setCapture(q),Y(this.W,c,"losecapture",this.Ab)):Y(this.W,mc(b),
"blur",this.Ab);K&&this.$e&&Y(this.W,b,"dragstart",ua);this.Ef&&Y(this.W,this.Ef,"scroll",this.vf,d);this.clientX=this.Pd=a.clientX;this.clientY=this.Qd=a.clientY;this.screenX=a.screenX;this.screenY=a.screenY;this.va=this.Da?Qe(this.target):this.target.offsetLeft;this.wa=this.target.offsetTop;this.Cc=W(this.f).Ma();this.sf=B()}else this.dispatchEvent("earlycancel")};
t.Ab=function(a,b){ye(this.W);Se&&this.f.releaseCapture();if(this.xa){Ue(a);this.xa=q;var c=We(this,this.va),d=Xe(this,this.wa);this.dispatchEvent(new Ve("end",this,a.clientX,a.clientY,a,c,d,b||"touchcancel"==a.type))}else this.dispatchEvent("earlycancel");("touchend"==a.type||"touchcancel"==a.type)&&a.preventDefault()};
function Ue(a){var b=a.type;"touchstart"==b||"touchmove"==b?a.o(a.N.targetTouches[0],a.currentTarget):("touchend"==b||"touchcancel"==b)&&a.o(a.N.changedTouches[0],a.currentTarget)}
t.We=function(a){if(this.ic){Ue(a);var b=(this.Da&&Te(this)?-1:1)*(a.clientX-this.clientX),c=a.clientY-this.clientY;this.clientX=a.clientX;this.clientY=a.clientY;this.screenX=a.screenX;this.screenY=a.screenY;if(!this.xa){var d=this.Pd-this.clientX,e=this.Qd-this.clientY;if(d*d+e*e>this.jd)if(this.dispatchEvent(new Ve("start",this,a.clientX,a.clientY,a)))this.xa=l;else{this.gc||this.Ab(a);return}}c=Ye(this,b,c);b=c.x;c=c.y;this.xa&&this.dispatchEvent(new Ve("beforedrag",this,a.clientX,a.clientY,a,
b,c))&&(Ze(this,a,b,c),a.preventDefault())}};function Ye(a,b,c){var d=W(a.f).Ma();b+=d.x-a.Cc.x;c+=d.y-a.Cc.y;a.Cc=d;a.va+=b;a.wa+=c;b=We(a,a.va);a=Xe(a,a.wa);return new V(b,a)}t.vf=function(a){var b=Ye(this,0,0);a.clientX=this.clientX;a.clientY=this.clientY;Ze(this,a,b.x,b.y)};function Ze(a,b,c,d){a.ec(c,d);a.dispatchEvent(new Ve("drag",a,b.clientX,b.clientY,b,c,d))}
function We(a,b){var c=a.qd,d=!isNaN(c.left)?c.left:m,c=!isNaN(c.width)?c.width:0;return Math.min(d!=m?d+c:Infinity,Math.max(d!=m?d:-Infinity,b))}function Xe(a,b){var c=a.qd,d=!isNaN(c.top)?c.top:m,c=!isNaN(c.height)?c.height:0;return Math.min(d!=m?d+c:Infinity,Math.max(d!=m?d:-Infinity,b))}t.ec=function(a,b){this.Da&&Te(this)?this.target.style.right=a+"px":this.target.style.left=a+"px";this.target.style.top=b+"px"};
function Ve(a,b,c,d,e,f,h,k){J.call(this,a);this.clientX=c;this.clientY=d;this.Bh=e;this.left=v(f)?f:b.va;this.top=v(h)?h:b.wa;this.hc=b;this.Gh=!!k}C(Ve,J);var hb={},$e=m;function af(a){a=ja(a);delete hb[a];gb()&&$e&&$e.stop()}function bf(){$e||($e=new Nb(function(){var a=B();cb(hb,function(c){cf(c,a)});gb()||bf()},20));var a=$e;a.Fb()||a.start()};function df(){I.call(this);this.q=ef;this.cb=this.startTime=m}C(df,U);var ef=0;df.prototype.m=function(){return 1==this.q};df.prototype.Ob=function(){this.B("begin")};df.prototype.Ua=function(){this.B("end")};df.prototype.B=function(a){this.dispatchEvent(a)};function ff(a,b,c,d){df.call(this);(!fa(a)||!fa(b))&&g(Error("Start and end parameters must be arrays"));a.length!=b.length&&g(Error("Start and end points must be the same length"));this.ob=a;this.oe=b;this.duration=c;this.Qc=d;this.coords=[];this.Da=q}C(ff,df);t=ff.prototype;t.ha=aa("Da");t.$c=0;t.K=0;t.wc=m;
t.play=function(a){if(a||this.q==ef)this.K=0,this.coords=this.ob;else if(this.m())return q;af(this);this.startTime=a=B();-1==this.q&&(this.startTime-=this.duration*this.K);this.cb=this.startTime+this.duration;this.wc=this.startTime;this.K||this.Ob();this.B("play");-1==this.q&&this.B("resume");this.q=1;var b=ja(this);b in hb||(hb[b]=this);bf();cf(this,a);return l};t.stop=function(a){af(this);this.q=ef;a&&(this.K=1);gf(this,this.K);this.B("stop");this.Ua()};
t.d=function(){this.q==ef||this.stop(q);this.B("destroy");ff.i.d.call(this)};function cf(a,b){a.K=(b-a.startTime)/(a.cb-a.startTime);1<=a.K&&(a.K=1);a.$c=1E3/(b-a.wc);a.wc=b;gf(a,a.K);1==a.K?(a.q=ef,af(a),a.B("finish"),a.Ua()):a.m()&&a.Ac()}function gf(a,b){ha(a.Qc)&&(b=a.Qc(b));a.coords=Array(a.ob.length);for(var c=0;c<a.ob.length;c++)a.coords[c]=(a.oe[c]-a.ob[c])*b+a.ob[c]}t.Ac=function(){this.B("animate")};t.B=function(a){this.dispatchEvent(new hf(a,this))};
function hf(a,b){J.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.bi=b.coords[2];this.duration=b.duration;this.K=b.K;this.Kh=b.$c;this.state=b.q;this.yh=b}C(hf,J);function Z(a,b,c,d,e){ff.call(this,b,c,d,e);this.element=a}C(Z,ff);t=Z.prototype;t.Za=da;t.Pa=function(){v(this.aa)||(this.aa=re(this.element));return this.aa};t.Ac=function(){this.Za();Z.i.Ac.call(this)};t.Ua=function(){this.Za();Z.i.Ua.call(this)};t.Ob=function(){this.Za();Z.i.Ob.call(this)};function jf(a,b,c,d,e){(2!=b.length||2!=c.length)&&g(Error("Start and end points must be 2D"));Z.apply(this,arguments)}C(jf,Z);
jf.prototype.Za=function(){var a=this.Da&&this.Pa()?"right":"left";this.element.style[a]=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};function kf(a,b,c,d,e){Z.call(this,a,[b],[c],d,e)}C(kf,Z);kf.prototype.Za=function(){this.element.style.width=Math.round(this.coords[0])+"px"};function lf(a,b,c,d,e){Z.call(this,a,[b],[c],d,e)}C(lf,Z);lf.prototype.Za=function(){this.element.style.height=Math.round(this.coords[0])+"px"};function nf(){df.call(this);this.da=[]}C(nf,df);nf.prototype.add=function(a){0<=ob(this.da,a)||(this.da.push(a),S(a,"finish",this.Dd,q,this))};nf.prototype.remove=function(a){sb(this.da,a)&&Eb(a,"finish",this.Dd,q,this)};nf.prototype.d=function(){P(this.da,function(a){a.u()});this.da.length=0;nf.i.d.call(this)};function of(){nf.call(this);this.jc=0}C(of,nf);
of.prototype.play=function(a){if(0==this.da.length)return q;if(a||this.q==ef)this.jc=0,this.Ob();else if(this.m())return q;this.B("play");-1==this.q&&this.B("resume");var b=-1==this.q&&!a;this.startTime=B();this.cb=m;this.q=1;P(this.da,function(c){(!b||-1==c.q)&&c.play(a)});return l};of.prototype.stop=function(a){P(this.da,function(b){b.q==ef||b.stop(a)});this.q=ef;this.cb=B();this.B("stop");this.Ua()};
of.prototype.Dd=function(){this.jc++;this.jc==this.da.length&&(this.cb=B(),this.q=ef,this.B("finish"),this.Ua())};var pf={Nf:"activedescendant",Sf:"atomic",Tf:"autocomplete",Vf:"busy",Xf:"checked",ag:"controls",bg:"describedby",eg:"disabled",gg:"dropeffect",hg:"expanded",ig:"flowto",kg:"grabbed",og:"haspopup",qg:"hidden",sg:"invalid",tg:"label",ug:"labelledby",vg:"level",Ag:"live",Lg:"multiline",Mg:"multiselectable",Qg:"orientation",Rg:"owns",Sg:"posinset",Ug:"pressed",Yg:"readonly",$g:"relevant",ah:"required",hh:"selected",jh:"setsize",kh:"sort",Zd:"valuemax",$d:"valuemin",ae:"valuenow",xh:"valuetext"},qf={Of:"alert",
Pf:"alertdialog",Qf:"application",Rf:"article",Uf:"banner",Wd:"button",Wf:"checkbox",Yf:"columnheader",Zf:"combobox",$f:"complementary",cg:"dialog",dg:"directory",fg:"document",jg:"form",lg:"grid",mg:"gridcell",ng:"group",pg:"heading",rg:"img",wg:"link",xg:"list",yg:"listbox",zg:"listitem",Bg:"log",Cg:"main",Dg:"marquee",Eg:"math",Gg:"menu",Hg:"menubar",Ig:"menuitem",Jg:"menuitemcheckbox",Kg:"menuitemradio",Ng:"navigation",Og:"note",Pg:"option",Tg:"presentation",Vg:"progressbar",Wg:"radio",Xg:"radiogroup",
Zg:"region",bh:"row",dh:"rowgroup",eh:"rowheader",fh:"scrollbar",gh:"search",ih:"separator",Yd:"slider",lh:"spinbutton",mh:"status",nh:"tab",oh:"tablist",ph:"tabpanel",qh:"textbox",rh:"timer",sh:"toolbar",th:"tooltip",uh:"tree",vh:"treegrid",wh:"treeitem"};function rf(a){I.call(this);this.g=a;a=Nc(this.g)?this.g:this.g?this.g.body:m;this.kf=!!a&&re(a);this.sd=S(this.g,L?"DOMMouseScroll":"mousewheel",this)}C(rf,U);
rf.prototype.handleEvent=function(a){var b=0,c=0,d=0;a=a.N;if("mousewheel"==a.type){c=1;if(K||M&&(Ja||N("532.0")))c=40;d=sf(-a.wheelDelta,c);v(a.wheelDeltaX)?(b=sf(-a.wheelDeltaX,c),c=sf(-a.wheelDeltaY,c)):c=d}else d=a.detail,100<d?d=3:-100>d&&(d=-3),v(a.axis)&&a.axis===a.HORIZONTAL_AXIS?b=d:c=d;"number"==typeof this.vd&&(b=Yb(b,-this.vd,this.vd));"number"==typeof this.wd&&(c=Yb(c,-this.wd,this.wd));this.kf&&(b=-b);b=new tf(d,a,b,c);this.dispatchEvent(b)};
function sf(a,b){return M&&(Ia||Ka)&&0!=a%b?a:a/b}rf.prototype.d=function(){rf.i.d.call(this);T(this.sd);delete this.sd};function tf(a,b,c,d){b&&this.o(b,j);this.type="mousewheel";this.detail=a;this.va=c;this.wa=d}C(tf,yb);function uf(){I.call(this)}C(uf,U);t=uf.prototype;t.Ea=0;t.Q=0;t.J=100;t.v=0;t.Ca=1;t.Y=q;t.Ta=q;t.Ya=function(a){a=vf(this,a);this.Ea!=a&&(this.Ea=a+this.v>this.J?this.J-this.v:a<this.Q?this.Q:a,!this.Y&&!this.Ta&&this.dispatchEvent("change"))};t.s=function(){return vf(this,this.Ea)};t.nb=function(a){a=vf(this,a);this.v!=a&&(this.v=0>a?0:this.Ea+a>this.J?this.J-this.Ea:a,!this.Y&&!this.Ta&&this.dispatchEvent("change"))};t.ja=function(){return this.Ca==m?this.v:Math.round(this.v/this.Ca)*this.Ca};
t.Ic=function(a){if(this.Q!=a){var b=this.Y;this.Y=l;this.Q=a;a+this.v>this.J&&(this.v=this.J-this.Q);a>this.Ea&&this.Ya(a);a>this.J&&(this.v=0,this.Vb(a),this.Ya(a));this.Y=b;!this.Y&&!this.Ta&&this.dispatchEvent("change")}};t.n=function(){return vf(this,this.Q)};t.Vb=function(a){a=vf(this,a);if(this.J!=a){var b=this.Y;this.Y=l;this.J=a;a<this.Ea+this.v&&this.Ya(a-this.v);a<this.Q&&(this.v=0,this.Ic(a),this.Ya(this.J));a<this.Q+this.v&&(this.v=this.J-this.Q);this.Y=b;!this.Y&&!this.Ta&&this.dispatchEvent("change")}};
t.r=function(){return vf(this,this.J)};t.nc=ba("Ca");function vf(a,b){return a.Ca==m?b:a.Q+Math.round((b-a.Q)/a.Ca)*a.Ca};function wf(a){Ae.call(this,a);this.Rc=m;this.a=new uf;S(this.a,"change",this.fd,q,this)}C(wf,Ae);var yf="dragvaluestart_"+Jb++,zf="dragvalueend_"+Jb++,Af="dragextentstart_"+Jb++,Bf="dragextentend_"+Jb++,Cf="dragstart_"+Jb++,Df="dragend_"+Jb++;t=wf.prototype;t.S="horizontal";t.Gb=q;t.yd=q;t.U=10;t.jb=0;t.tc=l;t.ic=l;t.H=q;t.Ha=function(){wf.i.Ha.call(this);var a=this.Db().Ha("div",Ef(this.S));this.zb(a)};
t.zb=function(a){wf.i.zb.call(this,a);Rb(a,Ef(this.S));a=this.c();var b=ac(m,"goog-slider-thumb",a)[0];b||(b=this.Db().Ha("div","goog-slider-thumb"),b.setAttribute("role",qf.Wd),a.appendChild(b));this.e=this.G=b;this.c().setAttribute("role",qf.Yd);Ff(this)};
t.Ka=function(){wf.i.Ka.call(this);this.T=new Re(this.e);this.ia=new Re(this.G);this.T.ha(this.H);this.ia.ha(this.H);this.T.ec=this.ia.ec=da;this.gb=new Ke(this.c());Y(Y(Y(Y(Y(Y(this.ka(),this.T,"beforedrag",this.dd),this.ia,"beforedrag",this.dd),this.T,["start","end"],this.gd),this.ia,["start","end"],this.gd),this.gb,"key",this.rc),this.c(),"mousedown",this.Ue);this.tc&&Gf(this);this.c().tabIndex=0;Hf(this)};t.eb=function(){wf.i.eb.call(this);ta(this.T,this.ia,this.gb,this.Sa)};
t.dd=function(a){var b=a.hc==this.T?this.e:this.G,c;"vertical"==this.S?(c=this.c().clientHeight-b.offsetHeight,c=(c-a.top)/c*(this.r()-this.n())+this.n()):(c=this.c().clientWidth-b.offsetWidth,c=a.left/c*(this.r()-this.n())+this.n());c=a.hc==this.T?Math.min(Math.max(c,this.n()),this.s()+this.ja()):Math.min(Math.max(c,this.s()),this.r());If(this,b,c)};
t.gd=function(a){var b="start"==a.type,c=this.c();b?Rb(c,"goog-slider-dragging"):Sb(c,"goog-slider-dragging");c=a.target.handle;b?Rb(c,"goog-slider-thumb-dragging"):Sb(c,"goog-slider-thumb-dragging");a=a.hc==this.T;b?(this.dispatchEvent(Cf),this.dispatchEvent(a?yf:Af)):(this.dispatchEvent(Df),this.dispatchEvent(a?zf:Bf))};
t.rc=function(a){var b=l;switch(a.keyCode){case 36:qa(this,this.n());break;case 35:qa(this,this.r());break;case 33:Jf(this,this.U);break;case 34:Jf(this,-this.U);break;case 37:var c=this.H&&this.Pa()?1:-1;Jf(this,a.shiftKey?c*this.U:c*this.qb);break;case 40:Jf(this,a.shiftKey?-this.U:-this.qb);break;case 39:c=this.H&&this.Pa()?-1:1;Jf(this,a.shiftKey?c*this.U:c*this.qb);break;case 38:Jf(this,a.shiftKey?this.U:this.qb);break;default:b=q}b&&a.preventDefault()};
t.Ue=function(a){this.c().focus&&this.c().focus();var b=a.target;!Qc(this.e,b)&&!Qc(this.G,b)&&(this.yd?qa(this,Kf(this,a)):(this.Lc(a),this.M=Lf(this,Kf(this,a)),this.kd="vertical"==this.S?this.Lb<this.M.offsetTop:this.Lb>Mf(this,this.M)+this.M.offsetWidth,a=X(this.c()),Y(Y(this.ka(),a,"mouseup",this.Rd,l),this.c(),"mousemove",this.Lc),this.na||(this.na=new Kb(200),Y(this.ka(),this.na,Mb,this.hd)),this.hd(),this.na.start()))};t.Ve=function(a){Jf(this,(0<a.detail?-1:1)*this.qb);a.preventDefault()};
t.hd=function(){var a;if("vertical"==this.S){var b=this.Lb,c=this.M.offsetTop;this.kd?b<c&&(a=Nf(this,this.M)+this.U):b>c+this.M.offsetHeight&&(a=Nf(this,this.M)-this.U)}else b=this.Lb,c=Mf(this,this.M),this.kd?b>c+this.M.offsetWidth&&(a=Nf(this,this.M)+this.U):b<c&&(a=Nf(this,this.M)-this.U);v(a)&&If(this,this.M,a)};t.Rd=function(){this.na&&this.na.stop();var a=X(this.c());xe(xe(this.ka(),a,"mouseup",this.Rd,l),this.c(),"mousemove",this.Lc)};
function Of(a,b){var c,d=a.c();c=pe(b);d=pe(d);c=new V(c.x-d.x,c.y-d.y);return"vertical"==a.S?c.y:a.H&&a.Pa()?a.c().clientWidth-c.x:c.x}t.Lc=function(a){this.Lb=Of(this,a)};function Kf(a,b){var c=a.n(),d=a.r();if("vertical"==a.S){var e=a.e.offsetHeight,f=a.c().clientHeight-e,e=Of(a,b)-e/2;return(d-c)*(f-e)/f+c}e=a.e.offsetWidth;f=a.c().clientWidth-e;e=Of(a,b)-e/2;return(d-c)*e/f+c}
function Nf(a,b){if(b==a.e)return a.a.s();if(b==a.G)return a.a.s()+a.a.ja();g(Error("Illegal thumb element. Neither minThumb nor maxThumb"))}function Jf(a,b){var c=Nf(a,a.e)+b,d=Nf(a,a.G)+b,c=Yb(c,a.n(),a.r()-a.jb),d=Yb(d,a.n()+a.jb,a.r());Pf(a,c,d-c)}function If(a,b,c){var d=m;b==a.G&&(c<=a.a.r()&&c>=a.a.s()+a.jb)&&(d=c-a.a.s());var e=d||a.a.ja();b==a.e&&(c>=a.n()&&c<=a.a.s()+e-a.jb)&&(b=e-(c-a.a.s()),vf(a.a,c)+vf(a.a,b)==vf(a.a,c+b)&&(Pf(a,c,b),d=m));d!=m&&a.a.nb(d)}
function Pf(a,b,c){a.n()<=b&&(b<=a.r()-c&&a.jb<=c&&c<=a.r()-b)&&!(b==a.s()&&c==a.ja())&&(a.a.Ta=l,a.a.nb(0),a.a.Ya(b),a.a.nb(c),a.a.Ta=q,a.fd())}t.n=function(){return this.a.n()};t.Ic=function(a){this.a.Ic(a)};t.r=function(){return this.a.r()};t.Vb=function(a){this.a.Vb(a)};function Lf(a,b){return b<=a.a.s()+a.a.ja()/2?a.e:a.G}t.fd=function(){Hf(this);Ff(this);this.dispatchEvent("change")};
function Hf(a){if(a.e&&!a.Gb){var b=Qf(a,Nf(a,a.e)),c=Qf(a,Nf(a,a.G));if("vertical"==a.S)a.e.style.top=b.y+"px",a.G.style.top=c.y+"px",a.t&&(b=Rf(c.y,b.y,a.e.offsetHeight),a.t.style.top=b.offset+"px",a.t.style.height=b.size+"px");else{var d=a.H&&a.Pa()?"right":"left";a.e.style[d]=b.x+"px";a.G.style[d]=c.x+"px";a.t&&(b=Rf(b.x,c.x,a.e.offsetWidth),a.t.style[d]=b.offset+"px",a.t.style.width=b.size+"px")}}}function Rf(a,b,c){var d=Math.ceil(c/2);return{offset:a+d,size:Math.max(b-a+c-2*d,0)}}
function Qf(a,b){var c=new V;if(a.e){var d=a.n(),e=a.r(),d=b==d&&d==e?0:(b-d)/(e-d);"vertical"==a.S?(e=a.e.offsetHeight,e=a.c().clientHeight-e,d=Math.round(d*e),c.x=Mf(a,a.e),c.y=e-d):(e=a.c().clientWidth-a.e.offsetWidth,d=Math.round(d*e),c.x=d,c.y=a.e.offsetTop)}return c}
function qa(a,b){b=Yb(b,a.n(),a.r());a.Gb&&a.yb.stop(l);var c=new of,d,e=Lf(a,b),f=a.s(),h=a.ja(),k=Nf(a,e),n=Qf(a,k);d=a.nc();Math.abs(b-k)<d&&(b=Yb(k+(b>k?d:-d),a.n(),a.r()));If(a,e,b);k=Qf(a,Nf(a,e));d="vertical"==a.S?[Mf(a,e),k.y]:[k.x,e.offsetTop];n=new jf(e,[n.x,n.y],d,100);n.ha(a.H);c.add(n);if(a.t){var n=Qf(a,f),p=Qf(a,f+h),h=n;d=p;e==a.e?h=k:d=k;"vertical"==a.S?(e=Rf(p.y,n.y,a.e.offsetHeight),h=Rf(d.y,h.y,a.e.offsetHeight),k=new jf(a.t,[Mf(a,a.t),e.offset],[Mf(a,a.t),h.offset],100),e=new lf(a.t,
e.size,h.size,100)):(e=Rf(n.x,p.x,a.e.offsetWidth),h=Rf(h.x,d.x,a.e.offsetWidth),k=new jf(a.t,[e.offset,a.t.offsetTop],[h.offset,a.t.offsetTop],100),e=new kf(a.t,e.size,h.size,100));k.ha(a.H);e.ha(a.H);c.add(k);c.add(e)}a.Rc&&(f=a.Rc.Ch(f,b,100),P(f,function(a){c.add(a)}));a.yb=c;Y(a.ka(),c,"end",a.ne);a.Gb=l;c.play(q)}t.ne=function(){this.Gb=q};
t.d=function(){wf.i.d.call(this);this.na&&this.na.u();delete this.na;this.yb&&this.yb.u();delete this.yb;delete this.e;delete this.G;this.t&&delete this.t;this.a.u();delete this.a;this.gb&&(this.gb.u(),delete this.gb);this.Sa&&(this.Sa.u(),delete this.Sa);this.T&&(this.T.u(),delete this.T);this.ia&&(this.ia.u(),delete this.ia)};t.qb=1;t.nc=function(){return this.a.nc()};t.s=function(){return this.a.s()};t.Ya=function(a){If(this,this.e,a)};t.ja=function(){return this.a.ja()};
t.nb=function(a){If(this,this.G,this.a.s()+a)};function Ff(a){var b=a.c();if(b){var c=a.n();b.setAttribute("aria-"+pf.$d,c);c=a.r();b.setAttribute("aria-"+pf.Zd,c);a=a.s();b.setAttribute("aria-"+pf.ae,a)}}function Gf(a){a.Sa||(a.Sa=new rf(a.c()));Y(a.ka(),a.Sa,"mousewheel",a.Ve)}function Mf(a,b){return a.H?Qe(b):b.offsetLeft};function Sf(a){wf.call(this,a);this.a.nb(0)}C(Sf,wf);function Ef(a){return"vertical"==a?"goog-slider-vertical":"goog-slider-horizontal"};function Tf(a,b,c){this.O=a;this.tb=c||16;this.pd=Array(this.tb);this.vc=Array(this.tb);a=b;a.length>this.tb&&(this.O.update(a),a=this.O.ab());for(c=0;c<this.tb;c++)b=c<a.length?a[c]:0,this.pd[c]=b^92,this.vc[c]=b^54;this.O.update(this.vc)}C(Tf,Wd);Tf.prototype.reset=function(){this.O.reset();this.O.update(this.vc)};Tf.prototype.update=function(a,b){this.O.update(a,b)};Tf.prototype.ab=function(){var a=this.O.ab();this.O.reset();this.O.update(this.pd);this.O.update(a);return this.O.ab()};function Uf(a){this.f=a}var Vf=/\s*;\s*/;t=Uf.prototype;t.set=function(a,b,c,d,e,f){/[;=\s]/.test(a)&&g(Error('Invalid cookie name "'+a+'"'));/[;\r\n]/.test(b)&&g(Error('Invalid cookie value "'+b+'"'));v(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(B()+1E3*c)).toUTCString();this.f.cookie=a+"="+b+e+d+c+f};
t.get=function(a,b){for(var c=a+"=",d=(this.f.cookie||"").split(Vf),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};t.remove=function(a,b,c){var d=this.ta(a);this.set(a,"",0,b,c);return d};t.za=function(){return Wf(this).keys};t.X=function(){return Wf(this).values};t.ta=function(a){return v(this.get(a))};
function Wf(a){a=(a.f.cookie||"").split(Vf);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}}var Xf=new Uf(document);Xf.Fg=3950;var Yf=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function Zf(a){if("function"==typeof a.X)return a.X();if(x(a))return a.split("");if(ga(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return db(a)};function $f(a,b){this.ca={};this.l=[];var c=arguments.length;if(1<c){c%2&&g(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof $f?(c=a.za(),d=a.X()):(c=eb(a),d=db(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}}t=$f.prototype;t.b=0;t.Ud=0;t.X=function(){bg(this);for(var a=[],b=0;b<this.l.length;b++)a.push(this.ca[this.l[b]]);return a};t.za=function(){bg(this);return this.l.concat()};t.ta=function(a){return cg(this.ca,a)};
t.remove=function(a){return cg(this.ca,a)?(delete this.ca[a],this.b--,this.Ud++,this.l.length>2*this.b&&bg(this),l):q};function bg(a){if(a.b!=a.l.length){for(var b=0,c=0;b<a.l.length;){var d=a.l[b];cg(a.ca,d)&&(a.l[c++]=d);b++}a.l.length=c}if(a.b!=a.l.length){for(var e={},c=b=0;b<a.l.length;)d=a.l[b],cg(e,d)||(a.l[c++]=d,e[d]=1),b++;a.l.length=c}}t.get=function(a,b){return cg(this.ca,a)?this.ca[a]:b};t.set=function(a,b){cg(this.ca,a)||(this.b++,this.l.push(a),this.Ud++);this.ca[a]=b};t.clone=function(){return new $f(this)};
function cg(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function dg(a,b){var c;if(a instanceof dg)this.I=v(b)?b:a.I,eg(this,a.Xa),c=a.Zb,$(this),this.Zb=c,c=a.bb,$(this),this.bb=c,fg(this,a.Sb),c=a.Rb,$(this),this.Rb=c,gg(this,a.ra.clone()),c=a.Bb,$(this),this.Bb=c;else if(a&&(c=String(a).match(Yf))){this.I=!!b;eg(this,c[1]||"",l);var d=c[2]||"";$(this);this.Zb=d?decodeURIComponent(d):"";d=c[3]||"";$(this);this.bb=d?decodeURIComponent(d):"";fg(this,c[4]);d=c[5]||"";$(this);this.Rb=d?decodeURIComponent(d):"";gg(this,c[6]||"",l);c=c[7]||"";$(this);this.Bb=
c?decodeURIComponent(c):""}else this.I=!!b,this.ra=new hg(m,0,this.I)}t=dg.prototype;t.Xa="";t.Zb="";t.bb="";t.Sb=m;t.Rb="";t.Bb="";t.jf=q;t.I=q;
t.toString=function(){var a=[],b=this.Xa;b&&a.push(ig(b,jg),":");if(b=this.bb){a.push("//");var c=this.Zb;c&&a.push(ig(c,jg),"@");a.push(encodeURIComponent(String(b)));b=this.Sb;b!=m&&a.push(":",String(b))}if(b=this.Rb)this.bb&&"/"!=b.charAt(0)&&a.push("/"),a.push(ig(b,"/"==b.charAt(0)?kg:lg));(b=this.ra.toString())&&a.push("?",b);(b=this.Bb)&&a.push("#",ig(b,mg));return a.join("")};t.clone=function(){return new dg(this)};
function eg(a,b,c){$(a);a.Xa=c?b?decodeURIComponent(b):"":b;a.Xa&&(a.Xa=a.Xa.replace(/:$/,""))}function fg(a,b){$(a);b?(b=Number(b),(isNaN(b)||0>b)&&g(Error("Bad port number "+b)),a.Sb=b):a.Sb=m}function gg(a,b,c){$(a);b instanceof hg?(a.ra=b,a.ra.Hc(a.I)):(c||(b=ig(b,ng)),a.ra=new hg(b,0,a.I))}function og(a,b,c){$(a);fa(c)||(c=[String(c)]);pg(a.ra,b,c)}function $(a){a.jf&&g(Error("Tried to modify a read-only Uri"))}t.Hc=function(a){this.I=a;this.ra&&this.ra.Hc(a);return this};
function ig(a,b){return x(a)?encodeURI(a).replace(b,qg):m}function qg(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var jg=/[#\/\?@]/g,lg=/[\#\?:]/g,kg=/[\#\?]/g,ng=/[\#\?@]/g,mg=/#/g;function hg(a,b,c){this.F=a||m;this.I=!!c}
function rg(a){if(!a.k&&(a.k=new $f,a.b=0,a.F))for(var b=a.F.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=m,f=m;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=sg(a,e);a.add(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}t=hg.prototype;t.k=m;t.b=m;t.add=function(a,b){rg(this);this.F=m;a=sg(this,a);var c=this.k.get(a);c||this.k.set(a,c=[]);c.push(b);this.b++;return this};
t.remove=function(a){rg(this);a=sg(this,a);return this.k.ta(a)?(this.F=m,this.b-=this.k.get(a).length,this.k.remove(a)):q};t.ta=function(a){rg(this);a=sg(this,a);return this.k.ta(a)};t.za=function(){rg(this);for(var a=this.k.X(),b=this.k.za(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};t.X=function(a){rg(this);var b=[];if(a)this.ta(a)&&(b=tb(b,this.k.get(sg(this,a))));else{a=this.k.X();for(var c=0;c<a.length;c++)b=tb(b,a[c])}return b};
t.set=function(a,b){rg(this);this.F=m;a=sg(this,a);this.ta(a)&&(this.b-=this.k.get(a).length);this.k.set(a,[b]);this.b++;return this};t.get=function(a,b){var c=a?this.X(a):[];return 0<c.length?String(c[0]):b};function pg(a,b,c){a.remove(b);0<c.length&&(a.F=m,a.k.set(sg(a,b),ub(c)),a.b+=c.length)}
t.toString=function(){if(this.F)return this.F;if(!this.k)return"";for(var a=[],b=this.k.za(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.X(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+encodeURIComponent(String(d[f])));a.push(h)}return this.F=a.join("&")};t.clone=function(){var a=new hg;a.F=this.F;this.k&&(a.k=this.k.clone(),a.b=this.b);return a};function sg(a,b){var c=String(b);a.I&&(c=c.toLowerCase());return c}
t.Hc=function(a){if(a&&!this.I){rg(this);this.F=m;var b=this.k,c=function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),pg(this,c,a))};if("function"==typeof b.forEach)b.forEach(c,this);else if(ga(b)||x(b))P(b,c,this);else{var d;if("function"==typeof b.za)d=b.za();else if("function"!=typeof b.X)if(ga(b)||x(b)){d=[];for(var e=b.length,f=0;f<e;f++)d.push(f)}else d=eb(b);else d=j;b=Zf(b);e=b.length;for(f=0;f<e;f++)c.call(this,b[f],d&&d[f])}}this.I=a};function tg(){if(this&&this.Md){var a=this.Md;a&&"SCRIPT"==a.tagName&&ug(a,l,this.Wb)}}function ug(a,b,c){c!=m&&u.clearTimeout(c);a.onload=da;a.onerror=da;a.onreadystatechange=da;b&&window.setTimeout(function(){Cc(a)},0)}function vg(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);nb.call(this,c);this.code=a}C(vg,nb);function wg(a,b){this.Mf=new dg(a);this.ce=b?b:"callback";this.Wb=5E3}var xg=0;
wg.prototype.send=function(a,b,c,d){var e=a||m,f=d||"_"+(xg++).toString(36)+B().toString(36);u._callbacks_||(u._callbacks_={});a=this.Mf.clone();if(e)for(var h in e)(!e.hasOwnProperty||e.hasOwnProperty(h))&&og(a,h,e[h]);b&&(u._callbacks_[f]=function(a){yg(f,l);b.apply(j,arguments)},og(a,this.ce,"_callbacks_."+f));var k=a.toString(),n={timeout:this.Wb,ee:l};h=n.document||document;var p=rc("SCRIPT");a={Md:p,Wb:j};var r=new $d(tg,a),s=m;d=n.timeout!=m?n.timeout:5E3;0<d&&(s=window.setTimeout(function(){ug(p,
l);r.La(new vg(1,"Timeout reached for loading script "+k))},d),a.Wb=s);p.onload=p.onreadystatechange=function(){if(!p.readyState||"loaded"==p.readyState||"complete"==p.readyState)ug(p,n.ee||q,s),r.V(m)};p.onerror=function(){ug(p,l,s);r.La(new vg(0,"Error while loading script "+k))};ec(p,{type:"text/javascript",charset:"UTF-8",src:k});a=h.getElementsByTagName("HEAD");(!a||0==a.length?h.documentElement:a[0]).appendChild(p);fe(r,m,function(){yg(f,q);c&&c(e)},j);return{P:f,Xc:r}};
wg.prototype.cancel=function(a){a&&(a.Xc&&a.Xc.cancel(),a.P&&yg(a.P,q))};function yg(a,b){u._callbacks_[a]&&(b?delete u._callbacks_[a]:u._callbacks_[a]=da)};angular.module("Napster",[]).controller("Controller",["$scope",function(a){a.zh=H;a.Fh=E;a.Xh=zg;a.Mc=F;a.Zh=D;if(H.Xb){D.Ec=function(b){var c=a.$root.$$phase;"$apply"==c||"$digest"==c?b&&"function"===typeof b&&b():a.$apply(b)};var b={},c=function(a,c,d){function e(b){a[c]=b.val();D.update()}b[d]=b[d]||e;return b[d]},d={},e=function(a,b){function c(b){a[b.name()]=b.val();D.update()}d[b]=d[b]||c;return d[b]},f=function(a){return eb(a).exclude("processed").filter(function(b){return"string"==typeof a[b]})};
E.w().limit(500).on("child_added",function(a){e(E.data.w)(a);f(E.data.w).forEach(function(a){var b=E.data.w[a],d="track"+b;E.h(b).off("value",c(E.data.h,b,d));E.h(b).on("value",function(a){c(E.data.h,b,d)(a);E.data.w.Va[b]=a.val()})})});E.j().on("value",function(a){c(E.data.j,H.$a)(a);var b=E.data.j[H.$a];if(b.Hb==q)E.j().Hb.set(l);else{for(var d in b.qc){a=b.qc[d];var p="group"+a,r=p+"members",s=p+"messages",p=p+"name",z=E.group(a).hb().limit(500),G=E.group(a).ib().limit(500),A=E.group(a).name;E.data.group[d]=
E.data.group[d]||{hb:{},ib:{},name:""};z.off("child_added",e(E.data.group[a].hb,r));z.on("child_added",e(E.data.group[a].hb,r));G.off("child_added",e(E.data.group[a].ib,s));G.on("child_added",e(E.data.group[a].ib,s));A.off("value",c(E.data.group[a],"name",p));A.on("value",c(E.data.group[a],"name",p))}b.Z=b.Z||{};b.Z.Va=b.Z.Va||{};f(b.Z).map(function(a){return b.Z[a]}).add(b.pa.h).unique().compact().forEach(function(a){var d="track"+a;E.h(a).off("value",c(E.data.h,a,d));E.h(a).on("value",function(e){c(E.data.h,
a,d)(e);var f=e.val();f.id=a;f.length=F.Fc(f.length);f.w=(new Date(f.w)).format("{12hr}{tt}, {yyyy}-{MM}-{dd}");H.cd(f.xc,function(c){f.xc=c;f.Ad="";if(f.id==(F.ua||b.pa.h))f.Ad="now-playing",b.Sh=f;b.Z.Va[a]=f;D.update();F.p.stopVideo&&!window.mf&&(window.mf=l,F.Sd())})})});E.data.j.current=b;window.je=l;D.update()}})}}]);var zg=new function(){var a=this;a.xd=function(a,c,d){a={V:"callback",type:"master",Cf:a};c&&("artist"in a&&g(Error('The object already contains the key "artist"')),a.artist=c);(new wg("http://api.discogs.com/database/search")).send(a,function(a){var b=[],c=[];(fb(a,"data","results")||[]).slice(0,20).forEach(function(a){var d=(a.title||"").split("-"),e=d.slice(1).join("").trim(),d=d[0].split("(")[0].trim(),r=(a.Cb||[])[0];a=a.$b;var s=H.hash(e+d+a);b.add({title:e,rb:d,Cb:r,$b:a,id:s});c.add(new $d)});
d(b,c)})};a.search=function(b,c,d){a.xd(b,c,function(b,c){var h=new he(c,q,l);fe(h,function(a){return qb(a,function(a){return a[1]})},m,j);for(var k=0;k<b.length;++k){var n=b[k];a.Mc(n.title,n.rb,k,function(a,b){c[b].V(a,b)})}fe(h,function(a){function c(a){return a.Fa}a.forEach(function(a,c){var d=b[c];d.Fa=a.Fa;d.Ga=a.Ga;d.length=a.length});a=b.findAll(c).unique(c).sortBy(function(a){return a.Ga},l);a.forEach(function(a){var b=E.h(a.id);b.update({rb:a.rb,Cb:a.Cb,length:(a.length||0).toNumber(),title:a.title,
$b:(a.$b||42).toNumber(),Fa:a.Fa,Ga:(a.Ga||0).toNumber()});b.update({Dc:0})});d(a)},m,j)})};a.Mc=function(a,c,d,e){c=c.replace("Various","Song");(new wg("http://gdata.youtube.com/feeds/api/videos")).send({V:"callback",alt:"json-in-script",$h:2,Cf:"{0} {1} {2}".assign({"0":a,1:c,2:[].reduce(function(d,e){var k=e.toLowerCase();return d+(!a.toLowerCase().has(k)&&!c.toLowerCase().has(k)?' -"{0}"'.assign({"0":k}):"")},"")})},function(a){if(!fb(a,"feed","entry"))return e({},d);a=a.Jh.Hh.map(function(a){var b=
(fb(a,"id","$t")||"").split("video:")[1],c=(fb(a,"yt$statistics","viewCount")||0).toNumber(),d=fb(a,"media$group","media$content",0,"duration"),e=((a.ai||{}).find(function(a){return"embed"==a.action})||{}).Vh;a=fb(a,"app$control","yt$state");return{Fa:b,Ga:c,length:d,df:!("allowed"!=e||a)}}).findAll(function(a){return a.df}).slice(0,5).sortBy(function(a){return a.Ga},l);e(a[0]||{},d)})}};var H=new function(){function a(a){return"{0}@firebase.com".assign({"0":a})}var b=this;b.o=function(){b.xb=5E6;b.Xb=Xf.get("napsterfm-token");b.$a=Xf.get("napsterfm-userid");b.Pc=Xf.get("napsterfm-username");b.Xb&&(E.root.auth(b.Xb),E.j().Hb.set(l),E.j().Hb.setOnDisconnect(q))};b.cd=function(a,b){E.j(a).Pc.once("value",function(a){b(a.val().replace("@firebase.com",""))})};b.hash=function(a){var b=new Tf(new Zd,"napster");b.reset();b.update(a);return b.ab().map(function(a){return a.toString(36)}).join("")};
b.login=function(c,d){var e=new $d;(new FirebaseAuthClient(E.root)).login("password",a(c),d,function(a,d,k){a?e.V(a):(Xf.set("napsterfm-token",d,b.xb),Xf.set("napsterfm-userid",k.id,b.xb),Xf.set("napsterfm-username",c,b.xb),document.location.reload(l))});return e};b.pf=function(){E.root.unauth();Xf.remove("napsterfm-token");Xf.remove("napsterfm-userid");Xf.remove("napsterfm-username");document.location.reload(l)};b.createUser=function(b,d){var e=new $d;(new FirebaseAuthClient(E.root)).createUser(a(b),
d,function(a){a&&e.V(a)});return e};b.changePassword=function(b,d,e){var f=new $d;(new FirebaseAuthClient(E.root)).changePassword(a(b),d,e,function(a){a&&f.V(a)});return f}};var D=new function(){var a=this;a.o=function(){window.onhashchange=function(){function a(b,c,f){b=pa(b);for(var h=0;h<b.length;++h){var k=b[h],n=f?f(k):k;k.getAttribute(c)==window.location.hash?Rb(n,"active"):Sb(n,"active")}}a(".navbar a","href",function(a){return a.parentNode});a("[hash-location]","hash-location")};if(window.location.hash)window.onhashchange();else window.location.hash=pa(".navbar li.active")[0].ad()[0].getAttribute("href");var b=new Ee;b.Wc=wb;Ce(b,pa("#library-table")[0]);a.z=
new Sf;b=a.z;b.ma&&l!=b.tc&&Gf(b);b.tc=l;a.z.yd=l;a.z.onclick=function(){a.z.Td=l;F.time(a.z.s());window.setTimeout(function(){a.z.Td=q},1E3)};Ce(a.z,pa("#player .slider")[0])};a.update=function(){a.zf=window.isNaN(F.R)?"loading":"";a.Bf=F.m?"playing":"paused";a.Ec&&a.Ec()}};var Ag=new function(){this.log=function(a){console.log(a)};this.nf=function(){console.log("foo")};this.of=function(a){console.log(a.val())};this.qf=function(a){E.j().Z.push(a[0].id)}};var E=new function(){var a=this;a.data={group:{},w:{Va:{}},h:{},j:{}};a.root=new Firebase("https://napsterfm.firebaseio.com/");a.group=function(b){b=(b||0).toString();var c=a.root.child("group").child(b);c.hb=c.child("members");c.Qh=function(a){a=a.toString();return c.hb.child(a)};c.ib=c.child("messages");c.message=function(a){a=a.toString();a=c.ib.child(a);a.Ah=a.child("author");a.Dh=a.child("created");a.text=a.child("text");return a};c.name=c.child("name");return c};a.w=function(){return a.root.child("lastPlayed")};
a.h=function(b){b=b.toString();b=a.root.child("track").child(b);b.rb=b.child("artist");b.Cb=b.child("genre");b.w=b.child("lastPlayed");b.xc=b.child("lastPlayedBy");b.length=b.child("length");b.Dc=b.child("playCount");b.title=b.child("title");b.$b=b.child("year");b.Fa=b.child("youtubeid");b.Ga=b.child("youtubeviews");return b};a.j=function(b){b=(b||H.$a).toString();var c=a.root.child("user").child(b);c.qc=c.child("groups");c.group=function(a){a=a.toString();return c.qc.child(a)};c.Zc=c.child("following");
c.Xe=c.child("hotlist");c.Nh=function(a){a=a.toString();return c.Xe.child(a)};c.Hb=c.child("isOnline");c.pa=c.child("nowPlaying");c.kb={m:c.pa.child("isPlaying"),Kb:c.pa.child("lastChange"),time:c.pa.child("time"),h:c.pa.child("track")};c.Z=c.child("library");c.Ph=function(a){a=a.toString();return c.Z.child(a)};c.Lf=c.child("transfers");c.Yh=function(a){a=a.toString();a=c.Lf.child(a);a.from=a.child("from");a.h=a.child("track");return a};c.Pc=c.child("username");return c}};function pa(a){var b=Bg.qa(a),c=1>b.length;c&&1>(new DOMParser).parseFromString(a,"text/xml").getElementsByTagName("parsererror").length?(c=Bg.createElement("div"),c.innerHTML=a,b[0]=c.firstChild):c&&(b[0]={});for(var d in Bg){for(a=0;a<b.length;++a)b[a][d]=b[a][d]||Bg[d].fill(b[a]);b[d]=b[0]&&b[0][d]}return b}
var Bg={append:xc,appendChild:wc,canHaveChildren:vc,ge:Rc,contains:Qc,Ha:function(a,b,c){return nc(document,arguments)},createElement:rc,ie:function(a,b,c){return sc(document,a,b,!!c)},createTextNode:function(a){return document.createTextNode(a)},pe:Uc,qe:Zc,re:ad,te:Ec,ue:nd,ve:ld,we:md,xe:kd,ad:Fc,ze:function(){return uc()?"CSS1Compat":"BackCompat"},kc:function(){return document},Ae:function(){return jc(window)},Ma:function(){return kc(document)},Be:function(){return lc(document)},Db:W,c:$b,lc:dc,
mc:cc,Ce:ac,De:Gc,Ee:Vc,Fe:Wc,Ge:Ic,He:Jc,Ie:Lc,Je:jd,Ke:hd,Le:id,Me:Yc,Ne:X,Lh:function(a){return W((a||u||window).document).Ma()},Oe:Pc,Pe:Kc,Qe:Mc,Mh:function(a){var b=[];gd(a,b,q);return b.join("")},Re:fd,Se:gc,pc:mc,Ye:function(a){return tc(document,a)},af:Bc,bf:Ac,cf:zc,sc:uc,isElement:Nc,ff:dd,gf:pc,hf:qc,lf:Oc,qa:Vd,Ld:yc,removeNode:Cc,Df:Dc,Ff:ed,Gf:ec,Hf:Xc},Cg;for(Cg in Bg)pa[Cg]=Bg[Cg];/*
 EXPORT START  EXPORT END */
window.exports={authentication:H,"authentication.cookieAge":H.xb,"authentication.token":H.Xb,"authentication.userid":H.$a,"authentication.username":H.Pc,"authentication.init":H.o,"authentication.getUsername":H.cd,"authentication.hash":H.hash,"authentication.login":H.login,"authentication.logout":H.pf,"authentication.createUser":H.createUser,"authentication.changePassword":H.changePassword,closurequery:{},controllers:{},datastore:E,"datastore.data":E.data,"datastore.root":E.root,"datastore.group":E.group,
"datastore.lastPlayed":E.w,"datastore.track":E.h,"datastore.user":E.j,debug:Ag,"debug.log":Ag.log,"debug.logFoo":Ag.nf,"debug.logVal":Ag.of,"debug.lucky":Ag.qf,require:{},services:zg,"services.metadata":zg.xd,"services.search":zg.search,"services.stream":zg.Mc,stream:F,"stream.isPlaying":F.m,"stream.newTime":F.R,"stream.newTimeProcessed":F.tf,"stream.player":F.p,"stream.syncTimeouts":F.Nc,"stream.init":F.o,"stream.isFinished":F.ef,"stream.length":F.length,"stream.loadTrack":F.td,"stream.mute":F.mute,
"stream.onFinished":F.Gd,"stream.play":F.play,"stream.processTime":F.Fc,"stream.sync":F.Sd,"stream.time":F.time,"stream.updateNowPlaying":F.Yb,"stream.volume":F.volume,ui:D,"ui.pageLoadingClass":D.zf,"ui.playButtonClass":D.Bf,"ui.slider":D.z,"ui.init":D.o,"ui.postUpdate":D.Ec,"ui.update":D.update,"datastore.data.group":E.data.group,"datastore.data.lastPlayed":E.data.w,"datastore.data.lastPlayed.processed":E.data.w.Va,"datastore.data.track":E.data.h,"datastore.data.user":E.data.j,"datastore.data.user.current":E.data.j.current};H.o();D.o();F.o();
