function g(a){throw a;}var j=void 0,l=!0,m=null,p=!1;function aa(a){return function(b){this[a]=b}}function ba(a){return function(){return this[a]}}var t,u=this;function ca(a,b){var c=a.split("."),d=u;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&w(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function da(){}
function ea(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function w(a){return a!==j}function fa(a){return"array"==ea(a)}function ga(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length}function x(a){return"string"==typeof a}function ha(a){return"function"==ea(a)}function ia(a){var b=typeof a;return"object"==b&&a!=m||"function"==b}function ja(a){return a[ka]||(a[ka]=++la)}var ka="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),la=0;
function ma(a,b,c){return a.call.apply(a.bind,arguments)}function na(a,b,c){a||g(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function y(a,b,c){y=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ma:na;return y.apply(m,arguments)}var B=Date.now||function(){return+new Date};
function C(a,b){function c(){}c.prototype=b.prototype;a.i=b.prototype;a.prototype=new c;a.prototype.constructor=a};function D(){0!=oa&&(this.Eh=Error().stack,pa[ja(this)]=this)}var oa=0,pa={};D.prototype.gc=p;D.prototype.u=function(){if(!this.gc&&(this.gc=l,this.d(),0!=oa)){var a=ja(this);delete pa[a]}};D.prototype.d=function(){this.ke&&qa.apply(m,this.ke);if(this.Ed)for(;this.Ed.length;)this.Ed.shift()()};function qa(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];ga(d)?qa.apply(m,d):d&&"function"==typeof d.u&&d.u()}};function E(a,b){this.type=a;this.currentTarget=this.target=b}t=E.prototype;t.d=function(){};t.u=function(){};t.Wa=p;t.defaultPrevented=p;t.Tb=l;t.preventDefault=function(){this.defaultPrevented=l;this.Tb=p};function ra(a){a.preventDefault()};function sa(){}var ta=0;t=sa.prototype;t.key=0;t.Ba=p;t.ub=p;t.o=function(a,b,c,d,e,f){ha(a)?this.nd=l:a&&a.handleEvent&&ha(a.handleEvent)?this.nd=p:g(Error("Invalid listener argument"));this.Qa=a;this.Jd=b;this.src=c;this.type=d;this.capture=!!e;this.Eb=f;this.ub=p;this.key=++ta;this.Ba=p};t.handleEvent=function(a){return this.nd?this.Qa.call(this.Eb||this.src,a):this.Qa.handleEvent.call(this.Qa,a)};function ua(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function va(a){if(!wa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(xa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ya,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(za,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Aa,"&quot;"));return a}var xa=/&/g,ya=/</g,za=/>/g,Aa=/\"/g,wa=/[&<>\"]/;Math.random();var Ba,Ca,Da,Ea,Fa,Ga,Ha;function Ia(){return u.navigator?u.navigator.userAgent:m}function Ja(){return u.navigator}Ea=Da=Ca=Ba=p;var Ka;if(Ka=Ia()){var La=Ja();Ba=0==Ka.indexOf("Opera");Ca=!Ba&&-1!=Ka.indexOf("MSIE");(Da=!Ba&&-1!=Ka.indexOf("WebKit"))&&Ka.indexOf("Mobile");Ea=!Ba&&!Da&&"Gecko"==La.product}var Ma=Ba,F=Ca,H=Ea,I=Da,Na,Oa=Ja();Na=Oa&&Oa.platform||"";Fa=-1!=Na.indexOf("Mac");Ga=-1!=Na.indexOf("Win");Ha=-1!=Na.indexOf("Linux");Ja()&&(Ja().appVersion||"").indexOf("X11");
function Pa(){var a=u.document;return a?a.documentMode:j}var Qa;a:{var Ra="",Sa;if(Ma&&u.opera)var Ta=u.opera.version,Ra="function"==typeof Ta?Ta():Ta;else if(H?Sa=/rv\:([^\);]+)(\)|;)/:F?Sa=/MSIE\s+([^\);]+)(\)|;)/:I&&(Sa=/WebKit\/(\S+)/),Sa)var Ua=Sa.exec(Ia()),Ra=Ua?Ua[1]:"";if(F){var Va=Pa();if(Va>parseFloat(Ra)){Qa=String(Va);break a}}Qa=Ra}var Wa={};
function J(a){var b;if(!(b=Wa[a])){b=0;for(var c=ua(String(Qa)).split("."),d=ua(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"",n=RegExp("(\\d*)(\\D*)","g"),q=RegExp("(\\d*)(\\D*)","g");do{var r=n.exec(h)||["","",""],s=q.exec(k)||["","",""];if(0==r[0].length&&0==s[0].length)break;b=((0==r[1].length?0:parseInt(r[1],10))<(0==s[1].length?0:parseInt(s[1],10))?-1:(0==r[1].length?0:parseInt(r[1],10))>(0==s[1].length?0:parseInt(s[1],10))?1:0)||((0==r[2].length)<
(0==s[2].length)?-1:(0==r[2].length)>(0==s[2].length)?1:0)||(r[2]<s[2]?-1:r[2]>s[2]?1:0)}while(0==b)}b=Wa[a]=0<=b}return b}function Xa(a){return F&&Ya>=a}var Za=u.document,Ya=!Za||!F?j:Pa()||("CSS1Compat"==Za.compatMode?parseInt(Qa,10):5);function $a(a,b){for(var c in a)b.call(j,a[c],c,a)}function ab(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function bb(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function cb(a,b){for(var c=ga(b),d=c?b:arguments,c=c?0:1;c<d.length&&!(a=a[d[c]],!w(a));c++);return a}function db(){var a=eb,b;for(b in a)return p;return l}var fb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
function gb(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<fb.length;f++)c=fb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var hb=!F||Xa(9),ib=!F||Xa(9),jb=F&&!J("9");!I||J("528");H&&J("1.9b")||F&&J("8")||Ma&&J("9.5")||I&&J("528");H&&!J("8")||F&&J("9");function kb(a){Error.captureStackTrace?Error.captureStackTrace(this,kb):this.stack=Error().stack||"";a&&(this.message=String(a))}C(kb,Error);kb.prototype.name="CustomError";var K=Array.prototype,lb=K.indexOf?function(a,b,c){return K.indexOf.call(a,b,c)}:function(a,b,c){c=c==m?0:0>c?Math.max(0,a.length+c):c;if(x(a))return!x(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},L=K.forEach?function(a,b,c){K.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=x(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},mb=K.filter?function(a,b,c){return K.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=x(a)?a.split(""):
a,k=0;k<d;k++)if(k in h){var n=h[k];b.call(c,n,k,a)&&(e[f++]=n)}return e},nb=K.map?function(a,b,c){return K.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=x(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e},ob=K.some?function(a,b,c){return K.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=x(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return l;return p};function pb(a,b){var c=lb(a,b),d;(d=0<=c)&&K.splice.call(a,c,1);return d}
function qb(a){return K.concat.apply(K,arguments)}function rb(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function sb(a,b,c){return 2>=arguments.length?K.slice.call(a,b):K.slice.call(a,b,c)}function tb(a,b){return a>b?1:a<b?-1:0};function ub(a){ub[" "](a);return a}ub[" "]=da;function vb(a,b){a&&this.o(a,b)}C(vb,E);var wb=[1,4,2];t=vb.prototype;t.target=m;t.relatedTarget=m;t.offsetX=0;t.offsetY=0;t.clientX=0;t.clientY=0;t.screenX=0;t.screenY=0;t.button=0;t.keyCode=0;t.charCode=0;t.ctrlKey=p;t.altKey=p;t.shiftKey=p;t.metaKey=p;t.zf=p;t.N=m;
t.o=function(a,b){var c=this.type=a.type;E.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(H){var e;a:{try{ub(d.nodeName);e=l;break a}catch(f){}e=p}e||(d=m)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=I||a.offsetX!==j?a.offsetX:a.layerX;this.offsetY=I||a.offsetY!==j?a.offsetY:a.layerY;this.clientX=a.clientX!==j?a.clientX:a.pageX;this.clientY=a.clientY!==j?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.zf=Fa?a.metaKey:a.ctrlKey;this.state=a.state;this.N=a;a.defaultPrevented&&this.preventDefault();delete this.Wa};
t.preventDefault=function(){vb.i.preventDefault.call(this);var a=this.N;if(a.preventDefault)a.preventDefault();else if(a.returnValue=p,jb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};t.xe=ba("N");t.d=function(){};var xb={},M={},yb={},zb={};
function N(a,b,c,d,e){if(fa(b)){for(var f=0;f<b.length;f++)N(a,b[f],c,d,e);return m}a:{b||g(Error("Invalid event type"));d=!!d;var h=M;b in h||(h[b]={b:0,L:0});h=h[b];d in h||(h[d]={b:0,L:0},h.b++);var h=h[d],f=ja(a),k;h.L++;if(h[f]){k=h[f];for(var n=0;n<k.length;n++)if(h=k[n],h.Qa==c&&h.Eb==e){if(h.Ba)break;k[n].ub=p;a=k[n].key;break a}}else k=h[f]=[],h.b++;var q=Ab,r=ib?function(a){return q.call(r.src,r.key,a)}:function(a){a=q.call(r.src,r.key,a);if(!a)return a},n=r;n.src=a;h=new sa;h.o(c,n,a,b,
d,e);h.ub=p;c=h.key;n.key=c;k.push(h);xb[c]=h;yb[f]||(yb[f]=[]);yb[f].push(h);a.addEventListener?(a==u||!a.Tc)&&a.addEventListener(b,n,d):a.attachEvent(b in zb?zb[b]:zb[b]="on"+b,n);a=c}return a}function Bb(a,b,c,d,e){if(fa(b))for(var f=0;f<b.length;f++)Bb(a,b[f],c,d,e);else if(d=!!d,a=Cb(a,b,d))for(f=0;f<a.length;f++)if(a[f].Qa==c&&a[f].capture==d&&a[f].Eb==e){O(a[f].key);break}}
function O(a){if(!xb[a])return p;var b=xb[a];if(b.Ba)return p;var c=b.src,d=b.type,e=b.Jd,f=b.capture;c.removeEventListener?(c==u||!c.Tc)&&c.removeEventListener(d,e,f):c.detachEvent&&c.detachEvent(d in zb?zb[d]:zb[d]="on"+d,e);c=ja(c);yb[c]&&(e=yb[c],pb(e,b),0==e.length&&delete yb[c]);b.Ba=l;if(b=M[d][f][c])b.yd=l,Db(d,f,c,b);delete xb[a];return l}
function Db(a,b,c,d){if(!d.Mb&&d.yd){for(var e=0,f=0;e<d.length;e++)d[e].Ba?d[e].Jd.src=m:(e!=f&&(d[f]=d[e]),f++);d.length=f;d.yd=p;0==f&&(delete M[a][b][c],M[a][b].b--,0==M[a][b].b&&(delete M[a][b],M[a].b--),0==M[a].b&&delete M[a])}}function Cb(a,b,c){var d=M;return b in d&&(d=d[b],c in d&&(d=d[c],a=ja(a),d[a]))?d[a]:m}
function Eb(a,b,c,d,e){var f=1;b=ja(b);if(a[b]){a.L--;a=a[b];a.Mb?a.Mb++:a.Mb=1;try{for(var h=a.length,k=0;k<h;k++){var n=a[k];n&&!n.Ba&&(f&=Fb(n,e)!==p)}}finally{a.Mb--,Db(c,d,b,a)}}return Boolean(f)}function Fb(a,b){a.ub&&O(a.key);return a.handleEvent(b)}
function Ab(a,b){if(!xb[a])return l;var c=xb[a],d=c.type,e=M;if(!(d in e))return l;var e=e[d],f,h;if(!ib){var k;if(!(k=b))a:{k=["window","event"];for(var n=u;f=k.shift();)if(n[f]!=m)n=n[f];else{k=m;break a}k=n}f=k;k=l in e;n=p in e;if(k){if(0>f.keyCode||f.returnValue!=j)return l;a:{var q=p;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(r){q=l}if(q||f.returnValue==j)f.returnValue=l}}q=new vb;q.o(f,this);f=l;try{if(k){for(var s=[],z=q.currentTarget;z;z=z.parentNode)s.push(z);h=e[l];h.L=h.b;for(var G=
s.length-1;!q.Wa&&0<=G&&h.L;G--)q.currentTarget=s[G],f&=Eb(h,s[G],d,l,q);if(n){h=e[p];h.L=h.b;for(G=0;!q.Wa&&G<s.length&&h.L;G++)q.currentTarget=s[G],f&=Eb(h,s[G],d,p,q)}}else f=Fb(c,q)}finally{s&&(s.length=0)}return f}d=new vb(b,this);return f=Fb(c,d)}var Gb=0;function P(){D.call(this)}C(P,D);t=P.prototype;t.Tc=l;t.Qb=m;t.Ic=aa("Qb");t.addEventListener=function(a,b,c,d){N(this,a,b,c,d)};t.removeEventListener=function(a,b,c,d){Bb(this,a,b,c,d)};
t.dispatchEvent=function(a){var b=a.type||a,c=M;if(b in c){if(x(a))a=new E(a,this);else if(a instanceof E)a.target=a.target||this;else{var d=a;a=new E(b,this);gb(a,d)}var d=1,e,c=c[b],b=l in c,f;if(b){e=[];for(f=this;f;f=f.Qb)e.push(f);f=c[l];f.L=f.b;for(var h=e.length-1;!a.Wa&&0<=h&&f.L;h--)a.currentTarget=e[h],d&=Eb(f,e[h],a.type,l,a)&&a.Tb!=p}if(p in c)if(f=c[p],f.L=f.b,b)for(h=0;!a.Wa&&h<e.length&&f.L;h++)a.currentTarget=e[h],d&=Eb(f,e[h],a.type,p,a)&&a.Tb!=p;else for(e=this;!a.Wa&&e&&f.L;e=e.Qb)a.currentTarget=
e,d&=Eb(f,e,a.type,p,a)&&a.Tb!=p;a=Boolean(d)}else a=l;return a};t.d=function(){P.i.d.call(this);var a,b=0,c=a==m;a=!!a;if(this==m)$a(yb,function(d){for(var e=d.length-1;0<=e;e--){var f=d[e];if(c||a==f.capture)O(f.key),b++}});else{var d=ja(this);if(yb[d])for(var d=yb[d],e=d.length-1;0<=e;e--){var f=d[e];if(c||a==f.capture)O(f.key),b++}}this.Qb=m};function Hb(a,b){D.call(this);this.C=a||1;this.pb=b||Ib;this.cc=y(this.Kf,this);this.yc=B()}C(Hb,P);Hb.prototype.enabled=p;var Ib=u.window;t=Hb.prototype;t.ea=m;t.setInterval=function(a){this.C=a;this.ea&&this.enabled?(this.stop(),this.start()):this.ea&&this.stop()};t.Kf=function(){if(this.enabled){var a=B()-this.yc;0<a&&a<0.8*this.C?this.ea=this.pb.setTimeout(this.cc,this.C-a):(this.dispatchEvent(Jb),this.enabled&&(this.ea=this.pb.setTimeout(this.cc,this.C),this.yc=B()))}};
t.start=function(){this.enabled=l;this.ea||(this.ea=this.pb.setTimeout(this.cc,this.C),this.yc=B())};t.stop=function(){this.enabled=p;this.ea&&(this.pb.clearTimeout(this.ea),this.ea=m)};t.d=function(){Hb.i.d.call(this);this.stop();delete this.pb};var Jb="tick";function Kb(a,b,c){D.call(this);this.Ra=a;this.C=b||0;this.la=c;this.ce=y(this.le,this)}C(Kb,D);t=Kb.prototype;t.P=0;t.d=function(){Kb.i.d.call(this);this.stop();delete this.Ra;delete this.la};t.start=function(a){this.stop();var b=this.ce;a=w(a)?a:this.C;ha(b)||(b&&"function"==typeof b.handleEvent?b=y(b.handleEvent,b):g(Error("Invalid listener argument")));this.P=2147483647<a?-1:Ib.setTimeout(b,a||0)};t.stop=function(){this.Fb()&&Ib.clearTimeout(this.P);this.P=0};t.Fb=function(){return 0!=this.P};
t.le=function(){this.P=0;this.Ra&&this.Ra.call(this.la)};function Lb(a,b){D.call(this);this.Ra=a;this.la=b;this.Ia=new Kb(y(this.vf,this),0,this)}C(Lb,D);t=Lb.prototype;t.C=0;t.Fc=0;t.md=p;t.d=function(){this.Ia.u();delete this.Ra;delete this.la;Lb.i.d.call(this)};t.start=function(a,b){this.stop();this.md=p;var c=b||0;this.C=Math.max(a||0,0);this.Fc=0>c?-1:B()+c;this.Ia.start(0>c?this.C:Math.min(this.C,c))};t.stop=function(){this.Ia.stop()};t.Fb=function(){return this.Ia.Fb()};t.Gd=function(){};
t.vf=function(){if(this.Ra.call(this.la))this.md=l,this.Gd();else if(0>this.Fc)this.Ia.start(this.C);else{var a=this.Fc-B();0>=a||this.Ia.start(Math.min(this.C,a))}};var Mb;Mb=function(){return l};var Nb;function Ob(a){a=a.className;return x(a)&&a.match(/\S+/g)||[]}function Pb(a,b){for(var c=Ob(a),d=sb(arguments,1),e=c.length+d.length,f=c,h=0;h<d.length;h++)0<=lb(f,d[h])||f.push(d[h]);a.className=c.join(" ");return c.length==e}function Qb(a,b){var c=Ob(a),d=sb(arguments,1),c=mb(c,function(a){return!(0<=lb(d,a))});a.className=c.join(" ")};function Rb(a,b){this.width=a;this.height=b}t=Rb.prototype;t.clone=function(){return new Rb(this.width,this.height)};t.toString=function(){return"("+this.width+" x "+this.height+")"};t.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};t.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};t.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var Sb=!F||Xa(9),Tb=!H&&!F||F&&Xa(9)||H&&J("1.9.1"),Vb=F&&!J("9"),Wb=F||Ma||I;function Xb(a,b,c){return Math.min(Math.max(a,b),c)};function R(a,b){this.x=w(a)?a:0;this.y=w(b)?b:0}R.prototype.clone=function(){return new R(this.x,this.y)};R.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function S(a){return a?new Yb(T(a)):Nb||(Nb=new Yb)}function Zb(a){return x(a)?document.getElementById(a):a}function $b(a,b,c){return ac(document,a,b,c)}function bc(a,b){var c=b||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):c.getElementsByClassName?c.getElementsByClassName(a):ac(document,"*",a,b)}function cc(a,b){var c=b||document,d=m;return(d=c.querySelectorAll&&c.querySelector?c.querySelector("."+a):bc(a,b)[0])||m}
function ac(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&0<=lb(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a}
function dc(a,b){$a(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in ec?a.setAttribute(ec[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var ec={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function fc(a){return gc(a||window)}
function gc(a){a=a.document;a=hc(a)?a.documentElement:a.body;return new Rb(a.clientWidth,a.clientHeight)}function ic(a){var b=a.document,c=0;if(b){a=gc(a).height;var c=b.body,d=b.documentElement;if(hc(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{var b=d.scrollHeight,e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}}return c}
function jc(a){var b=kc(a);a=a.parentWindow||a.defaultView;return new R(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)}function kc(a){return!I&&hc(a)?a.documentElement:a.body}function lc(a){return a?a.parentWindow||a.defaultView:window}
function mc(a,b){var c=b[0],d=b[1];if(!Sb&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',va(d.name),'"');if(d.type){c.push(' type="',va(d.type),'"');var e={};gb(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(x(d)?c.className=d:fa(d)?Pb.apply(m,[c].concat(d)):dc(c,d));2<b.length&&nc(a,c,b,2);return c}function nc(a,b,c,d){function e(c){c&&b.appendChild(x(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];ga(f)&&!oc(f)?L(pc(f)?rb(f):f,e):e(f)}}
function qc(a){return document.createElement(a)}function rc(a,b,c,d){for(var e=["<tr>"],f=0;f<c;f++)e.push(d?"<td>&nbsp;</td>":"<td></td>");e.push("</tr>");e=e.join("");c=["<table>"];for(f=0;f<b;f++)c.push(e);c.push("</table>");a=a.createElement("DIV");a.innerHTML=c.join("");return a.removeChild(a.firstChild)}
function sc(a,b){var c=a.createElement("div");F?(c.innerHTML="<br>"+b,c.removeChild(c.firstChild)):c.innerHTML=b;if(1==c.childNodes.length)return c.removeChild(c.firstChild);for(var d=a.createDocumentFragment();c.firstChild;)d.appendChild(c.firstChild);return d}function tc(){return hc(document)}function hc(a){return"CSS1Compat"==a.compatMode}
function uc(a){if(1!=a.nodeType)return p;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return p}return l}function vc(a,b){a.appendChild(b)}function wc(a,b){nc(T(a),a,arguments,1)}
function xc(a){for(var b;b=a.firstChild;)a.removeChild(b)}function yc(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)}function zc(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)}function Ac(a,b,c){a.insertBefore(b,a.childNodes[c]||m)}function Bc(a){return a&&a.parentNode?a.parentNode.removeChild(a):m}function Cc(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)}
function Dc(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(p);for(;b=a.firstChild;)c.insertBefore(b,a);return Bc(a)}}function Ec(a){return Tb&&a.children!=j?a.children:mb(a.childNodes,function(a){return 1==a.nodeType})}function Fc(a){return a.firstElementChild!=j?a.firstElementChild:Gc(a.firstChild,l)}function Hc(a){return a.lastElementChild!=j?a.lastElementChild:Gc(a.lastChild,p)}
function Ic(a){return a.nextElementSibling!=j?a.nextElementSibling:Gc(a.nextSibling,l)}function Jc(a){return a.previousElementSibling!=j?a.previousElementSibling:Gc(a.previousSibling,p)}function Gc(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function Kc(a){if(!a)return m;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:m}
function Lc(a){if(!a)return m;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a}function oc(a){return ia(a)&&0<a.nodeType}function Mc(a){return ia(a)&&1==a.nodeType}function Nc(a){return ia(a)&&a.window==a}function Oc(a){if(Wb)return a.parentElement;a=a.parentNode;return Mc(a)?a:m}
function Pc(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function Qc(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(F&&!Xa(9)){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?Rc(a,b):!c&&Pc(e,b)?-1*Sc(a,b):!d&&Pc(f,a)?Sc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=T(a);c=d.createRange();
c.selectNode(a);c.collapse(l);d=d.createRange();d.selectNode(b);d.collapse(l);return c.compareBoundaryPoints(u.Range.START_TO_END,d)}function Sc(a,b){var c=a.parentNode;if(c==b)return-1;for(var d=b;d.parentNode!=c;)d=d.parentNode;return Rc(d,a)}function Rc(a,b){for(var c=b;c=c.previousSibling;)if(c==a)return-1;return 1}
function Tc(a){var b,c=arguments.length;if(c){if(1==c)return arguments[0]}else return m;var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],h=arguments[b];h;)f.unshift(h),h=h.parentNode;d.push(f);e=Math.min(e,f.length)}f=m;for(b=0;b<e;b++){for(var h=d[0][b],k=1;k<c;k++)if(h!=d[k][b])return f;f=h}return f}function T(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function Uc(a){return a.contentDocument||a.contentWindow.document}
function Vc(a){return a.contentWindow||Uc(a).parentWindow||Uc(a).defaultView}function Wc(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else xc(a),a.appendChild(T(a).createTextNode(b))}function Xc(a){if("outerHTML"in a)return a.outerHTML;var b=T(a).createElement("div");b.appendChild(a.cloneNode(l));return b.innerHTML}function Yc(a,b){var c=[];return Zc(a,b,c,l)?c[0]:j}
function $c(a,b){var c=[];Zc(a,b,c,p);return c}function Zc(a,b,c,d){if(a!=m)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||Zc(a,b,c,d))return l;a=a.nextSibling}return p}var ad={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},bd={IMG:" ",BR:"\n"};function cd(a){var b=a.getAttributeNode("tabindex");return b&&b.specified?(a=a.tabIndex,"number"==typeof a&&0<=a&&32768>a):p}function dd(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))}
function ed(a){if(Vb&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];fd(a,b,l);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Vb||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function fd(a,b,c){if(!(a.nodeName in ad))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in bd)b.push(bd[a.nodeName]);else for(a=a.firstChild;a;)fd(a,b,c),a=a.nextSibling}function gd(a){return ed(a).length}function hd(a,b){for(var c=b||T(a).body,d=[];a&&a!=c;){for(var e=a;e=e.previousSibling;)d.unshift(ed(e));a=a.parentNode}return d.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length}
function id(a,b,c){a=[a];for(var d=0,e=m;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in ad))if(3==e.nodeType)var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," "),d=d+f.length;else if(e.nodeName in bd)d+=bd[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);ia(c)&&(c.Wh=e?e.nodeValue.length+b-d-1:0,c.Rh=e);return e}
function pc(a){if(a&&"number"==typeof a.length){if(ia(a))return"function"==typeof a.item||"string"==typeof a.item;if(ha(a))return"function"==typeof a.item}return p}function jd(a,b,c){if(!b&&!c)return m;var d=b?b.toUpperCase():m;return kd(a,function(a){var b;if(b=!d||a.nodeName==d)if(!(b=!c))a=Ob(a),b=0<=lb(a,c);return b},l)}function ld(a,b){return jd(a,m,b)}function kd(a,b,c,d){c||(a=a.parentNode);c=d==m;for(var e=0;a&&(c||e<=d);){if(b(a))return a;a=a.parentNode;e++}return m}
function md(a){try{return a&&a.activeElement}catch(b){}return m}function Yb(a){this.f=a||u.document||document}t=Yb.prototype;t.Db=S;t.kc=ba("f");t.c=function(a){return x(a)?this.f.getElementById(a):a};t.Be=function(a,b,c){return ac(this.f,a,b,c)};t.mc=function(a,b){return bc(a,b||this.f)};t.lc=function(a,b){return cc(a,b||this.f)};t.Gf=dc;t.Re=function(a){return fc(a||this.pc())};t.ze=function(){return ic(this.pc())};t.Ha=function(a,b,c){return mc(this.f,arguments)};t.createElement=function(a){return this.f.createElement(a)};
t.createTextNode=function(a){return this.f.createTextNode(a)};t.he=function(a,b,c){return rc(this.f,a,b,!!c)};t.Xe=function(a){return sc(this.f,a)};t.ye=function(){return this.sc()?"CSS1Compat":"BackCompat"};t.sc=function(){return hc(this.f)};t.pc=function(){return this.f.parentWindow||this.f.defaultView};t.Ae=function(){return kc(this.f)};t.Ma=function(){return jc(this.f)};t.te=function(a){return md(a||this.f)};t.appendChild=vc;t.append=wc;t.canHaveChildren=uc;t.Kd=xc;t.bf=yc;t.af=zc;t.$e=Ac;
t.removeNode=Bc;t.Cf=Cc;t.se=Dc;t.$c=Ec;t.Ce=Fc;t.Fe=Hc;t.Ge=Ic;t.Oe=Jc;t.He=Kc;t.Pe=Lc;t.ff=oc;t.isElement=Mc;t.kf=Nc;t.Ne=Oc;t.contains=Pc;t.fe=Qc;t.oe=Tc;t.Me=T;t.De=Uc;t.Ee=Vc;t.Hf=Wc;t.Le=Xc;t.pe=Yc;t.qe=$c;t.ef=cd;t.Ff=dd;t.Qe=ed;t.Je=gd;t.Ke=hd;t.Ie=id;t.gf=pc;t.we=jd;t.ve=ld;t.ue=kd;/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

The "New" BSD License:

Copyright (c) 2005-2009, The Dojo Foundation
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
function nd(a,b){var c=b||[];a&&c.push(a);return c}var od=I&&"BackCompat"==document.compatMode,pd=document.firstChild.children?"children":"childNodes",qd=p;
function rd(a){function b(){0<=q&&(v.id=c(q,A).replace(/\\/g,""),q=-1);if(0<=r){var a=r==A?m:c(r,A);0>">~+".indexOf(a)?v.A=a:v.Pb=a;r=-1}0<=n&&(v.ba.push(c(n+1,A).replace(/\\/g,"")),n=-1)}function c(b,c){return ua(a.slice(b,c))}a=0<=">~+".indexOf(a.slice(-1))?a+" * ":a+" ";for(var d=[],e=-1,f=-1,h=-1,k=-1,n=-1,q=-1,r=-1,s="",z="",G,A=0,Ub=a.length,v=m,Q=m;s=z,z=a.charAt(A),A<Ub;A++)if("\\"!=s)if(v||(G=A,v={qa:m,Aa:[],sb:[],ba:[],A:m,Pb:m,id:m,oc:function(){return qd?this.xf:this.A}},r=A),0<=e)if("]"==
z){Q.attr?Q.zc=c(h||e+1,A):Q.attr=c(e+1,A);if((e=Q.zc)&&('"'==e.charAt(0)||"'"==e.charAt(0)))Q.zc=e.slice(1,-1);v.sb.push(Q);Q=m;e=h=-1}else"="==z&&(h=0<="|~^$*".indexOf(s)?s:"",Q.type=h+z,Q.attr=c(e+1,A-h.length),h=A+1);else 0<=f?")"==z&&(0<=k&&(Q.value=c(f+1,A)),k=f=-1):"#"==z?(b(),q=A+1):"."==z?(b(),n=A):":"==z?(b(),k=A):"["==z?(b(),e=A,Q={}):"("==z?(0<=k&&(Q={name:c(k+1,A),value:m},v.Aa.push(Q)),f=A):" "==z&&s!=z&&(b(),0<=k&&v.Aa.push({name:c(k+1,A)}),v.td=v.Aa.length||v.sb.length||v.ba.length,
v.Uh=v.qa=c(G,A),v.xf=v.A=v.Pb?m:v.A||"*",v.A&&(v.A=v.A.toUpperCase()),d.length&&d[d.length-1].Pb&&(v.kd=d.pop(),v.qa=v.kd.qa+" "+v.qa),d.push(v),v=m);return d}function sd(a,b){return!a?b:!b?a:function(){return a.apply(window,arguments)&&b.apply(window,arguments)}}function td(a){return 1==a.nodeType}function ud(a,b){return!a?"":"class"==b?a.className||"":"for"==b?a.htmlFor||"":"style"==b?a.style.cssText||"":(qd?a.getAttribute(b):a.getAttribute(b,2))||""}
var vd={"*=":function(a,b){return function(c){return 0<=ud(c,a).indexOf(b)}},"^=":function(a,b){return function(c){return 0==ud(c,a).indexOf(b)}},"$=":function(a,b){return function(c){c=" "+ud(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return 0<=(" "+ud(b,a)+" ").indexOf(c)}},"|=":function(a,b){b=" "+b;return function(c){c=" "+ud(c,a);return c==b||0==c.indexOf(b+"-")}},"=":function(a,b){return function(c){return ud(c,a)==b}}},wd="undefined"==
typeof document.firstChild.nextElementSibling,xd=!wd?"nextElementSibling":"nextSibling",yd=!wd?"previousElementSibling":"previousSibling",zd=wd?td:Mb;function Ad(a){for(;a=a[yd];)if(zd(a))return p;return l}function Bd(a){for(;a=a[xd];)if(zd(a))return p;return l}function Cd(a){var b=a.parentNode,c=0,d=b[pd],e=a._i||-1,f=b._l||-1;if(!d)return-1;d=d.length;if(f==d&&0<=e&&0<=f)return e;b._l=d;e=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[xd])zd(b)&&(b._i=++c,a===b&&(e=c));return e}
function Dd(a){return!(Cd(a)%2)}function Ed(a){return Cd(a)%2}
var Gd={checked:function(){return function(a){return a.checked||a.attributes.checked}},"first-child":function(){return Ad},"last-child":function(){return Bd},"only-child":function(){return function(a){return!Ad(a)||!Bd(a)?p:l}},empty:function(){return function(a){var b=a.childNodes;for(a=a.childNodes.length-1;0<=a;a--){var c=b[a].nodeType;if(1===c||3==c)return p}return l}},contains:function(a,b){var c=b.charAt(0);if('"'==c||"'"==c)b=b.slice(1,-1);return function(a){return 0<=a.innerHTML.indexOf(b)}},
not:function(a,b){var c=rd(b)[0],d={Ja:1};"*"!=c.A&&(d.A=1);c.ba.length||(d.ba=1);var e=Fd(c,d);return function(a){return!e(a)}},"nth-child":function(a,b){if("odd"==b)return Ed;if("even"==b)return Dd;if(-1!=b.indexOf("n")){var c=b.split("n",2),d=c[0]?"-"==c[0]?-1:parseInt(c[0],10):1,e=c[1]?parseInt(c[1],10):0,f=0,h=-1;0<d?0>e?e=e%d&&d+e%d:0<e&&(e>=d&&(f=e-e%d),e%=d):0>d&&(d*=-1,0<e&&(h=e,e%=d));if(0<d)return function(a){a=Cd(a);return a>=f&&(0>h||a<=h)&&a%d==e};b=e}var k=parseInt(b,10);return function(a){return Cd(a)==
k}}},Id=F?function(a){var b=a.toLowerCase();"class"==b&&(a="className");return function(c){return qd?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}};
function Fd(a,b){if(!a)return Mb;b=b||{};var c=m;b.Ja||(c=sd(c,td));b.A||"*"!=a.A&&(c=sd(c,function(b){return b&&b.tagName==a.oc()}));b.ba||L(a.ba,function(a,b){var f=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=sd(c,function(a){return f.test(a.className)});c.count=b});b.Aa||L(a.Aa,function(a){var b=a.name;Gd[b]&&(c=sd(c,Gd[b](b,a.value)))});b.sb||L(a.sb,function(a){var b,f=a.attr;a.type&&vd[a.type]?b=vd[a.type](f,a.zc):f.length&&(b=Id(f));b&&(c=sd(c,b))});b.id||a.id&&(c=sd(c,function(b){return!!b&&b.id==
a.id}));c||"default"in b||(c=Mb);return c}var Jd={};
function Kd(a){var b=Jd[a.qa];if(b)return b;var c=a.kd,c=c?c.Pb:"",d=Fd(a,{Ja:1}),e="*"==a.A,f=document.getElementsByClassName;if(c)if(f={Ja:1},e&&(f.A=1),d=Fd(a,f),"+"==c)var h=d,b=function(a,b,c){for(;a=a[xd];)if(!wd||td(a)){(!c||Ld(a,c))&&h(a)&&b.push(a);break}return b};else if("~"==c)var k=d,b=function(a,b,c){for(a=a[xd];a;){if(zd(a)){if(c&&!Ld(a,c))break;k(a)&&b.push(a)}a=a[xd]}return b};else{if(">"==c)var n=d,n=n||Mb,b=function(a,b,c){for(var d=0,e=a[pd];a=e[d++];)zd(a)&&((!c||Ld(a,c))&&n(a,
d))&&b.push(a);return b}}else if(a.id)d=!a.td&&e?Mb:Fd(a,{Ja:1,id:1}),b=function(b,c){var e=S(b).c(a.id),f;if(f=e&&d(e))if(!(f=9==b.nodeType)){for(f=e.parentNode;f&&f!=b;)f=f.parentNode;f=!!f}if(f)return nd(e,c)};else if(f&&/\{\s*\[native code\]\s*\}/.test(String(f))&&a.ba.length&&!od)var d=Fd(a,{Ja:1,ba:1,id:1}),q=a.ba.join(" "),b=function(a,b){for(var c=nd(0,b),e,f=0,h=a.getElementsByClassName(q);e=h[f++];)d(e,a)&&c.push(e);return c};else!e&&!a.td?b=function(b,c){for(var d=nd(0,c),e,f=0,h=b.getElementsByTagName(a.oc());e=
h[f++];)d.push(e);return d}:(d=Fd(a,{Ja:1,A:1,id:1}),b=function(b,c){for(var e=nd(0,c),f,h=0,k=b.getElementsByTagName(a.oc());f=k[h++];)d(f,b)&&e.push(f);return e});return Jd[a.qa]=b}var Md={},Nd={};function Od(a){var b=rd(ua(a));if(1==b.length){var c=Kd(b[0]);return function(a){if(a=c(a,[]))a.Nb=l;return a}}return function(a){a=nd(a);for(var c,f,h=b.length,k,n,q=0;q<h;q++){n=[];c=b[q];f=a.length-1;0<f&&(k={},n.Nb=l);f=Kd(c);for(var r=0;c=a[r];r++)f(c,n,k);if(!n.length)break;a=n}return n}}
var Pd=!!document.querySelectorAll&&(!I||J("526"));
function Qd(a,b){if(Pd){var c=Nd[a];if(c&&!b)return c}if(c=Md[a])return c;var c=a.charAt(0),d=-1==a.indexOf(" ");0<=a.indexOf("#")&&d&&(b=l);if(Pd&&!b&&-1==">~+".indexOf(c)&&(!F||-1==a.indexOf(":"))&&!(od&&0<=a.indexOf("."))&&-1==a.indexOf(":contains")&&-1==a.indexOf("|=")){var e=0<=">~+".indexOf(a.charAt(a.length-1))?a+" *":a;return Nd[a]=function(b){try{9==b.nodeType||d||g("");var c=b.querySelectorAll(e);F?c.ee=l:c.Nb=l;return c}catch(f){return Qd(a,l)(b)}}}var f=a.split(/\s*,\s*/);return Md[a]=
2>f.length?Od(a):function(a){for(var b=0,c=[],d;d=f[b++];)c=c.concat(Od(d)(a));return c}}var Rd=0,Sd=F?function(a){return qd?a.getAttribute("_uid")||a.setAttribute("_uid",++Rd)||Rd:a.uniqueID}:function(a){return a._uid||(a._uid=++Rd)};function Ld(a,b){if(!b)return 1;var c=Sd(a);return!b[c]?b[c]=1:0}
function Td(a){if(a&&a.Nb)return a;var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(2>a.length)return b;Rd++;if(F&&qd){var c=Rd+"";a[0].setAttribute("_zipIdx",c);for(var d=1,e;e=a[d];d++)a[d].getAttribute("_zipIdx")!=c&&b.push(e),e.setAttribute("_zipIdx",c)}else if(F&&a.ee)try{for(d=1;e=a[d];d++)td(e)&&b.push(e)}catch(f){}else{a[0]&&(a[0]._zipIdx=Rd);for(d=1;e=a[d];d++)a[d]._zipIdx!=Rd&&b.push(e),e._zipIdx=Rd}return b}
function Ud(a,b){if(!a)return[];if(a.constructor==Array)return a;if(!x(a))return[a];if(x(b)&&(b=Zb(b),!b))return[];b=b||document;var c=b.ownerDocument||b.documentElement;qd=b.contentType&&"application/xml"==b.contentType||Ma&&(b.doctype||"[object XMLDocument]"==c.toString())||!!c&&(F?c.xml:b.xmlVersion||c.xmlVersion);return(c=Qd(a)(b))&&c.Nb?c:Td(c)}Ud.Aa=Gd;ca("goog.dom.query",Ud);ca("goog.dom.query.pseudos",Ud.Aa);function Vd(){};function Wd(){this.sa=[];this.total=this.Oa=0;for(var a=[],b=0;64>b;b++)a[b]=0;this.Bc=a;this.Bc[0]=128;this.hash=[];this.Bd=0;this.reset()}C(Wd,Vd);
function Xd(a,b){for(var c=[],d=0,e=0;e<b.length;)c[d++]=b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3],e=4*d;for(d=16;64>d;d++)c[d]=c[d-16]+((c[d-15]>>>7|c[d-15]<<25)^(c[d-15]>>>18|c[d-15]<<14)^c[d-15]>>>3)+c[d-7]+((c[d-2]>>>17|c[d-2]<<15)^(c[d-2]>>>19|c[d-2]<<13)^c[d-2]>>>10)&4294967295;for(var e=a.hash[0],f=a.hash[1],h=a.hash[2],k=a.hash[3],n=a.hash[4],q=a.hash[5],r=a.hash[6],s=a.hash[7],d=0;64>d;d++)var z=((e>>>2|e<<30)^(e>>>13|e<<19)^(e>>>22|e<<10))+(e&f^e&h^f&h)&4294967295,G=s+((n>>>6|n<<26)^(n>>>11|
n<<21)^(n>>>25|n<<7))+(n&q^~n&r)+a.Wd[d]+c[d]&4294967295,s=r,r=q,q=n,n=k+G&4294967295,k=h,h=f,f=e,e=G+z&4294967295;a.hash[0]=a.hash[0]+e&4294967295;a.hash[1]=a.hash[1]+f&4294967295;a.hash[2]=a.hash[2]+h&4294967295;a.hash[3]=a.hash[3]+k&4294967295;a.hash[4]=a.hash[4]+n&4294967295;a.hash[5]=a.hash[5]+q&4294967295;a.hash[6]=a.hash[6]+r&4294967295;a.hash[7]=a.hash[7]+s&4294967295}
Wd.prototype.update=function(a,b){w(b)||(b=a.length);var c=0,d=this.Oa;if(x(a))for(;c<b;)this.sa[d++]=a.charCodeAt(c++),64==d&&(Xd(this,this.sa),d=0);else for(;c<b;)this.sa[d++]=a[c++],64==d&&(Xd(this,this.sa),d=0);this.Oa=d;this.total+=b};
Wd.prototype.ab=function(){var a=[],b=8*this.total;56>this.Oa?this.update(this.Bc,56-this.Oa):this.update(this.Bc,64-(this.Oa-56));for(var c=63;56<=c;c--)this.sa[c]=b&255,b/=256;Xd(this,this.sa);for(c=b=0;c<this.Bd;c++)for(var d=24;0<=d;d-=8)a[b++]=this.hash[c]>>d&255;return a};
Wd.prototype.Wd=[1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,
3600352804,4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298];function Yd(){Wd.call(this)}C(Yd,Wd);Yd.prototype.reset=function(){this.sa=[];this.total=this.Oa=0;this.hash=[1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225];this.Bd=8};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function Zd(a,b){this.Ub=[];this.Dd=a;this.Uc=b||m}t=Zd.prototype;t.ya=p;t.fb=p;t.bc=p;t.ae=p;t.Jc=p;t.dc=0;t.cancel=function(a){if(this.ya)this.lb instanceof Zd&&this.lb.cancel();else{if(this.$){var b=this.$;delete this.$;a?b.cancel(a):(b.dc--,0>=b.dc&&b.cancel())}this.Dd?this.Dd.call(this.Uc,this):this.Jc=l;this.ya||this.La(new $d(this))}};t.Sc=function(a,b){this.bc=p;ae(this,a,b)};function ae(a,b,c){a.ya=l;a.lb=c;a.fb=!b;be(a)}function ce(a){a.ya&&(a.Jc||g(new de(a)),a.Jc=p)}
t.V=function(a){ce(this);ae(this,l,a)};t.La=function(a){ce(this);ae(this,p,a)};function ee(a,b,c,d){a.Ub.push([b,c,d]);a.ya&&be(a)}function fe(a){return ob(a.Ub,function(a){return ha(a[1])})}
function be(a){a.Nc&&(a.ya&&fe(a))&&(u.clearTimeout(a.Nc),delete a.Nc);a.$&&(a.$.dc--,delete a.$);for(var b=a.lb,c=p,d=p;a.Ub.length&&!a.bc;){var e=a.Ub.shift(),f=e[0],h=e[1],e=e[2];if(f=a.fb?h:f)try{var k=f.call(e||a.Uc,b);w(k)&&(a.fb=a.fb&&(k==b||k instanceof Error),a.lb=b=k);b instanceof Zd&&(d=l,a.bc=l)}catch(n){b=n,a.fb=l,fe(a)||(c=l)}}a.lb=b;d&&(ee(b,y(a.Sc,a,l),y(a.Sc,a,p)),b.ae=l);c&&(a.Nc=u.setTimeout(function(){g(b)},0))}function de(a){kb.call(this);this.je=a}C(de,kb);
de.prototype.message="Deferred has already fired";de.prototype.name="AlreadyCalledError";function $d(a){kb.call(this);this.je=a}C($d,kb);$d.prototype.message="Deferred was cancelled";$d.prototype.name="CancelledError";function ge(a,b,c,d,e,f){Zd.call(this,e,f);this.qd=a;this.fc=[];this.Xc=!!b;this.re=!!c;this.ge=!!d;for(b=0;b<a.length;b++)ee(a[b],y(this.dd,this,b,l),y(this.dd,this,b,p));0==a.length&&!this.Xc&&this.V(this.fc)}C(ge,Zd);ge.prototype.Ad=0;ge.prototype.dd=function(a,b,c){this.Ad++;this.fc[a]=[b,c];this.ya||(this.Xc&&b?this.V([a,c]):this.re&&!b?this.La(c):this.Ad==this.qd.length&&this.V(this.fc));this.ge&&!b&&(c=m);return c};ge.prototype.La=function(a){ge.i.La.call(this,a);L(this.qd,function(a){a.cancel()})};function he(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}he.prototype.clone=function(){return new he(this.top,this.right,this.bottom,this.left)};he.prototype.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};he.prototype.contains=function(a){return!this||!a?p:a instanceof he?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom};function je(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}je.prototype.clone=function(){return new je(this.left,this.top,this.width,this.height)};je.prototype.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};
je.prototype.contains=function(a){return a instanceof je?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};function ke(a,b){var c=T(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,m))?c[b]||c.getPropertyValue(b)||"":""}function le(a,b){return ke(a,b)||(a.currentStyle?a.currentStyle[b]:m)||a.style&&a.style[b]}function me(a){var b=a.getBoundingClientRect();F&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function ne(a){if(F&&!Xa(8))return a.offsetParent;var b=T(a),c=le(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=le(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return m}
function oe(a){var b=new R;if(1==a.nodeType){if(a.getBoundingClientRect){var c=me(a);b.x=c.left;b.y=c.top}else{c=S(a).Ma();var d,e=T(a),f=le(a,"position"),h=H&&e.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==f&&(d=e.getBoxObjectFor(a))&&(0>d.screenX||0>d.screenY),k=new R(0,0),n;d=e?T(e):document;n=F&&!Xa(9)&&!S(d).sc()?d.body:d.documentElement;if(a!=n)if(a.getBoundingClientRect)d=me(a),e=S(e).Ma(),k.x=d.left+e.x,k.y=d.top+e.y;else if(e.getBoxObjectFor&&!h)d=e.getBoxObjectFor(a),e=e.getBoxObjectFor(n),
k.x=d.screenX-e.screenX,k.y=d.screenY-e.screenY;else{d=a;do{k.x+=d.offsetLeft;k.y+=d.offsetTop;d!=a&&(k.x+=d.clientLeft||0,k.y+=d.clientTop||0);if(I&&"fixed"==le(d,"position")){k.x+=e.body.scrollLeft;k.y+=e.body.scrollTop;break}d=d.offsetParent}while(d&&d!=a);if(Ma||I&&"absolute"==f)k.y-=e.body.offsetTop;for(d=a;(d=ne(d))&&d!=e.body&&d!=n;)if(k.x-=d.scrollLeft,!Ma||"TR"!=d.tagName)k.y-=d.scrollTop}b.x=k.x-c.x;b.y=k.y-c.y}if(H&&!J(12)){var q;F?q="-ms-transform":I?q="-webkit-transform":Ma?q="-o-transform":
H&&(q="-moz-transform");var r;q&&(r=le(a,q));r||(r=le(a,"transform"));r?(a=r.match(pe),a=!a?new R(0,0):new R(parseFloat(a[1]),parseFloat(a[2]))):a=new R(0,0);b=new R(b.x+a.x,b.y+a.y)}}else q=ha(a.xe),r=a,a.targetTouches?r=a.targetTouches[0]:q&&a.N.targetTouches&&(r=a.N.targetTouches[0]),b.x=r.clientX,b.y=r.clientY;return b}function qe(a){return"rtl"==le(a,"direction")}var re={thin:2,medium:4,thick:6};
function se(a,b){if("none"==(a.currentStyle?a.currentStyle[b+"Style"]:m))return 0;var c=a.currentStyle?a.currentStyle[b+"Width"]:m,d;if(c in re)d=re[c];else if(/^\d+px?$/.test(c))d=parseInt(c,10);else{d=a.style.left;var e=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=c;c=a.style.pixelLeft;a.style.left=d;a.runtimeStyle.left=e;d=c}return d}
function te(a){if(F){var b=se(a,"borderLeft"),c=se(a,"borderRight"),d=se(a,"borderTop");a=se(a,"borderBottom");return new he(d,c,a,b)}b=ke(a,"borderLeftWidth");c=ke(a,"borderRightWidth");d=ke(a,"borderTopWidth");a=ke(a,"borderBottomWidth");return new he(parseFloat(d),parseFloat(c),parseFloat(a),parseFloat(b))}var pe=/matrix\([0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, ([0-9\.\-]+)p?x?, ([0-9\.\-]+)p?x?\)/;function ue(a){D.call(this);this.la=a;this.l=[]}C(ue,D);var ve=[];function U(a,b,c,d,e){fa(c)||(ve[0]=c,c=ve);for(var f=0;f<c.length;f++){var h=N(b,c[f],d||a,e||p,a.la||a);a.l.push(h)}return a}function we(a,b,c,d,e,f){if(fa(c))for(var h=0;h<c.length;h++)we(a,b,c[h],d,e,f);else{a:{d=d||a;f=f||a.la||a;e=!!e;if(b=Cb(b,c,e))for(c=0;c<b.length;c++)if(!b[c].Ba&&b[c].Qa==d&&b[c].capture==e&&b[c].Eb==f){b=b[c];break a}b=m}b&&(b=b.key,O(b),pb(a.l,b))}return a}function xe(a){L(a.l,O);a.l.length=0}
ue.prototype.d=function(){ue.i.d.call(this);xe(this)};ue.prototype.handleEvent=function(){g(Error("EventHandler.handleEvent not implemented"))};function ye(){}ye.ad=function(){return ye.ld?ye.ld:ye.ld=new ye};ye.prototype.tf=0;ye.ad();function ze(a){D.call(this);this.ga=a||S();this.aa=Ae}C(ze,P);ze.prototype.Ye=ye.ad();var Ae=m;t=ze.prototype;t.P=m;t.ma=p;t.g=m;t.aa=m;t.qf=m;t.$=m;t.fa=m;t.vb=m;t.Ud=p;t.c=ba("g");t.mc=function(a){return this.g?this.ga.mc(a,this.g):[]};t.lc=function(a){return this.g?this.ga.lc(a,this.g):m};t.ka=function(){return this.Na||(this.Na=new ue(this))};t.Ic=function(a){this.$&&this.$!=a&&g(Error("Method not supported"));ze.i.Ic.call(this,a)};t.Db=ba("ga");t.Ha=function(){this.g=this.ga.createElement("div")};
function Be(a,b){a.ma&&g(Error("Component already rendered"));if(b&&a.Rc(b)){a.Ud=l;if(!a.ga||a.ga.kc()!=T(b))a.ga=S(b);a.zb(b);a.Ka()}else g(Error("Invalid element to decorate"))}t.Rc=function(){return l};t.zb=aa("g");t.Ka=function(){this.ma=l;Ce(this,function(a){!a.ma&&a.c()&&a.Ka()})};t.eb=function(){Ce(this,function(a){a.ma&&a.eb()});this.Na&&xe(this.Na);this.ma=p};
t.d=function(){ze.i.d.call(this);this.ma&&this.eb();this.Na&&(this.Na.u(),delete this.Na);Ce(this,function(a){a.u()});!this.Ud&&this.g&&Bc(this.g);this.$=this.qf=this.g=this.vb=this.fa=m};t.Pa=function(){this.aa==m&&(this.aa=qe(this.ma?this.g:this.ga.kc().body));return this.aa};function Ce(a,b){a.fa&&L(a.fa,b,j)}
t.removeChild=function(a,b){if(a){var c=x(a)?a:a.P||(a.P=":"+(a.Ye.tf++).toString(36)),d;this.vb&&c?(d=this.vb,d=(c in d?d[c]:j)||m):d=m;a=d;c&&a&&(d=this.vb,c in d&&delete d[c],pb(this.fa,a),b&&(a.eb(),a.g&&Bc(a.g)),c=a,c==m&&g(Error("Unable to set parent component")),c.$=m,ze.i.Ic.call(c,m))}a||g(Error("Child is not in parent component"));return a};t.Kd=function(a){for(var b=[];this.fa&&0!=this.fa.length;)b.push(this.removeChild(this.fa?this.fa[0]||m:m,a));return b};function De(a){ze.call(this,a);this.wb=-1;this.mb=p;this.Vc=Ee;this.If=[]}C(De,ze);t=De.prototype;t.Md=0;t.Rc=function(a){return"TABLE"==a.tagName};t.Ka=function(){De.i.Ka.call(this);var a=this.c().tHead.rows[this.Md];U(this.ka(),a,"click",this.Jf)};t.Jf=function(a){a=jd(a.target,"TH").cellIndex;var b=a==this.wb?!this.mb:p;this.dispatchEvent("beforesort")&&this.sort(a,b)&&this.dispatchEvent("sort")};
t.sort=function(a,b){var c=this.If[a]||this.Vc;if(c===Fe)return p;var d=this.c(),e=d.tBodies[0],f=e.rows,h=d.tHead.rows[this.Md].cells;0<=this.wb&&Qb(h[this.wb],this.mb?"goog-tablesorter-sorted-reverse":"goog-tablesorter-sorted");this.mb=!!b;for(var h=h[a],k=[],n=0,q=f.length;n<q;n++){var r=f[n],s=ed(r.cells[a]);k.push([s,r])}for(var z=this.mb?-1:1,f=0;f<k.length;f++)k[f]={index:f,value:k[f]};var G=function(a,b){return c(a[0],b[0])*z}||tb;K.sort.call(k,function(a,b){return G(a.value,b.value)||a.index-
b.index}||tb);for(f=0;f<k.length;f++)k[f]=k[f].value;d.removeChild(e);for(n=0;n<q;n++)e.appendChild(k[n][1]);d.insertBefore(e,d.tBodies[0]||m);this.wb=a;Pb(h,this.mb?"goog-tablesorter-sorted-reverse":"goog-tablesorter-sorted");return l};var Fe;Fe=function(){g(Error("no sort"))};function Ee(a,b){return parseFloat(a)-parseFloat(b)};function Ge(a,b,c,d,e){if(!F&&(!I||!J("525")))return l;if(Fa&&e)return He(a);if(e&&!d||!c&&(17==b||18==b||Fa&&91==b))return p;if(I&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return p}if(F&&d&&b==a)return p;switch(a){case 13:return!(F&&Xa(9));case 27:return!I}return He(a)}
function He(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||I&&0==a)return l;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return l;default:return p}}function Ie(a){switch(a){case 61:return 187;case 59:return 186;case 224:return 91;case 0:return 224;default:return a}};function Je(a,b){D.call(this);a&&(this.Jb&&this.detach(),this.g=a,this.Ib=N(this.g,"keypress",this,b),this.uc=N(this.g,"keydown",this.rc,b,this),this.Jb=N(this.g,"keyup",this.Se,b,this))}C(Je,P);t=Je.prototype;t.g=m;t.Ib=m;t.uc=m;t.Jb=m;t.D=-1;t.oa=-1;t.ac=p;
var Ke={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},Le={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},Me=F||I&&J("525"),Ne=Fa&&H;t=Je.prototype;
t.rc=function(a){if(I&&(17==this.D&&!a.ctrlKey||18==this.D&&!a.altKey||Fa&&91==this.D&&!a.metaKey))this.oa=this.D=-1;-1==this.D&&(a.ctrlKey&&17!=a.keyCode?this.D=17:a.altKey&&18!=a.keyCode?this.D=18:a.metaKey&&91!=a.keyCode&&(this.D=91));Me&&!Ge(a.keyCode,this.D,a.shiftKey,a.ctrlKey,a.altKey)?this.handleEvent(a):(this.oa=H?Ie(a.keyCode):a.keyCode,Ne&&(this.ac=a.altKey))};t.Se=function(a){this.oa=this.D=-1;this.ac=a.altKey};
t.handleEvent=function(a){var b=a.N,c,d,e=b.altKey;F&&"keypress"==a.type?(c=this.oa,d=13!=c&&27!=c?b.keyCode:0):I&&"keypress"==a.type?(c=this.oa,d=0<=b.charCode&&63232>b.charCode&&He(c)?b.charCode:0):Ma?(c=this.oa,d=He(c)?b.keyCode:0):(c=b.keyCode||this.oa,d=b.charCode||0,Ne&&(e=this.ac),Fa&&(63==d&&224==c)&&(c=191));var f=c,h=b.keyIdentifier;c?63232<=c&&c in Ke?f=Ke[c]:25==c&&a.shiftKey&&(f=9):h&&h in Le&&(f=Le[h]);a=f==this.D;this.D=f;b=new Oe(f,d,a,b);b.altKey=e;this.dispatchEvent(b)};t.c=ba("g");
t.detach=function(){this.Ib&&(O(this.Ib),O(this.uc),O(this.Jb),this.Jb=this.uc=this.Ib=m);this.g=m;this.oa=this.D=-1};t.d=function(){Je.i.d.call(this);this.detach()};function Oe(a,b,c,d){d&&this.o(d,j);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}C(Oe,vb);function Pe(a){var b=a.offsetLeft,c=a.offsetParent;!c&&"fixed"==le(a,"position")&&(c=T(a).documentElement);if(!c)return b;if(H)var d=te(c),b=b+d.left;else Xa(8)&&(d=te(c),b-=d.left);return qe(c)?c.clientWidth-(b+a.offsetWidth):b};function Qe(a,b,c){D.call(this);this.target=a;this.handle=b||a;this.pd=c||new je(NaN,NaN,NaN,NaN);this.f=T(a);this.W=new ue(this);N(this.handle,["touchstart","mousedown"],this.Nd,p,this)}C(Qe,P);var Re=F||H&&J("1.9.3");t=Qe.prototype;t.clientX=0;t.clientY=0;t.screenX=0;t.screenY=0;t.Od=0;t.Pd=0;t.va=0;t.wa=0;t.ic=l;t.xa=p;t.hd=0;t.rf=0;t.Ze=p;t.Da=p;t.ha=aa("Da");t.ka=ba("W");
t.d=function(){Qe.i.d.call(this);Bb(this.handle,["touchstart","mousedown"],this.Nd,p,this);xe(this.W);Re&&this.f.releaseCapture();this.W=this.handle=this.target=m};function Se(a){w(a.aa)||(a.aa=qe(a.target));return a.aa}
t.Nd=function(a){var b="mousedown"==a.type;if(this.ic&&!this.xa&&(!b||(hb?0==a.N.button:"click"==a.type||a.N.button&wb[0])&&(!I||!Fa||!a.ctrlKey))){Te(a);if(0==this.hd)if(this.dispatchEvent(new Ue("start",this,a.clientX,a.clientY,a)))this.xa=l,a.preventDefault();else return;else a.preventDefault();var b=this.f,c=b.documentElement,d=!Re;U(this.W,b,["touchmove","mousemove"],this.Ve,d);U(this.W,b,["touchend","mouseup"],this.Ab,d);Re?(c.setCapture(p),U(this.W,c,"losecapture",this.Ab)):U(this.W,lc(b),
"blur",this.Ab);F&&this.Ze&&U(this.W,b,"dragstart",ra);this.Ef&&U(this.W,this.Ef,"scroll",this.uf,d);this.clientX=this.Od=a.clientX;this.clientY=this.Pd=a.clientY;this.screenX=a.screenX;this.screenY=a.screenY;this.va=this.Da?Pe(this.target):this.target.offsetLeft;this.wa=this.target.offsetTop;this.Cc=S(this.f).Ma();this.rf=B()}else this.dispatchEvent("earlycancel")};
t.Ab=function(a,b){xe(this.W);Re&&this.f.releaseCapture();if(this.xa){Te(a);this.xa=p;var c=Ve(this,this.va),d=We(this,this.wa);this.dispatchEvent(new Ue("end",this,a.clientX,a.clientY,a,c,d,b||"touchcancel"==a.type))}else this.dispatchEvent("earlycancel");("touchend"==a.type||"touchcancel"==a.type)&&a.preventDefault()};
function Te(a){var b=a.type;"touchstart"==b||"touchmove"==b?a.o(a.N.targetTouches[0],a.currentTarget):("touchend"==b||"touchcancel"==b)&&a.o(a.N.changedTouches[0],a.currentTarget)}
t.Ve=function(a){if(this.ic){Te(a);var b=(this.Da&&Se(this)?-1:1)*(a.clientX-this.clientX),c=a.clientY-this.clientY;this.clientX=a.clientX;this.clientY=a.clientY;this.screenX=a.screenX;this.screenY=a.screenY;if(!this.xa){var d=this.Od-this.clientX,e=this.Pd-this.clientY;if(d*d+e*e>this.hd)if(this.dispatchEvent(new Ue("start",this,a.clientX,a.clientY,a)))this.xa=l;else{this.gc||this.Ab(a);return}}c=Xe(this,b,c);b=c.x;c=c.y;this.xa&&this.dispatchEvent(new Ue("beforedrag",this,a.clientX,a.clientY,a,
b,c))&&(Ye(this,a,b,c),a.preventDefault())}};function Xe(a,b,c){var d=S(a.f).Ma();b+=d.x-a.Cc.x;c+=d.y-a.Cc.y;a.Cc=d;a.va+=b;a.wa+=c;b=Ve(a,a.va);a=We(a,a.wa);return new R(b,a)}t.uf=function(a){var b=Xe(this,0,0);a.clientX=this.clientX;a.clientY=this.clientY;Ye(this,a,b.x,b.y)};function Ye(a,b,c,d){a.ec(c,d);a.dispatchEvent(new Ue("drag",a,b.clientX,b.clientY,b,c,d))}
function Ve(a,b){var c=a.pd,d=!isNaN(c.left)?c.left:m,c=!isNaN(c.width)?c.width:0;return Math.min(d!=m?d+c:Infinity,Math.max(d!=m?d:-Infinity,b))}function We(a,b){var c=a.pd,d=!isNaN(c.top)?c.top:m,c=!isNaN(c.height)?c.height:0;return Math.min(d!=m?d+c:Infinity,Math.max(d!=m?d:-Infinity,b))}t.ec=function(a,b){this.Da&&Se(this)?this.target.style.right=a+"px":this.target.style.left=a+"px";this.target.style.top=b+"px"};
function Ue(a,b,c,d,e,f,h,k){E.call(this,a);this.clientX=c;this.clientY=d;this.Bh=e;this.left=w(f)?f:b.va;this.top=w(h)?h:b.wa;this.hc=b;this.Gh=!!k}C(Ue,E);var eb={},Ze=m;function $e(a){a=ja(a);delete eb[a];db()&&Ze&&Ze.stop()}function af(){Ze||(Ze=new Kb(function(){var a=B();$a(eb,function(c){bf(c,a)});db()||af()},20));var a=Ze;a.Fb()||a.start()};function cf(){D.call(this);this.q=df;this.cb=this.startTime=m}C(cf,P);var df=0;cf.prototype.m=function(){return 1==this.q};cf.prototype.Ob=function(){this.B("begin")};cf.prototype.Ua=function(){this.B("end")};cf.prototype.B=function(a){this.dispatchEvent(a)};function ef(a,b,c,d){cf.call(this);(!fa(a)||!fa(b))&&g(Error("Start and end parameters must be arrays"));a.length!=b.length&&g(Error("Start and end points must be the same length"));this.ob=a;this.ne=b;this.duration=c;this.Pc=d;this.coords=[];this.Da=p}C(ef,cf);t=ef.prototype;t.ha=aa("Da");t.Zc=0;t.K=0;t.wc=m;
t.play=function(a){if(a||this.q==df)this.K=0,this.coords=this.ob;else if(this.m())return p;$e(this);this.startTime=a=B();-1==this.q&&(this.startTime-=this.duration*this.K);this.cb=this.startTime+this.duration;this.wc=this.startTime;this.K||this.Ob();this.B("play");-1==this.q&&this.B("resume");this.q=1;var b=ja(this);b in eb||(eb[b]=this);af();bf(this,a);return l};t.stop=function(a){$e(this);this.q=df;a&&(this.K=1);ff(this,this.K);this.B("stop");this.Ua()};
t.d=function(){this.q==df||this.stop(p);this.B("destroy");ef.i.d.call(this)};function bf(a,b){a.K=(b-a.startTime)/(a.cb-a.startTime);1<=a.K&&(a.K=1);a.Zc=1E3/(b-a.wc);a.wc=b;ff(a,a.K);1==a.K?(a.q=df,$e(a),a.B("finish"),a.Ua()):a.m()&&a.Ac()}function ff(a,b){ha(a.Pc)&&(b=a.Pc(b));a.coords=Array(a.ob.length);for(var c=0;c<a.ob.length;c++)a.coords[c]=(a.ne[c]-a.ob[c])*b+a.ob[c]}t.Ac=function(){this.B("animate")};t.B=function(a){this.dispatchEvent(new gf(a,this))};
function gf(a,b){E.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.bi=b.coords[2];this.duration=b.duration;this.K=b.K;this.Kh=b.Zc;this.state=b.q;this.yh=b}C(gf,E);function V(a,b,c,d,e){ef.call(this,b,c,d,e);this.element=a}C(V,ef);t=V.prototype;t.Za=da;t.Pa=function(){w(this.aa)||(this.aa=qe(this.element));return this.aa};t.Ac=function(){this.Za();V.i.Ac.call(this)};t.Ua=function(){this.Za();V.i.Ua.call(this)};t.Ob=function(){this.Za();V.i.Ob.call(this)};function hf(a,b,c,d,e){(2!=b.length||2!=c.length)&&g(Error("Start and end points must be 2D"));V.apply(this,arguments)}C(hf,V);
hf.prototype.Za=function(){var a=this.Da&&this.Pa()?"right":"left";this.element.style[a]=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};function jf(a,b,c,d,e){V.call(this,a,[b],[c],d,e)}C(jf,V);jf.prototype.Za=function(){this.element.style.width=Math.round(this.coords[0])+"px"};function kf(a,b,c,d,e){V.call(this,a,[b],[c],d,e)}C(kf,V);kf.prototype.Za=function(){this.element.style.height=Math.round(this.coords[0])+"px"};function mf(){cf.call(this);this.da=[]}C(mf,cf);mf.prototype.add=function(a){0<=lb(this.da,a)||(this.da.push(a),N(a,"finish",this.Cd,p,this))};mf.prototype.remove=function(a){pb(this.da,a)&&Bb(a,"finish",this.Cd,p,this)};mf.prototype.d=function(){L(this.da,function(a){a.u()});this.da.length=0;mf.i.d.call(this)};function nf(){mf.call(this);this.jc=0}C(nf,mf);
nf.prototype.play=function(a){if(0==this.da.length)return p;if(a||this.q==df)this.jc=0,this.Ob();else if(this.m())return p;this.B("play");-1==this.q&&this.B("resume");var b=-1==this.q&&!a;this.startTime=B();this.cb=m;this.q=1;L(this.da,function(c){(!b||-1==c.q)&&c.play(a)});return l};nf.prototype.stop=function(a){L(this.da,function(b){b.q==df||b.stop(a)});this.q=df;this.cb=B();this.B("stop");this.Ua()};
nf.prototype.Cd=function(){this.jc++;this.jc==this.da.length&&(this.cb=B(),this.q=df,this.B("finish"),this.Ua())};var of={Nf:"activedescendant",Sf:"atomic",Tf:"autocomplete",Vf:"busy",Xf:"checked",ag:"controls",bg:"describedby",eg:"disabled",gg:"dropeffect",hg:"expanded",ig:"flowto",kg:"grabbed",og:"haspopup",qg:"hidden",sg:"invalid",tg:"label",ug:"labelledby",vg:"level",Ag:"live",Lg:"multiline",Mg:"multiselectable",Qg:"orientation",Rg:"owns",Sg:"posinset",Ug:"pressed",Yg:"readonly",$g:"relevant",ah:"required",hh:"selected",jh:"setsize",kh:"sort",Yd:"valuemax",Zd:"valuemin",$d:"valuenow",xh:"valuetext"},pf={Of:"alert",
Pf:"alertdialog",Qf:"application",Rf:"article",Uf:"banner",Vd:"button",Wf:"checkbox",Yf:"columnheader",Zf:"combobox",$f:"complementary",cg:"dialog",dg:"directory",fg:"document",jg:"form",lg:"grid",mg:"gridcell",ng:"group",pg:"heading",rg:"img",wg:"link",xg:"list",yg:"listbox",zg:"listitem",Bg:"log",Cg:"main",Dg:"marquee",Eg:"math",Gg:"menu",Hg:"menubar",Ig:"menuitem",Jg:"menuitemcheckbox",Kg:"menuitemradio",Ng:"navigation",Og:"note",Pg:"option",Tg:"presentation",Vg:"progressbar",Wg:"radio",Xg:"radiogroup",
Zg:"region",bh:"row",dh:"rowgroup",eh:"rowheader",fh:"scrollbar",gh:"search",ih:"separator",Xd:"slider",lh:"spinbutton",mh:"status",nh:"tab",oh:"tablist",ph:"tabpanel",qh:"textbox",rh:"timer",sh:"toolbar",th:"tooltip",uh:"tree",vh:"treegrid",wh:"treeitem"};function qf(a){D.call(this);this.g=a;a=Mc(this.g)?this.g:this.g?this.g.body:m;this.jf=!!a&&qe(a);this.rd=N(this.g,H?"DOMMouseScroll":"mousewheel",this)}C(qf,P);
qf.prototype.handleEvent=function(a){var b=0,c=0,d=0;a=a.N;if("mousewheel"==a.type){c=1;if(F||I&&(Ga||J("532.0")))c=40;d=rf(-a.wheelDelta,c);w(a.wheelDeltaX)?(b=rf(-a.wheelDeltaX,c),c=rf(-a.wheelDeltaY,c)):c=d}else d=a.detail,100<d?d=3:-100>d&&(d=-3),w(a.axis)&&a.axis===a.HORIZONTAL_AXIS?b=d:c=d;"number"==typeof this.ud&&(b=Xb(b,-this.ud,this.ud));"number"==typeof this.vd&&(c=Xb(c,-this.vd,this.vd));this.jf&&(b=-b);b=new sf(d,a,b,c);this.dispatchEvent(b)};
function rf(a,b){return I&&(Fa||Ha)&&0!=a%b?a:a/b}qf.prototype.d=function(){qf.i.d.call(this);O(this.rd);delete this.rd};function sf(a,b,c,d){b&&this.o(b,j);this.type="mousewheel";this.detail=a;this.va=c;this.wa=d}C(sf,vb);function tf(){D.call(this)}C(tf,P);t=tf.prototype;t.Ea=0;t.Q=0;t.J=100;t.v=0;t.Ca=1;t.Y=p;t.Ta=p;t.Ya=function(a){a=uf(this,a);this.Ea!=a&&(this.Ea=a+this.v>this.J?this.J-this.v:a<this.Q?this.Q:a,!this.Y&&!this.Ta&&this.dispatchEvent("change"))};t.s=function(){return uf(this,this.Ea)};t.nb=function(a){a=uf(this,a);this.v!=a&&(this.v=0>a?0:this.Ea+a>this.J?this.J-this.Ea:a,!this.Y&&!this.Ta&&this.dispatchEvent("change"))};t.ja=function(){return this.Ca==m?this.v:Math.round(this.v/this.Ca)*this.Ca};
t.Hc=function(a){if(this.Q!=a){var b=this.Y;this.Y=l;this.Q=a;a+this.v>this.J&&(this.v=this.J-this.Q);a>this.Ea&&this.Ya(a);a>this.J&&(this.v=0,this.Vb(a),this.Ya(a));this.Y=b;!this.Y&&!this.Ta&&this.dispatchEvent("change")}};t.n=function(){return uf(this,this.Q)};t.Vb=function(a){a=uf(this,a);if(this.J!=a){var b=this.Y;this.Y=l;this.J=a;a<this.Ea+this.v&&this.Ya(a-this.v);a<this.Q&&(this.v=0,this.Hc(a),this.Ya(this.J));a<this.Q+this.v&&(this.v=this.J-this.Q);this.Y=b;!this.Y&&!this.Ta&&this.dispatchEvent("change")}};
t.r=function(){return uf(this,this.J)};t.nc=ba("Ca");function uf(a,b){return a.Ca==m?b:a.Q+Math.round((b-a.Q)/a.Ca)*a.Ca};function vf(a){ze.call(this,a);this.Qc=m;this.a=new tf;N(this.a,"change",this.ed,p,this)}C(vf,ze);var xf="dragvaluestart_"+Gb++,yf="dragvalueend_"+Gb++,zf="dragextentstart_"+Gb++,Af="dragextentend_"+Gb++,Bf="dragstart_"+Gb++,Cf="dragend_"+Gb++;t=vf.prototype;t.S="horizontal";t.Gb=p;t.xd=p;t.U=10;t.jb=0;t.tc=l;t.ic=l;t.H=p;t.Ha=function(){vf.i.Ha.call(this);var a=this.Db().Ha("div",Df(this.S));this.zb(a)};
t.zb=function(a){vf.i.zb.call(this,a);Pb(a,Df(this.S));a=this.c();var b=$b(m,"goog-slider-thumb",a)[0];b||(b=this.Db().Ha("div","goog-slider-thumb"),b.setAttribute("role",pf.Vd),a.appendChild(b));this.e=this.G=b;this.c().setAttribute("role",pf.Xd);Ef(this)};
t.Ka=function(){vf.i.Ka.call(this);this.T=new Qe(this.e);this.ia=new Qe(this.G);this.T.ha(this.H);this.ia.ha(this.H);this.T.ec=this.ia.ec=da;this.gb=new Je(this.c());U(U(U(U(U(U(this.ka(),this.T,"beforedrag",this.cd),this.ia,"beforedrag",this.cd),this.T,["start","end"],this.fd),this.ia,["start","end"],this.fd),this.gb,"key",this.rc),this.c(),"mousedown",this.Te);this.tc&&Ff(this);this.c().tabIndex=0;Gf(this)};t.eb=function(){vf.i.eb.call(this);qa(this.T,this.ia,this.gb,this.Sa)};
t.cd=function(a){var b=a.hc==this.T?this.e:this.G,c;"vertical"==this.S?(c=this.c().clientHeight-b.offsetHeight,c=(c-a.top)/c*(this.r()-this.n())+this.n()):(c=this.c().clientWidth-b.offsetWidth,c=a.left/c*(this.r()-this.n())+this.n());c=a.hc==this.T?Math.min(Math.max(c,this.n()),this.s()+this.ja()):Math.min(Math.max(c,this.s()),this.r());Hf(this,b,c)};
t.fd=function(a){var b="start"==a.type,c=this.c();b?Pb(c,"goog-slider-dragging"):Qb(c,"goog-slider-dragging");c=a.target.handle;b?Pb(c,"goog-slider-thumb-dragging"):Qb(c,"goog-slider-thumb-dragging");a=a.hc==this.T;b?(this.dispatchEvent(Bf),this.dispatchEvent(a?xf:zf)):(this.dispatchEvent(Cf),this.dispatchEvent(a?yf:Af))};
t.rc=function(a){var b=l;switch(a.keyCode){case 36:If(this,this.n());break;case 35:If(this,this.r());break;case 33:Jf(this,this.U);break;case 34:Jf(this,-this.U);break;case 37:var c=this.H&&this.Pa()?1:-1;Jf(this,a.shiftKey?c*this.U:c*this.qb);break;case 40:Jf(this,a.shiftKey?-this.U:-this.qb);break;case 39:c=this.H&&this.Pa()?-1:1;Jf(this,a.shiftKey?c*this.U:c*this.qb);break;case 38:Jf(this,a.shiftKey?this.U:this.qb);break;default:b=p}b&&a.preventDefault()};
t.Te=function(a){this.c().focus&&this.c().focus();var b=a.target;!Pc(this.e,b)&&!Pc(this.G,b)&&(this.xd?If(this,Kf(this,a)):(this.Kc(a),this.M=Lf(this,Kf(this,a)),this.jd="vertical"==this.S?this.Lb<this.M.offsetTop:this.Lb>Mf(this,this.M)+this.M.offsetWidth,a=T(this.c()),U(U(this.ka(),a,"mouseup",this.Qd,l),this.c(),"mousemove",this.Kc),this.na||(this.na=new Hb(200),U(this.ka(),this.na,Jb,this.gd)),this.gd(),this.na.start()))};t.Ue=function(a){Jf(this,(0<a.detail?-1:1)*this.qb);a.preventDefault()};
t.gd=function(){var a;if("vertical"==this.S){var b=this.Lb,c=this.M.offsetTop;this.jd?b<c&&(a=Nf(this,this.M)+this.U):b>c+this.M.offsetHeight&&(a=Nf(this,this.M)-this.U)}else b=this.Lb,c=Mf(this,this.M),this.jd?b>c+this.M.offsetWidth&&(a=Nf(this,this.M)+this.U):b<c&&(a=Nf(this,this.M)-this.U);w(a)&&Hf(this,this.M,a)};t.Qd=function(){this.na&&this.na.stop();var a=T(this.c());we(we(this.ka(),a,"mouseup",this.Qd,l),this.c(),"mousemove",this.Kc)};
function Of(a,b){var c,d=a.c();c=oe(b);d=oe(d);c=new R(c.x-d.x,c.y-d.y);return"vertical"==a.S?c.y:a.H&&a.Pa()?a.c().clientWidth-c.x:c.x}t.Kc=function(a){this.Lb=Of(this,a)};function Kf(a,b){var c=a.n(),d=a.r();if("vertical"==a.S){var e=a.e.offsetHeight,f=a.c().clientHeight-e,e=Of(a,b)-e/2;return(d-c)*(f-e)/f+c}e=a.e.offsetWidth;f=a.c().clientWidth-e;e=Of(a,b)-e/2;return(d-c)*e/f+c}
function Nf(a,b){if(b==a.e)return a.a.s();if(b==a.G)return a.a.s()+a.a.ja();g(Error("Illegal thumb element. Neither minThumb nor maxThumb"))}function Jf(a,b){var c=Nf(a,a.e)+b,d=Nf(a,a.G)+b,c=Xb(c,a.n(),a.r()-a.jb),d=Xb(d,a.n()+a.jb,a.r());Pf(a,c,d-c)}function Hf(a,b,c){var d=m;b==a.G&&(c<=a.a.r()&&c>=a.a.s()+a.jb)&&(d=c-a.a.s());var e=d||a.a.ja();b==a.e&&(c>=a.n()&&c<=a.a.s()+e-a.jb)&&(b=e-(c-a.a.s()),uf(a.a,c)+uf(a.a,b)==uf(a.a,c+b)&&(Pf(a,c,b),d=m));d!=m&&a.a.nb(d)}
function Pf(a,b,c){a.n()<=b&&(b<=a.r()-c&&a.jb<=c&&c<=a.r()-b)&&!(b==a.s()&&c==a.ja())&&(a.a.Ta=l,a.a.nb(0),a.a.Ya(b),a.a.nb(c),a.a.Ta=p,a.ed())}t.n=function(){return this.a.n()};t.Hc=function(a){this.a.Hc(a)};t.r=function(){return this.a.r()};t.Vb=function(a){this.a.Vb(a)};function Lf(a,b){return b<=a.a.s()+a.a.ja()/2?a.e:a.G}t.ed=function(){Gf(this);Ef(this);this.dispatchEvent("change")};
function Gf(a){if(a.e&&!a.Gb){var b=Qf(a,Nf(a,a.e)),c=Qf(a,Nf(a,a.G));if("vertical"==a.S)a.e.style.top=b.y+"px",a.G.style.top=c.y+"px",a.t&&(b=Rf(c.y,b.y,a.e.offsetHeight),a.t.style.top=b.offset+"px",a.t.style.height=b.size+"px");else{var d=a.H&&a.Pa()?"right":"left";a.e.style[d]=b.x+"px";a.G.style[d]=c.x+"px";a.t&&(b=Rf(b.x,c.x,a.e.offsetWidth),a.t.style[d]=b.offset+"px",a.t.style.width=b.size+"px")}}}function Rf(a,b,c){var d=Math.ceil(c/2);return{offset:a+d,size:Math.max(b-a+c-2*d,0)}}
function Qf(a,b){var c=new R;if(a.e){var d=a.n(),e=a.r(),d=b==d&&d==e?0:(b-d)/(e-d);"vertical"==a.S?(e=a.e.offsetHeight,e=a.c().clientHeight-e,d=Math.round(d*e),c.x=Mf(a,a.e),c.y=e-d):(e=a.c().clientWidth-a.e.offsetWidth,d=Math.round(d*e),c.x=d,c.y=a.e.offsetTop)}return c}
function If(a,b){b=Xb(b,a.n(),a.r());a.Gb&&a.yb.stop(l);var c=new nf,d,e=Lf(a,b),f=a.s(),h=a.ja(),k=Nf(a,e),n=Qf(a,k);d=a.nc();Math.abs(b-k)<d&&(b=Xb(k+(b>k?d:-d),a.n(),a.r()));Hf(a,e,b);k=Qf(a,Nf(a,e));d="vertical"==a.S?[Mf(a,e),k.y]:[k.x,e.offsetTop];n=new hf(e,[n.x,n.y],d,100);n.ha(a.H);c.add(n);if(a.t){var n=Qf(a,f),q=Qf(a,f+h),h=n;d=q;e==a.e?h=k:d=k;"vertical"==a.S?(e=Rf(q.y,n.y,a.e.offsetHeight),h=Rf(d.y,h.y,a.e.offsetHeight),k=new hf(a.t,[Mf(a,a.t),e.offset],[Mf(a,a.t),h.offset],100),e=new kf(a.t,
e.size,h.size,100)):(e=Rf(n.x,q.x,a.e.offsetWidth),h=Rf(h.x,d.x,a.e.offsetWidth),k=new hf(a.t,[e.offset,a.t.offsetTop],[h.offset,a.t.offsetTop],100),e=new jf(a.t,e.size,h.size,100));k.ha(a.H);e.ha(a.H);c.add(k);c.add(e)}a.Qc&&(f=a.Qc.Ch(f,b,100),L(f,function(a){c.add(a)}));a.yb=c;U(a.ka(),c,"end",a.me);a.Gb=l;c.play(p)}t.me=function(){this.Gb=p};
t.d=function(){vf.i.d.call(this);this.na&&this.na.u();delete this.na;this.yb&&this.yb.u();delete this.yb;delete this.e;delete this.G;this.t&&delete this.t;this.a.u();delete this.a;this.gb&&(this.gb.u(),delete this.gb);this.Sa&&(this.Sa.u(),delete this.Sa);this.T&&(this.T.u(),delete this.T);this.ia&&(this.ia.u(),delete this.ia)};t.qb=1;t.nc=function(){return this.a.nc()};t.s=function(){return this.a.s()};t.Ya=function(a){Hf(this,this.e,a)};t.ja=function(){return this.a.ja()};
t.nb=function(a){Hf(this,this.G,this.a.s()+a)};function Ef(a){var b=a.c();if(b){var c=a.n();b.setAttribute("aria-"+of.Zd,c);c=a.r();b.setAttribute("aria-"+of.Yd,c);a=a.s();b.setAttribute("aria-"+of.$d,a)}}function Ff(a){a.Sa||(a.Sa=new qf(a.c()));U(a.ka(),a.Sa,"mousewheel",a.Ue)}function Mf(a,b){return a.H?Pe(b):b.offsetLeft};function Sf(a){vf.call(this,a);this.a.nb(0)}C(Sf,vf);function Df(a){return"vertical"==a?"goog-slider-vertical":"goog-slider-horizontal"};function Tf(a,b,c){this.O=a;this.tb=c||16;this.od=Array(this.tb);this.vc=Array(this.tb);a=b;a.length>this.tb&&(this.O.update(a),a=this.O.ab());for(c=0;c<this.tb;c++)b=c<a.length?a[c]:0,this.od[c]=b^92,this.vc[c]=b^54;this.O.update(this.vc)}C(Tf,Vd);Tf.prototype.reset=function(){this.O.reset();this.O.update(this.vc)};Tf.prototype.update=function(a,b){this.O.update(a,b)};Tf.prototype.ab=function(){var a=this.O.ab();this.O.reset();this.O.update(this.od);this.O.update(a);return this.O.ab()};function Uf(a){this.f=a}var Vf=/\s*;\s*/;t=Uf.prototype;t.set=function(a,b,c,d,e,f){/[;=\s]/.test(a)&&g(Error('Invalid cookie name "'+a+'"'));/[;\r\n]/.test(b)&&g(Error('Invalid cookie value "'+b+'"'));w(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(B()+1E3*c)).toUTCString();this.f.cookie=a+"="+b+e+d+c+f};
t.get=function(a,b){for(var c=a+"=",d=(this.f.cookie||"").split(Vf),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};t.remove=function(a,b,c){var d=this.ta(a);this.set(a,"",0,b,c);return d};t.za=function(){return Wf(this).keys};t.X=function(){return Wf(this).values};t.ta=function(a){return w(this.get(a))};
function Wf(a){a=(a.f.cookie||"").split(Vf);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}}var Xf=new Uf(document);Xf.Fg=3950;var Yf=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function Zf(a){if("function"==typeof a.X)return a.X();if(x(a))return a.split("");if(ga(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return ab(a)};function $f(a,b){this.ca={};this.l=[];var c=arguments.length;if(1<c){c%2&&g(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof $f?(c=a.za(),d=a.X()):(c=bb(a),d=ab(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}}t=$f.prototype;t.b=0;t.Td=0;t.X=function(){ag(this);for(var a=[],b=0;b<this.l.length;b++)a.push(this.ca[this.l[b]]);return a};t.za=function(){ag(this);return this.l.concat()};t.ta=function(a){return bg(this.ca,a)};
t.remove=function(a){return bg(this.ca,a)?(delete this.ca[a],this.b--,this.Td++,this.l.length>2*this.b&&ag(this),l):p};function ag(a){if(a.b!=a.l.length){for(var b=0,c=0;b<a.l.length;){var d=a.l[b];bg(a.ca,d)&&(a.l[c++]=d);b++}a.l.length=c}if(a.b!=a.l.length){for(var e={},c=b=0;b<a.l.length;)d=a.l[b],bg(e,d)||(a.l[c++]=d,e[d]=1),b++;a.l.length=c}}t.get=function(a,b){return bg(this.ca,a)?this.ca[a]:b};t.set=function(a,b){bg(this.ca,a)||(this.b++,this.l.push(a),this.Td++);this.ca[a]=b};t.clone=function(){return new $f(this)};
function bg(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function cg(a,b){var c;if(a instanceof cg)this.I=w(b)?b:a.I,dg(this,a.Xa),c=a.Zb,W(this),this.Zb=c,c=a.bb,W(this),this.bb=c,eg(this,a.Sb),c=a.Rb,W(this),this.Rb=c,fg(this,a.ra.clone()),c=a.Bb,W(this),this.Bb=c;else if(a&&(c=String(a).match(Yf))){this.I=!!b;dg(this,c[1]||"",l);var d=c[2]||"";W(this);this.Zb=d?decodeURIComponent(d):"";d=c[3]||"";W(this);this.bb=d?decodeURIComponent(d):"";eg(this,c[4]);d=c[5]||"";W(this);this.Rb=d?decodeURIComponent(d):"";fg(this,c[6]||"",l);c=c[7]||"";W(this);this.Bb=
c?decodeURIComponent(c):""}else this.I=!!b,this.ra=new gg(m,0,this.I)}t=cg.prototype;t.Xa="";t.Zb="";t.bb="";t.Sb=m;t.Rb="";t.Bb="";t.hf=p;t.I=p;
t.toString=function(){var a=[],b=this.Xa;b&&a.push(hg(b,ig),":");if(b=this.bb){a.push("//");var c=this.Zb;c&&a.push(hg(c,ig),"@");a.push(encodeURIComponent(String(b)));b=this.Sb;b!=m&&a.push(":",String(b))}if(b=this.Rb)this.bb&&"/"!=b.charAt(0)&&a.push("/"),a.push(hg(b,"/"==b.charAt(0)?jg:kg));(b=this.ra.toString())&&a.push("?",b);(b=this.Bb)&&a.push("#",hg(b,lg));return a.join("")};t.clone=function(){return new cg(this)};
function dg(a,b,c){W(a);a.Xa=c?b?decodeURIComponent(b):"":b;a.Xa&&(a.Xa=a.Xa.replace(/:$/,""))}function eg(a,b){W(a);b?(b=Number(b),(isNaN(b)||0>b)&&g(Error("Bad port number "+b)),a.Sb=b):a.Sb=m}function fg(a,b,c){W(a);b instanceof gg?(a.ra=b,a.ra.Gc(a.I)):(c||(b=hg(b,mg)),a.ra=new gg(b,0,a.I))}function ng(a,b,c){W(a);fa(c)||(c=[String(c)]);og(a.ra,b,c)}function W(a){a.hf&&g(Error("Tried to modify a read-only Uri"))}t.Gc=function(a){this.I=a;this.ra&&this.ra.Gc(a);return this};
function hg(a,b){return x(a)?encodeURI(a).replace(b,pg):m}function pg(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var ig=/[#\/\?@]/g,kg=/[\#\?:]/g,jg=/[\#\?]/g,mg=/[\#\?@]/g,lg=/#/g;function gg(a,b,c){this.F=a||m;this.I=!!c}
function qg(a){if(!a.k&&(a.k=new $f,a.b=0,a.F))for(var b=a.F.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=m,f=m;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=rg(a,e);a.add(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}t=gg.prototype;t.k=m;t.b=m;t.add=function(a,b){qg(this);this.F=m;a=rg(this,a);var c=this.k.get(a);c||this.k.set(a,c=[]);c.push(b);this.b++;return this};
t.remove=function(a){qg(this);a=rg(this,a);return this.k.ta(a)?(this.F=m,this.b-=this.k.get(a).length,this.k.remove(a)):p};t.ta=function(a){qg(this);a=rg(this,a);return this.k.ta(a)};t.za=function(){qg(this);for(var a=this.k.X(),b=this.k.za(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};t.X=function(a){qg(this);var b=[];if(a)this.ta(a)&&(b=qb(b,this.k.get(rg(this,a))));else{a=this.k.X();for(var c=0;c<a.length;c++)b=qb(b,a[c])}return b};
t.set=function(a,b){qg(this);this.F=m;a=rg(this,a);this.ta(a)&&(this.b-=this.k.get(a).length);this.k.set(a,[b]);this.b++;return this};t.get=function(a,b){var c=a?this.X(a):[];return 0<c.length?String(c[0]):b};function og(a,b,c){a.remove(b);0<c.length&&(a.F=m,a.k.set(rg(a,b),rb(c)),a.b+=c.length)}
t.toString=function(){if(this.F)return this.F;if(!this.k)return"";for(var a=[],b=this.k.za(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.X(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+encodeURIComponent(String(d[f])));a.push(h)}return this.F=a.join("&")};t.clone=function(){var a=new gg;a.F=this.F;this.k&&(a.k=this.k.clone(),a.b=this.b);return a};function rg(a,b){var c=String(b);a.I&&(c=c.toLowerCase());return c}
t.Gc=function(a){if(a&&!this.I){qg(this);this.F=m;var b=this.k,c=function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),og(this,c,a))};if("function"==typeof b.forEach)b.forEach(c,this);else if(ga(b)||x(b))L(b,c,this);else{var d;if("function"==typeof b.za)d=b.za();else if("function"!=typeof b.X)if(ga(b)||x(b)){d=[];for(var e=b.length,f=0;f<e;f++)d.push(f)}else d=bb(b);else d=j;b=Zf(b);e=b.length;for(f=0;f<e;f++)c.call(this,b[f],d&&d[f])}}this.I=a};function sg(){if(this&&this.Ld){var a=this.Ld;a&&"SCRIPT"==a.tagName&&tg(a,l,this.Wb)}}function tg(a,b,c){c!=m&&u.clearTimeout(c);a.onload=da;a.onerror=da;a.onreadystatechange=da;b&&window.setTimeout(function(){Bc(a)},0)}function ug(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);kb.call(this,c);this.code=a}C(ug,kb);function vg(a,b){this.Mf=new cg(a);this.be=b?b:"callback";this.Wb=5E3}var wg=0;
vg.prototype.send=function(a,b,c,d){var e=a||m,f=d||"_"+(wg++).toString(36)+B().toString(36);u._callbacks_||(u._callbacks_={});a=this.Mf.clone();if(e)for(var h in e)(!e.hasOwnProperty||e.hasOwnProperty(h))&&ng(a,h,e[h]);b&&(u._callbacks_[f]=function(a){xg(f,l);b.apply(j,arguments)},ng(a,this.be,"_callbacks_."+f));var k=a.toString(),n={timeout:this.Wb,de:l};h=n.document||document;var q=qc("SCRIPT");a={Ld:q,Wb:j};var r=new Zd(sg,a),s=m;d=n.timeout!=m?n.timeout:5E3;0<d&&(s=window.setTimeout(function(){tg(q,
l);r.La(new ug(1,"Timeout reached for loading script "+k))},d),a.Wb=s);q.onload=q.onreadystatechange=function(){if(!q.readyState||"loaded"==q.readyState||"complete"==q.readyState)tg(q,n.de||p,s),r.V(m)};q.onerror=function(){tg(q,l,s);r.La(new ug(0,"Error while loading script "+k))};dc(q,{type:"text/javascript",charset:"UTF-8",src:k});a=h.getElementsByTagName("HEAD");(!a||0==a.length?h.documentElement:a[0]).appendChild(q);ee(r,m,function(){xg(f,p);c&&c(e)},j);return{P:f,Wc:r}};
vg.prototype.cancel=function(a){a&&(a.Wc&&a.Wc.cancel(),a.P&&xg(a.P,p))};function xg(a,b){u._callbacks_[a]&&(b?delete u._callbacks_[a]:u._callbacks_[a]=da)};var Z=new function(){var a=this;a.o=function(){function b(){}function c(a){(a=a.data==YT.PlayerState.PLAYING?window.Hd:a.data==YT.PlayerState.ENDED?window.wf:m)&&a();X.update()}function d(){var b=new Lb(function(){return window.ie});b.Gd=function(){a.Fd()};b.start()}window.Th=function(){a.p=new YT.Player(yg("#stream")[0],{height:"390",width:"640",Oh:"1",Ih:{onReady:d,onStateChange:c,onError:b}})};Y.j().kb.m.setOnDisconnect(p);Y.j().kb.Kb.setOnDisconnect(0);a.Mc=[]};a.df=function(){return a.time()>=
a.length()};a.length=function(){return a.p.getDuration()};a.sd=function(b,c,d){a.p.stopVideo();a.time(0,l);window.Hd=function(){window.Hd=m;window.setTimeout(function(){Z.volume(0);a.time(0,l);a.play(l,l);Y.h(a.ua).length.set(a.length());c&&c()},2E3)};Y.h(b).once("value",function(c){var f=c.val();c=c.name();X.z.Vb(f.length);Y.h(b).w.set(Date.now());Y.h(b).xc.set($.$a);Y.w().push(c);a.p.loadVideoById(f.Fa);a.ua=b;d!=l&&(Y.h(b).Dc.set(++f.Dc),a.Yb());c=Y.data.j.current.Z.Va;for(var h in c)f=c[h],f.zd=
f.id==a.ua?"now-playing":""})};a.mute=function(b){b!=p?a.p.mute():a.p.unMute()};a.Fd=function(b){window.wf=function(){a.play(p);window.clearInterval(X.z.Id);b&&b()}};a.play=function(b,c){a.m=b==p?p:l;a.m?a.volume(100):a.volume(0);window.clearInterval(X.z.Id);a.m&&(X.z.Id=window.setInterval(function(){!X.z.Sd&&a.m&&a.time()},500));a.m?a.p.playVideo():a.p.pauseVideo();X.update();a.time();c!=l&&a.Yb()};a.Ec=function(a){a=a||0;return(60>a?"0:":"")+(10>a?"0":"")+([].add((new Date(0,0,0,0,0,a)).toLocaleTimeString().match(/[^0:].*/))[0]||
0)};a.Rd=function(b){b=b||$.$a;var c=Y.j(b);Y.j(Y.data.j.current.Yc).kb.Kb.off();Y.j().Yc.set(b);c.kb.Kb.on("value",function(b){b=b.val();var e=(Date.now()-b)/1E3;c.pa.once("value",function(b){var c=b.val(),d=c.time+(c.m?e:0);c.h!=a.ua?a.sd(c.h,function(){a.Mc[0]=window.setTimeout(function(){c.h==a.ua&&a.p.pauseVideo();a.Mc[1]=window.setTimeout(function(){c.h==a.ua&&(a.play(c.m,l),a.time(d,l))},3E3)},3E3)},l):(c.m?a.p.playVideo():a.p.pauseVideo(),a.time(d,l));X.update()})})};a.time=function(b,c){if((b=
0===b?1:b)&&5>Math.abs(b-a.time()))return b;b&&(a.R=b,c!=l?a.Yb():a.p.seekTo(b,l));if((b>=a.length()||a.p.getCurrentTime()>=a.length())&&a.m)a.m=p,a.R=0,X.update();a.R=a.p.getCurrentTime()||a.R;a.sf=a.Ec(a.R);a.R&&Y.j().kb.time.set(a.R);If(X.z,a.R);X.update();return a.R};a.Yb=function(){Y.j().pa.set({m:a.m,Kb:Date.now(),time:a.R,h:a.ua});X.update()};a.volume=function(b){window.isNaN(b)||a.p.setVolume(b);return a.p.getVolume()}};angular.module("Napster",[]).controller("Controller",["$scope",function(a){a.zh=$;a.Fh=Y;a.Xh=zg;a.Lc=Z;a.Zh=X;if($.Xb){a.Df=function(b){var c=a.$root.$$phase;"$apply"==c||"$digest"==c?b&&"function"===typeof b&&b():a.$apply(b)};var b=X.update;X.update=function(c){b();a.Df(c)};var c={},d=function(a,b,d){function e(c){a[b]=c.val();X.update()}c[d]=c[d]||e;return c[d]},e={},f=function(a,b){function c(b){a[b.name()]=b.val();X.update()}e[b]=e[b]||c;return e[b]},h=function(a){return bb(a).exclude("processed").filter(function(b){return"string"==
typeof a[b]})};Y.w().limit(500).on("child_added",function(a){f(Y.data.w)(a);h(Y.data.w).forEach(function(a){var b=Y.data.w[a],c="track"+b;Y.h(b).off("value",d(Y.data.h,b,c));Y.h(b).on("value",function(a){d(Y.data.h,b,c)(a);Y.data.w.Va[b]=a.val()})})});Y.j().on("value",function(a){d(Y.data.j,$.$a)(a);var b=Y.data.j[$.$a];if(b.Hb==p)Y.j().Hb.set(l);else{for(var c in b.qc){a=b.qc[c];var e="group"+a,s=e+"members",z=e+"messages",e=e+"name",G=Y.group(a).hb().limit(500),A=Y.group(a).ib().limit(500),Ub=Y.group(a).name;
Y.data.group[c]=Y.data.group[c]||{hb:{},ib:{},name:""};G.off("child_added",f(Y.data.group[a].hb,s));G.on("child_added",f(Y.data.group[a].hb,s));A.off("child_added",f(Y.data.group[a].ib,z));A.on("child_added",f(Y.data.group[a].ib,z));Ub.off("value",d(Y.data.group[a],"name",e));Ub.on("value",d(Y.data.group[a],"name",e))}b.Z=b.Z||{};b.Z.Va=b.Z.Va||{};h(b.Z).map(function(a){return b.Z[a]}).add(b.pa.h).unique().compact().forEach(function(a){var c="track"+a;console.log(JSON.stringify(Y));Y.h(a).off("value",
d(Y.data.h,a,c));Y.h(a).on("value",function(e){d(Y.data.h,a,c)(e);var f=e.val();f.id=a;f.length=Z.Ec(f.length);f.w=(new Date(f.w)).format("{12hr}{tt}, {yyyy}-{MM}-{dd}");$.bd(f.xc,function(c){f.xc=c;f.zd="";if(f.id==(Z.ua||b.pa.h))f.zd="now-playing",b.Sh=f;b.Z.Va[a]=f;X.update();Z.p.stopVideo&&!window.lf&&(window.lf=l,Z.Rd())})})});Y.data.j.current=b;window.ie=l;X.update()}})}}]);var zg=new function(){var a=this;a.wd=function(a,c,d){a={V:"callback",type:"master",Bf:a};c&&("artist"in a&&g(Error('The object already contains the key "artist"')),a.artist=c);(new vg("http://api.discogs.com/database/search")).send(a,function(a){var b=[],c=[];(cb(a,"data","results")||[]).slice(0,20).forEach(function(a){var d=(a.title||"").split("-"),e=d.slice(1).join("").trim(),d=d[0].split("(")[0].trim(),r=(a.Cb||[])[0];a=a.$b;var s=$.hash(e+d+a);b.add({title:e,rb:d,Cb:r,$b:a,id:s});c.add(new Zd)});
d(b,c)})};a.search=function(b,c,d){a.wd(b,c,function(b,c){var h=new ge(c,p,l);ee(h,function(a){return nb(a,function(a){return a[1]})},m,j);for(var k=0;k<b.length;++k){var n=b[k];a.Lc(n.title,n.rb,k,function(a,b){c[b].V(a,b)})}ee(h,function(a){function c(a){return a.Fa}a.forEach(function(a,c){var d=b[c];d.Fa=a.Fa;d.Ga=a.Ga;d.length=a.length});a=b.findAll(c).unique(c).sortBy(function(a){return a.Ga},l);a.forEach(function(a){var b=Y.h(a.id);b.update({rb:a.rb,Cb:a.Cb,length:(a.length||0).toNumber(),title:a.title,
$b:(a.$b||42).toNumber(),Fa:a.Fa,Ga:(a.Ga||0).toNumber()});b.update({Dc:0})});d(a)},m,j)})};a.Lc=function(a,c,d,e){c=c.replace("Various","Song");(new vg("http://gdata.youtube.com/feeds/api/videos")).send({V:"callback",alt:"json-in-script",$h:2,Bf:"{0} {1} {2}".assign({"0":a,1:c,2:[].reduce(function(d,e){var k=e.toLowerCase();return d+(!a.toLowerCase().has(k)&&!c.toLowerCase().has(k)?' -"{0}"'.assign({"0":k}):"")},"")})},function(a){if(!cb(a,"feed","entry"))return e({},d);a=a.Jh.Hh.map(function(a){var b=
(cb(a,"id","$t")||"").split("video:")[1],c=(cb(a,"yt$statistics","viewCount")||0).toNumber(),d=cb(a,"media$group","media$content",0,"duration"),e=((a.ai||{}).find(function(a){return"embed"==a.action})||{}).Vh;a=cb(a,"app$control","yt$state");return{Fa:b,Ga:c,length:d,cf:!("allowed"!=e||a)}}).findAll(function(a){return a.cf}).slice(0,5).sortBy(function(a){return a.Ga},l);e(a[0]||{},d)})}};var $=new function(){function a(a){return"{0}@firebase.com".assign({"0":a})}var b=this;b.o=function(){b.xb=5E6;b.Xb=Xf.get("napsterfm-token");b.$a=Xf.get("napsterfm-userid");b.Oc=Xf.get("napsterfm-username");b.Xb&&(Y.root.auth(b.Xb),Y.j().Hb.set(l),Y.j().Hb.setOnDisconnect(p))};b.bd=function(a,b){Y.j(a).Oc.once("value",function(a){b(a.val().replace("@firebase.com",""))})};b.hash=function(a){var b=new Tf(new Yd,"napster");b.reset();b.update(a);return b.ab().map(function(a){return a.toString(36)}).join("")};
b.login=function(c,d){var e=new Zd;(new FirebaseAuthClient(Y.root)).login("password",a(c),d,function(a,d,k){a?e.V(a):(Xf.set("napsterfm-token",d,b.xb),Xf.set("napsterfm-userid",k.id,b.xb),Xf.set("napsterfm-username",c,b.xb),document.location.reload(l))});return e};b.of=function(){Y.root.unauth();Xf.remove("napsterfm-token");Xf.remove("napsterfm-userid");Xf.remove("napsterfm-username");document.location.reload(l)};b.createUser=function(b,d){var e=new Zd;(new FirebaseAuthClient(Y.root)).createUser(a(b),
d,function(a){a&&e.V(a)});return e};b.changePassword=function(b,d,e){var f=new Zd;(new FirebaseAuthClient(Y.root)).changePassword(a(b),d,e,function(a){a&&f.V(a)});return f}};var X=new function(){var a=this;a.o=function(){window.onhashchange=function(){function a(b,c,f){b=yg(b);for(var h=0;h<b.length;++h){var k=b[h],n=f?f(k):k;k.getAttribute(c)==window.location.hash?Pb(n,"active"):Qb(n,"active")}}a(".navbar a","href",function(a){return a.parentNode});a("[hash-location]","hash-location")};if(window.location.hash)window.onhashchange();else window.location.hash=yg(".navbar li.active")[0].$c()[0].getAttribute("href");var b=new De;b.Vc=tb;Be(b,yg("#library-table")[0]);a.z=
new Sf;b=a.z;b.ma&&l!=b.tc&&Ff(b);b.tc=l;a.z.xd=l;a.z.onclick=function(){a.z.Sd=l;Z.time(a.z.s());window.setTimeout(function(){a.z.Sd=p},1E3)};Be(a.z,yg("#player .slider")[0])};a.update=function(){a.yf=window.isNaN(Z.R)?"loading":"";a.Af=Z.m?"playing":"paused"}};var Ag=new function(){this.log=function(a){console.log(a)};this.mf=function(){console.log("foo")};this.nf=function(a){console.log(a.val())};this.pf=function(a){Y.j().Z.push(a[0].id)}};var Y=new function(){var a=this;a.data={group:{},w:{Va:{}},h:{},j:{}};a.root=new Firebase("https://napsterfm.firebaseio.com/");a.group=function(b){b=(b||0).toString();var c=a.root.child("group").child(b);c.hb=c.child("members");c.Qh=function(a){a=a.toString();return c.hb.child(a)};c.ib=c.child("messages");c.message=function(a){a=a.toString();a=c.ib.child(a);a.Ah=a.child("author");a.Dh=a.child("created");a.text=a.child("text");return a};c.name=c.child("name");return c};a.w=function(){return a.root.child("lastPlayed")};
a.h=function(b){b=b.toString();b=a.root.child("track").child(b);b.rb=b.child("artist");b.Cb=b.child("genre");b.w=b.child("lastPlayed");b.xc=b.child("lastPlayedBy");b.length=b.child("length");b.Dc=b.child("playCount");b.title=b.child("title");b.$b=b.child("year");b.Fa=b.child("youtubeid");b.Ga=b.child("youtubeviews");return b};a.j=function(b){b=(b||$.$a).toString();var c=a.root.child("user").child(b);c.qc=c.child("groups");c.group=function(a){a=a.toString();return c.qc.child(a)};c.Yc=c.child("following");
c.We=c.child("hotlist");c.Nh=function(a){a=a.toString();return c.We.child(a)};c.Hb=c.child("isOnline");c.pa=c.child("nowPlaying");c.kb={m:c.pa.child("isPlaying"),Kb:c.pa.child("lastChange"),time:c.pa.child("time"),h:c.pa.child("track")};c.Z=c.child("library");c.Ph=function(a){a=a.toString();return c.Z.child(a)};c.Lf=c.child("transfers");c.Yh=function(a){a=a.toString();a=c.Lf.child(a);a.from=a.child("from");a.h=a.child("track");return a};c.Oc=c.child("username");return c}};function yg(a){var b=Bg.qa(a),c=1>b.length;c&&1>(new DOMParser).parseFromString(a,"text/xml").getElementsByTagName("parsererror").length?(c=Bg.createElement("div"),c.innerHTML=a,b[0]=c.firstChild):c&&(b[0]={});for(var d in Bg){for(a=0;a<b.length;++a)b[a][d]=b[a][d]||Bg[d].fill(b[a]);b[d]=b[0]&&b[0][d]}return b}
var Bg={append:wc,appendChild:vc,canHaveChildren:uc,fe:Qc,contains:Pc,Ha:function(a,b,c){return mc(document,arguments)},createElement:qc,he:function(a,b,c){return rc(document,a,b,!!c)},createTextNode:function(a){return document.createTextNode(a)},oe:Tc,pe:Yc,qe:$c,se:Dc,te:md,ue:kd,ve:ld,we:jd,$c:Ec,ye:function(){return tc()?"CSS1Compat":"BackCompat"},kc:function(){return document},ze:function(){return ic(window)},Ma:function(){return jc(document)},Ae:function(){return kc(document)},Db:S,c:Zb,lc:cc,
mc:bc,Be:$b,Ce:Fc,De:Uc,Ee:Vc,Fe:Hc,Ge:Ic,He:Kc,Ie:id,Je:gd,Ke:hd,Le:Xc,Me:T,Lh:function(a){return S((a||u||window).document).Ma()},Ne:Oc,Oe:Jc,Pe:Lc,Mh:function(a){var b=[];fd(a,b,p);return b.join("")},Qe:ed,Re:fc,pc:lc,Xe:function(a){return sc(document,a)},$e:Ac,af:zc,bf:yc,sc:tc,isElement:Mc,ef:cd,ff:oc,gf:pc,kf:Nc,qa:Ud,Kd:xc,removeNode:Bc,Cf:Cc,Ff:dd,Gf:dc,Hf:Wc},Cg;for(Cg in Bg)yg[Cg]=Bg[Cg];$.o();X.o();Z.o();window.authentication=$;window.authentication.cookieAge=$.xb;window.authentication.token=$.Xb;window.authentication.userid=$.$a;window.authentication.username=$.Oc;window.authentication.init=$.o;window.authentication.getUsername=$.bd;window.authentication.hash=$.hash;window.authentication.login=$.login;window.authentication.logout=$.of;window.authentication.createUser=$.createUser;window.authentication.changePassword=$.changePassword;window.closurequery={};window.controllers={};window.datastore=Y;
window.datastore.data=Y.data;window.datastore.root=Y.root;window.datastore.group=Y.group;window.datastore.lastPlayed=Y.w;window.datastore.track=Y.h;window.datastore.user=Y.j;window.debug=Ag;window.debug.log=Ag.log;window.debug.logFoo=Ag.mf;window.debug.logVal=Ag.nf;window.debug.lucky=Ag.pf;window.init={};window["require.goog"]={};window["require.napster"]={};window.services=zg;window.services.metadata=zg.wd;window.services.search=zg.search;window.services.stream=zg.Lc;window.stream=Z;
window.stream.isPlaying=Z.m;window.stream.newTime=Z.R;window.stream.newTimeProcessed=Z.sf;window.stream.player=Z.p;window.stream.syncTimeouts=Z.Mc;window.stream.init=Z.o;window.stream.isFinished=Z.df;window.stream.length=Z.length;window.stream.loadTrack=Z.sd;window.stream.mute=Z.mute;window.stream.onFinished=Z.Fd;window.stream.play=Z.play;window.stream.processTime=Z.Ec;window.stream.sync=Z.Rd;window.stream.time=Z.time;window.stream.updateNowPlaying=Z.Yb;window.stream.volume=Z.volume;window.ui=X;
window.ui.pageLoadingClass=X.yf;window.ui.playButtonClass=X.Af;window.ui.slider=X.z;window.ui.init=X.o;window.ui.update=X.update;window.datastore.data.group=Y.data.group;window.datastore.data.lastPlayed=Y.data.w;window.datastore.data.lastPlayed.processed=Y.data.w.Va;window.datastore.data.track=Y.data.h;window.datastore.data.user=Y.data.j;window.datastore.data.user.current=Y.data.j.current;
